### ISSUE TITLE
"Commit on successful build" does not cause docker slave to be committed

### ISSUE THREAD

**Issue by daveshepherd** [jenkinsci/docker-plugin#115]
Issue #84 might be related, but refers to the commit working all the time. However, some of the comments suggest that others are getting the same issue that I am seeing.

I have set up Jenkins with the docker-plugin and configured it to use the docker API. When I run a job a slave is created and the job successfully completes. However the slave instance is not committed despite the job configuration.

I am using:
Docker: 1.2.0
Jenkins: 1.589
docker-plugin: 0.8

I have put together a Jenkins docker image that you can use to reproduce this issue:

I use the example Jenkins slave image from the [wiki page](https://wiki.jenkins-ci.org/display/JENKINS/Docker+Plugin), so make sure you have it available on the Docker server:

`docker pull evarga/jenkins-slave`

Start the Jenkins docker container:
`docker run -p 8080:8080 daveshepherd/jenkins-docker:1.589`

Browse to: http://localhost:8080/configure
and check that the "Docker URL" is correct for your setup

Browse to: http://localhost:8080/ and start the "docker-plugin-test" job

The job should pass, but the slave has not been committed despite the job being set up to "commit on successful build", list your images to check:

`docker images`

The node instance has been removed now that it has stopped, despite the "clean local images" being unchecked:

`docker ps -a`

If you look at the Jenkins log that is shown from the running jenkins server instance then you will see the following error which might looks like it might be related:

```
INFO: docker-plugin-test #2 main build action completed: SUCCESS
Nov 13, 2014 12:03:02 PM hudson.remoting.SynchronousCommandTransport$ReaderThread run
SEVERE: I/O error in channel b02a204851c6@docker
java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:50)
Caused by: java.io.EOFException
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2325)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2794)
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:801)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:40)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)
```

**Comment by illkurok** [comment]
Also running into this problem:

Docker version 1.4.1, build 5bc2ff8
Jenkins ver. 1.596
Docker plugin version 0.8

```
I/O error in channel 170d4191e4aa@dockertest
java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:50)
Caused by: java.io.EOFException
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2328)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2797)
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:802)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:40)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)
```

Doing some more digging on my end.

**Comment by robertfirek** [comment]
I also have the same problem. In addition a slave node created during the process doesn't disappear from the node list. This doesn't allow to create new node if you set cap on instances. 

Docker version 1.0.1, build 990021a
Jenkins ver. 1.599
Docker plugin version 0.8

```
I/O error in channel 191426b9683b@Docker
java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:50)
Caused by: java.io.EOFException
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2328)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2797)
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:802)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:40)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)
```

**Comment by KostyaSha** [comment]
Tag issue... fixed in master...
