### ISSUE TITLE
FATAL: HTTP 304 Not Modified

### ISSUE THREAD

**Issue by ninja-** [jenkinsci/docker-plugin#121]
So...no matter what I do I fail with this when I try to build a project.

```
FATAL: HTTP 304 Not Modified
javax.ws.rs.RedirectionException: HTTP 304 Not Modified
    at org.glassfish.jersey.client.JerseyInvocation.createExceptionForFamily(JerseyInvocation.java:949)
    at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:936)
    at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:822)
    at org.glassfish.jersey.client.JerseyInvocation.access$600(JerseyInvocation.java:90)
    at org.glassfish.jersey.client.JerseyInvocation$3.call(JerseyInvocation.java:693)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:422)
    at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:689)
    at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:405)
    at org.glassfish.jersey.client.proxy.WebResourceFactory.invoke(WebResourceFactory.java:318)
    at com.sun.proxy.$Proxy58.startContainer(Unknown Source)
    at com.nirima.docker.client.DockerClient$Container.start(DockerClient.java:200)
    at com.nirima.jenkins.plugins.docker.builder.DockerBuilderControlOptionProvisionAndStart.execute(DockerBuilderControlOptionProvisionAndStart.java:35)
    at com.nirima.jenkins.plugins.docker.builder.DockerBuilderControl.perform(DockerBuilderControl.java:60)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
    at hudson.model.Build$BuildExecution.build(Build.java:199)
    at hudson.model.Build$BuildExecution.doRun(Build.java:160)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:533)
    at hudson.model.Run.execute(Run.java:1759)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:89)
    at hudson.model.Executor.run(Executor.java:240)
```

**Comment by haysclark** [comment]
I'm still seeing this issue for "Provision & Start Container" with a evarga/jenkins-slave container.

```Building on master in workspace /var/jenkins_home/jobs/Foo/workspace
FATAL: HTTP 304 Not Modified
javax.ws.rs.RedirectionException: HTTP 304 Not Modified
	at org.glassfish.jersey.client.JerseyInvocation.createExceptionForFamily(JerseyInvocation.java:949)
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:936)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:822)
	at org.glassfish.jersey.client.JerseyInvocation.access$600(JerseyInvocation.java:90)
	at org.glassfish.jersey.client.JerseyInvocation$3.call(JerseyInvocation.java:693)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:422)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:689)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:405)
	at org.glassfish.jersey.client.proxy.WebResourceFactory.invoke(WebResourceFactory.java:318)
	at com.sun.proxy.$Proxy60.startContainer(Unknown Source)
	at com.nirima.docker.client.DockerClient$Container.start(DockerClient.java:187)
	at com.nirima.jenkins.plugins.docker.builder.DockerBuilderControlOptionProvisionAndStart.execute(DockerBuilderControlOptionProvisionAndStart.java:35)
	at com.nirima.jenkins.plugins.docker.builder.DockerBuilderControl.perform(DockerBuilderControl.java:58)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
	at hudson.model.Build$BuildExecution.build(Build.java:199)
	at hudson.model.Build$BuildExecution.doRun(Build.java:160)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:533)
	at hudson.model.Run.execute(Run.java:1745)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)```

**Comment by KostyaSha** [comment]
@haysclark 0.8 is super ancient version we doesn't care anymore about it.
