### ISSUE TITLE
List of errors...

### ISSUE THREAD

**Issue by ninja-** [jenkinsci/docker-plugin#124]
So...this plugin works great on the frontend but spams with errors a lot.
Some of them are harmless, other can break things but in the end docker-plugin fixes itself and always does a successful build.

Sorry if packing into one issue is a problem, but I think most of them are only cosmetic annoyances that should be fixed anyway.

```
Nov 21, 2014 9:26:19 PM com.nirima.jenkins.plugins.docker.utils.RetryingComputerLauncher launch
INFO: Launch failed, pausing before retry.
Nov 21, 2014 9:26:19 PM hudson.slaves.NodeProvisioner update
INFO: Image of evarga/jenkins-slave provisioning successfully completed. We have now 2 computer(s)
[11/21/14 21:26:24] SSH Launch of 3e64b62f55c6@cloud on 192.168.0.5 failed in 2 ms
Nov 21, 2014 9:26:55 PM hudson.slaves.CloudRetentionStrategy check
INFO: Disconnecting 3e64b62f55c6@cloud
Nov 21, 2014 9:26:55 PM com.nirima.jenkins.plugins.docker.DockerSlave _terminate
SEVERE: Failed to stop instance 3e64b62f55c69dcd39f6b8bf82a26bda65ac743deeb3da3f689a907940cc55be for slave 3e64b62f55c6@cloud due to exception
javax.ws.rs.NotFoundException: HTTP 404 Not Found
        at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:917)
        at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:822)
        at org.glassfish.jersey.client.JerseyInvocation.access$600(JerseyInvocation.java:90)
        at org.glassfish.jersey.client.JerseyInvocation$3.call(JerseyInvocation.java:693)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:422)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:689)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:405)
        at org.glassfish.jersey.client.proxy.WebResourceFactory.invoke(WebResourceFactory.java:318)
        at com.sun.proxy.$Proxy55.stopContainer(Unknown Source)
        at com.nirima.docker.client.DockerClient$Container.stop(DockerClient.java:195)
        at com.nirima.jenkins.plugins.docker.DockerSlave._terminate(DockerSlave.java:87)
        at hudson.slaves.AbstractCloudSlave.terminate(AbstractCloudSlave.java:62)
        at hudson.slaves.CloudRetentionStrategy.check(CloudRetentionStrategy.java:56)
        at hudson.slaves.CloudRetentionStrategy.check(CloudRetentionStrategy.java:41)
        at hudson.slaves.ComputerRetentionWork.doRun(ComputerRetentionWork.java:66)
        at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)  
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

Nov 21, 2014 9:26:55 PM com.nirima.docker.client.DockerClient$Container remove
WARNING: Remove container 3e64b62f55c69dcd39f6b8bf82a26bda65ac743deeb3da3f689a907940cc55be not found
```
That's probably harmless but annoying. Trying to remove an instance that already exited and thus was removed by docker, I guess?
https://github.com/jenkinsci/docker-plugin/blob/master/src/main/java/com/nirima/jenkins/plugins/docker/DockerSlave.java#L89

```
Nov 21, 2014 9:26:15 PM hudson.remoting.SynchronousCommandTransport$ReaderThread run
SEVERE: I/O error in channel 3e64b62f55c6@cloud
java.io.IOException: Unexpected termination of the channel
        at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:50)
Caused by: java.io.EOFException
        at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2325)
        at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2794)
        at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:801)
        at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
        at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:40)
        at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
        at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)
```
Very annoying, probably harmless...
 
```
Nov 21, 2014 9:26:19 PM hudson.slaves.NodeProvisioner update
WARNING: Provisioned slave Image of evarga/jenkins-slave failed to launch
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at com.google.common.base.Throwables.propagate(Throwables.java:156)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:183)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:160)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:188)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:176)
        ... 6 more
Caused by: java.lang.NullPointerException
        at hudson.plugins.sshslaves.SSHLauncher.launch(SSHLauncher.java:743)
        at hudson.slaves.DelegatingComputerLauncher.launch(DelegatingComputerLauncher.java:56)
        at com.nirima.jenkins.plugins.docker.utils.RetryingComputerLauncher.launch(RetryingComputerLauncher.java:38)
        at hudson.slaves.DelegatingComputerLauncher.launch(DelegatingComputerLauncher.java:56)
        at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:241)
        ... 5 more
```
???
Happens at random, configuration is constant.

```
Nov 21, 2014 9:42:59 PM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
INFO: Started provisioning Image of evarga/jenkins-slave from cloud with 1 executors. Remaining excess workload: 0
Launching evarga/jenkins-slave
Nov 21, 2014 9:42:59 PM com.nirima.jenkins.plugins.docker.DockerComputerLauncher getSSHLauncher
INFO: Creating slave SSH launcher for 192.168.0.5:49233
Nov 21, 2014 9:42:59 PM com.nirima.jenkins.plugins.docker.DockerComputerLauncher getSSHLauncher
INFO: Creating slave SSH launcher for 192.168.0.5:49234
Nov 21, 2014 9:42:59 PM hudson.slaves.CloudRetentionStrategy check
INFO: Disconnecting ea867eeae7e9@cloud
[11/21/14 21:42:59] SSH Launch of ea867eeae7e9@cloud on 192.168.0.5 failed in 49 ms
Nov 21, 2014 9:42:59 PM com.nirima.jenkins.plugins.docker.DockerCloud$1 call
SEVERE: Error in provisioning; slave=DockerSlave{...........}, template=DockerTemplate{image=evarga/jenkins-slave, parent=DockerCloud{name=cloud, serverUrl=http://192.168.0.5:1234}}
java.util.concurrent.ExecutionException: java.io.IOException: Slave failed to connect, even though the launcher didn't report it. See the log output for details.
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:188)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:176)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:160)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Slave failed to connect, even though the launcher didn't report it. See the log output for details.
        at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:262)
        ... 5 more
```
?

**Comment by KostyaSha** [comment]
Please try #210
