### ISSUE TITLE
java.lang.NoSuchMethodError: hudson.plugins.sshslaves.SSHLauncher

### ISSUE THREAD

**Issue by guss77** [jenkinsci/docker-plugin#130]
I'm running Jenkins with the docker plugin, and when I try to run a build, I get this output:

    Dec 25, 2014 6:05:13 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
    INFO: Excess workload after pending Spot instances: 1
    Dec 25, 2014 6:05:13 PM com.nirima.jenkins.plugins.docker.DockerCloud countCurrentDockerSlaves
    INFO: Images found: [Image{repository=null, tag=null, id=8880612971b0e41ecc5de6943c9680bb8dc08027dbae4d3a275ac827293cbf2e, created=1419452556, size=0, virtualSize=610837405}]
    Dec 25, 2014 6:05:13 PM com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
    INFO: Provisioning for AMI evarga/jenkins-slave; Estimated number of total slaves: 3; Estimated number of slaves for ami evarga/jenkins-slave: 2
    Launching evarga/jenkins-slave
    Dec 25, 2014 6:05:13 PM hudson.slaves.NodeProvisioner update
    INFO: Started provisioning Image of evarga/jenkins-slave from local with 1 executors. Remaining excess workload:0.0
    Dec 25, 2014 6:05:13 PM com.nirima.jenkins.plugins.docker.DockerComputerLauncher getSSHLauncher
    INFO: Creating slave SSH launcher for docker:49155
    Dec 25, 2014 6:05:23 PM hudson.slaves.NodeProvisioner update
    WARNING: Provisioned slave Image of evarga/jenkins-slave failed to launch
    java.lang.NoSuchMethodError: hudson.plugins.sshslaves.SSHLauncher.<init>(Ljava/lang/String;ILcom/cloudbees/plugins/credentials/common/StandardUsernameCredentials;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Integer;)V
        at com.nirima.jenkins.plugins.docker.DockerComputerLauncher.getSSHLauncher(DockerComputerLauncher.java:59)
        at com.nirima.jenkins.plugins.docker.DockerComputerLauncher.makeLauncher(DockerComputerLauncher.java:41)
        at com.nirima.jenkins.plugins.docker.DockerComputerLauncher.<init>(DockerComputerLauncher.java:37)
        at com.nirima.jenkins.plugins.docker.DockerTemplate.provision(DockerTemplate.java:206)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:164)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:159)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

I've encountered this issue with Jenkins 1.565.3 with SSH Slaves plugin updated to 1.9, and I also tried to run the weekly Jenkins build 1.585 and encountered the same issue.

I'm using the docker plugin version 0.7, as installed using the Jenkins update center. Even though the Jenkins plugins web site says there's a version 0.8, the update center does not show it.

**Comment by ryrydundun** [comment]
Have you figured this out? We are having the same issue.

**Comment by KostyaSha** [comment]
please try #210 and reopen if issue still exists plus provide https://wiki.jenkins-ci.org/display/JENKINS/How+to+report+an+issue#Howtoreportanissue-WhatinformationtoprovideforEnvironmentandDescription
