### ISSUE TITLE
Jenkins 1.598 doesn't launch containers

### ISSUE THREAD

**Issue by mkamlesh** [jenkinsci/docker-plugin#161]
Hello,

I am trying out docker-plugin setup with Jenkins (1.598) and Docker(1.4.1) CentOS 6.5 on CentOS 6.5 VMs and it seems that Jenkins just doesn't initiate container launch process. 

Cloud configuration seems correct because "Test Connection" link correctly shows Docker version back to me. 

Also, link "docker-plugin/server/ci-docker/" shows that it recognized the container which I launched by hand. Only Jenkins doesn't seem to be launching containers even though container cap is not reached.

# docker info
Containers: 1
Images: 24
Storage Driver: devicemapper
 Pool Name: docker-253:0-782030-pool
 Pool Blocksize: 65.54 kB
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 1.216 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 2.023 MB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.89-RHEL6 (2014-09-01)
Execution Driver: native-0.2
Kernel Version: 2.6.32-431.el6.x86_64
Operating System: <unknown>
CPUs: 1
Total Memory: 3.79 GiB
Name: xxxxx

I don't find anything particularly bad in docker logs on docker host or in jenkins logs.

Could someone please let me know if I am missing something or if this is genuine issue with this pair of versions?

**Comment by mkamlesh** [comment]
If needed, here is a dockerfile used to create the image:

#Automation Launcher

FROM ubuntu

RUN apt-get update
RUN apt-get install -y python git wget python2.7-dev gcc vim zlib1g-dev libxml2-dev libxslt1-dev openjdk-7-jdk supervisor openssh-server

RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python get-pip.py

RUN git clone https://github.com/lczub/TestLink-API-Python-client.git
WORKDIR TestLink-API-Python-client
RUN python setup.py install
RUN pip install --upgrade lxml validictory requests argparse
RUN useradd jenkins
RUN echo "jenkins:jenkins" | chpasswd
RUN mkdir -p /home/jenkins
RUN chown jenkins:jenkins /home/jenkins
RUN mkdir -p /var/run/sshd
RUN sed -i 's|session    required     pam_loginuid.so|session    optional     pam_loginuid.so|g' /etc/pam.d/sshd
RUN mkdir -p /var/run/supervisord
ADD supervisord.conf /etc/supervisor/conf.d/supervisord.conf
EXPOSE 22
CMD ["/usr/bin/supervisord"]

**Comment by KostyaSha** [comment]
As usual, firstly try working container mentioned in wiki page.

**Comment by mkamlesh** [comment]
Yes, I am able to launch container just fine. I am also able to ssh into that container with jenkins user created as part of docker build.

**Comment by thomassuckow** [comment]
I would encourage you to add a logger to Jenkins of "com.nirima" at the INFO level.

I would expect to see something along the lines of:
```
Asked to provision 1 slave(s) for: mylabel
Feb 12, 2015 8:02:04 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
Will provision "foo_container" for: mylabel
Feb 12, 2015 8:02:04 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
Provisioning "foo_container" number 0 on "ci-docker"; Total containers: 0
```

If you do not and the job is starving in the Queue waiting for an executor, you may be experiencing a bug I have been trying to track down. I have a "fix" as a PR on Jenkins, though I have yet to figure out how the bug gets triggered in the first place.

**Comment by diranged** [comment]
Near as I can tell, I'm running into the same problem. Jenkins 1.598, Docker Plugin v0.8, Docker 1.4.1 and the stock docker container `evarga/jenkins-slave   latest              8880612971b0        8 weeks ago         610.8 MB`.

## Docker Debug Log
```
DEBU[0069] Calling GET /containers/json                 
INFO[0069] GET /containers/json?all=false&limit=-1&since=&before=&size=false 
INFO[0069] +job containers()                            
INFO[0069] -job containers() = OK (0)                   
DEBU[0069] Calling GET /containers/json                 
INFO[0069] GET /containers/json?all=false&limit=-1&since=&before=&size=false 
INFO[0069] +job containers()                            
INFO[0069] -job containers() = OK (0)                   
DEBU[0069] Calling GET /images/json                     
INFO[0069] GET /images/json?filter=evarga/jenkins-slave&all=true 
INFO[0069] +job images()                                
INFO[0069] -job images() = OK (0)                       
DEBU[0069] Calling GET /images/{name:.*}/json           
INFO[0069] GET /images/evarga%2Fjenkins-slave/json      
INFO[0069] +job image_inspect(evarga/jenkins-slave)     
INFO[0069] -job image_inspect(evarga/jenkins-slave) = OK (0) 
DEBU[0069] Calling POST /containers/create              
INFO[0069] POST /containers/create                      
INFO[0069] +job create()                                
INFO[0069] +job log(create, 01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c, evarga/jenkins-slave:latest) 
INFO[0069] -job log(create, 01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c, evarga/jenkins-slave:latest) = OK (0) 
INFO[0069] -job create() = OK (0)                       
DEBU[0069] Calling POST /containers/{name:.*}/start     
INFO[0069] POST /containers/01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c/start 
INFO[0069] +job start(01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c) 
INFO[0069] +job allocate_interface(01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c) 
INFO[0069] -job allocate_interface(01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c) = OK (0) 
INFO[0069] +job allocate_port(01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c) 
DEBU[0069] /sbin/iptables, [--wait -t nat -A DOCKER -p tcp -d 0/0 --dport 49153 ! -i docker0 -j DNAT --to-destination 172.17.0.2:22] 
DEBU[0069] /sbin/iptables, [--wait -I FORWARD ! -i docker0 -o docker0 -p tcp -d 172.17.0.2 --dport 22 -j ACCEPT] 
INFO[0069] -job allocate_port(01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c) = OK (0) 
INFO[0069] +job log(start, 01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c, evarga/jenkins-slave:latest) 
INFO[0069] -job log(start, 01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c, evarga/jenkins-slave:latest) = OK (0) 
INFO[0069] -job start(01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c) = OK (0) 
DEBU[0069] Calling GET /containers/{name:.*}/json       
INFO[0069] GET /containers/01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c/json 
INFO[0069] +job container_inspect(01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c) 
INFO[0069] -job container_inspect(01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c) = OK (0) 
DEBU[0071] Calling GET /containers/{name:.*}/json       
INFO[0071] GET /containers/01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c/json 
INFO[0071] +job container_inspect(01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c) 
INFO[0071] -job container_inspect(01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c) = OK (0) 
DEBU[0071] Calling GET /containers/{name:.*}/json       
INFO[0071] GET /containers/01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c/json 
INFO[0071] +job container_inspect(01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c) 
INFO[0071] -job container_inspect(01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c) = OK (0) 
DEBU[0074] Calling GET /containers/{name:.*}/json       
INFO[0074] GET /containers/01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c/json 
INFO[0074] +job container_inspect(01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c) 
INFO[0074] -job container_inspect(01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c) = OK (0) 
DEBU[0074] Calling GET /containers/{name:.*}/json       
INFO[0074] GET /containers/01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c/json 
INFO[0074] +job container_inspect(01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c) 
INFO[0074] -job container_inspect(01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c) = OK (0) 
DEBU[0074] Calling GET /containers/{name:.*}/json       
INFO[0074] GET /containers/01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c/json 
INFO[0074] +job container_inspect(01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c) 
INFO[0074] -job container_inspect(01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c) = OK (0) 
DEBU[0074] Calling GET /containers/{name:.*}/json       
INFO[0074] GET /containers/01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c/json 
INFO[0074] +job container_inspect(01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c) 
INFO[0074] -job container_inspect(01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c) = OK (0) 
DEBU[0076] Calling GET /containers/{name:.*}/json       
INFO[0076] GET /containers/01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c/json 
INFO[0076] +job container_inspect(01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c) 
INFO[0076] -job container_inspect(01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c) = OK (0) 
DEBU[0076] Calling POST /containers/{name:.*}/stop      
INFO[0076] POST /containers/01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c/stop 
INFO[0076] +job stop(01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c) 
DEBU[0076] Sending 15 to 01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c 
INFO[0076] Container 01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c failed to exit within 0 seconds of SIGTERM - using the force 
DEBU[0076] Sending 9 to 01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c 
INFO[0076] +job log(die, 01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c, evarga/jenkins-slave:latest) 
INFO[0076] -job log(die, 01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c, evarga/jenkins-slave:latest) = OK (0) 
INFO[0076] +job release_interface(01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c) 
DEBU[0076] /sbin/iptables, [--wait -t nat -D DOCKER -p tcp -d 0/0 --dport 49153 ! -i docker0 -j DNAT --to-destination 172.17.0.2:22] 
DEBU[0076] /sbin/iptables, [--wait -D FORWARD ! -i docker0 -o docker0 -p tcp -d 172.17.0.2 --dport 22 -j ACCEPT] 
INFO[0076] -job release_interface(01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c) = OK (0) 
INFO[0076] +job log(stop, 01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c, evarga/jenkins-slave:latest) 
INFO[0076] -job log(stop, 01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c, evarga/jenkins-slave:latest) = OK (0) 
INFO[0076] -job stop(01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c) = OK (0) 
DEBU[0076] Calling DELETE /containers/{name:.*}         
INFO[0076] DELETE /containers/01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c 
INFO[0076] +job rm(01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c) 
INFO[0076] +job log(destroy, 01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c, evarga/jenkins-slave:latest) 
INFO[0076] -job log(destroy, 01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c, evarga/jenkins-slave:latest) = OK (0) 
INFO[0076] -job rm(01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c) = OK (0) 
```

## Jenkins Log
```
Feb 19, 2015 4:46:13 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
Excess workload after pending Spot instances: 1
Feb 19, 2015 4:46:13 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud countCurrentDockerSlaves
Images found: [Image{repository=null, tag=null, id=8880612971b0e41ecc5de6943c9680bb8dc08027dbae4d3a275ac827293cbf2e, created=1419452556, size=0, virtualSize=610837405}]
Feb 19, 2015 4:46:13 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
Provisioning for AMI evarga/jenkins-slave; Estimated number of total slaves: 0; Estimated number of slaves for ami evarga/jenkins-slave: 0
Feb 19, 2015 4:46:13 PM WARNING com.nirima.jenkins.plugins.docker.DockerTemplateBase getLxcConf
Specified option:  is not in the form X=Y, please correct.
Feb 19, 2015 4:46:13 PM INFO com.nirima.jenkins.plugins.docker.DockerComputerLauncher getSSHLauncher
Creating slave SSH launcher for tools-jenkins-docker-slave-uswest2-i-26edda2a.cloud.nextdoor.com:49153
Feb 19, 2015 4:46:23 PM INFO com.nirima.jenkins.plugins.docker.utils.RetryingComputerLauncher launch
Launch failed, pausing before retry.
Feb 19, 2015 4:46:23 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
```

## Jenkins Docker Plugin Config Settings:
```xml
    <com.nirima.jenkins.plugins.docker.DockerCloud plugin="docker-plugin@0.8">
      <name>docker</name>
      <templates>
        <com.nirima.jenkins.plugins.docker.DockerTemplate>
          <image>evarga/jenkins-slave</image>
          <dockerCommand></dockerCommand>
          <lxcConfString></lxcConfString>
          <hostname></hostname>
          <dnsHosts/>
          <volumes/>
          <volumesFrom></volumesFrom>
          <bindPorts></bindPorts>
          <bindAllPorts>false</bindAllPorts>
          <privileged>false</privileged>
          <labelString>container</labelString>
          <credentialsId>11195549-224a-4b2f-b983-0f7d8233637d</credentialsId>
          <idleTerminationMinutes>5</idleTerminationMinutes>
          <jvmOptions></jvmOptions>
          <javaPath></javaPath>
          <prefixStartSlaveCmd></prefixStartSlaveCmd>
          <suffixStartSlaveCmd></suffixStartSlaveCmd>
          <remoteFsMapping></remoteFsMapping>
          <remoteFs>/home/jenkins</remoteFs>
          <instanceCap>2147483647</instanceCap>
        </com.nirima.jenkins.plugins.docker.DockerTemplate>
      </templates>
      <serverUrl>http://tools-jenkins-docker-slave-uswest2-i-26edda2a:4243</serverUrl>
      <containerCap>1</containerCap>
      <connectTimeout>5</connectTimeout>
      <readTimeout>15</readTimeout>
    </com.nirima.jenkins.plugins.docker.DockerCloud>
  </clouds>
```

## Jenkins Slave Boot Log
```
[02/19/15 16:46:28] [SSH] Opening SSH connection to tools-jenkins-docker-slave-uswest2-i-26edda2a:49153.
Connection refused
SSH Connection failed with IOException: "Connection refused".
java.io.IOException: There was a problem while connecting to tools-jenkins-docker-slave-uswest2-i-26edda2a:49153
	at com.trilead.ssh2.Connection.connect(Connection.java:818)
	at com.trilead.ssh2.Connection.connect(Connection.java:687)
	at com.trilead.ssh2.Connection.connect(Connection.java:587)
	at hudson.plugins.sshslaves.SSHLauncher.openConnection(SSHLauncher.java:1146)
	at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:701)
	at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:696)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at com.trilead.ssh2.transport.TransportManager.establishConnection(TransportManager.java:354)
	at com.trilead.ssh2.transport.TransportManager.initialize(TransportManager.java:467)
	at com.trilead.ssh2.Connection.connect(Connection.java:758)
	... 9 more
[02/19/15 16:46:28] Launch failed - cleaning up connection
[02/19/15 16:46:28] [SSH] Connection closed.
```

**Comment by diranged** [comment]
I just want to follow up here.. the issue is not that the container is unreachable, but that the container simply fails to launch. It starts up, and immediately is shut down. From the docker logs, it SEEMS like Docker is receiving a `stop` command from the Docker Plugin, but its very hard to tell:

```
DEBU[0076] Calling GET /containers/{name:.*}/json       
INFO[0076] GET /containers/01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c/json 
INFO[0076] +job container_inspect(01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c) 
INFO[0076] -job container_inspect(01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c) = OK (0) 
DEBU[0076] Calling POST /containers/{name:.*}/stop      
INFO[0076] POST /containers/01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c/stop 
INFO[0076] +job stop(01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c) 
DEBU[0076] Sending 15 to 01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c 
INFO[0076] Container 01bc38c315ee6d23ba705740648f694829d96ce10197422a51ae3436a0fb934c failed to exit within 0 seconds of SIGTERM - using the force 
```

**Comment by diranged** [comment]
Anyone able to reproduce this problem?

**Comment by thomassuckow** [comment]
I am not seeing this issue, but I am also using the bleeding edge docker-plugin. I think we will have to see if your issue persists in 0.9 and then go from there, because a lot has changed.

**Comment by diranged** [comment]
Can someone post instructions on how to build the plugin from scratch -- at least then I could try the latest master.

**Comment by KostyaSha** [comment]
try new beta1 release

**Comment by diranged** [comment]
So I built up the latest master and it doesn't seem to work.. but the behavior is idfferent. Now it doesn't seem to be able to launch the container at all.

```
Mar 20, 2015 4:43:11 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
INFO: Asked to provision 1 slave(s) for: default
Mar 20, 2015 4:43:11 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
INFO: Will provision "evarga/jenkins-slave" for: default
Mar 20, 2015 4:43:11 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
SEVERE: Exception while provisioning for: default
java.lang.NullPointerException
	at java.util.Arrays$ArrayList.<init>(Arrays.java:2842)
	at java.util.Arrays.asList(Arrays.java:2828)
	at com.nirima.jenkins.plugins.docker.DockerCloud$2.apply(DockerCloud.java:347)
	at com.nirima.jenkins.plugins.docker.DockerCloud$2.apply(DockerCloud.java:344)
	at com.google.common.collect.Iterators.indexOf(Iterators.java:778)
	at com.google.common.collect.Iterators.any(Iterators.java:684)
	at com.google.common.collect.Iterables.any(Iterables.java:623)
	at com.nirima.jenkins.plugins.docker.DockerCloud.countCurrentDockerSlaves(DockerCloud.java:344)
	at com.nirima.jenkins.plugins.docker.DockerCloud.addProvisionedSlave(DockerCloud.java:381)
	at com.nirima.jenkins.plugins.docker.DockerCloud.provision(DockerCloud.java:232)
	at hudson.slaves.NodeProvisioner$StandardStrategyImpl.apply(NodeProvisioner.java:582)
	at hudson.slaves.NodeProvisioner.update(NodeProvisioner.java:245)
	at hudson.slaves.NodeProvisioner.access$000(NodeProvisioner.java:55)
	at hudson.slaves.NodeProvisioner$NodeProvisionerInvoker.doRun(NodeProvisioner.java:679)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

Here is our config... tell me if somethign is wrong here:
```xml
  <clouds>
    <com.nirima.jenkins.plugins.docker.DockerCloud plugin="docker-plugin@0.9.0-SNAPSHOT">
      <name>default</name>
      <templates>
        <com.nirima.jenkins.plugins.docker.DockerTemplate>
          <image>evarga/jenkins-slave</image>
          <dockerCommand></dockerCommand>
          <lxcConfString></lxcConfString>
          <hostname></hostname>
          <dnsHosts/>
          <volumes/>
          <volumesFrom></volumesFrom>
          <environment/>
          <bindPorts></bindPorts>
          <bindAllPorts>false</bindAllPorts>
          <privileged>false</privileged>
          <tty>false</tty>
          <labelString>default</labelString>
          <credentialsId>82222fa2-83d9-4536-a3df-ce5307e840d6</credentialsId>
          <idleTerminationMinutes>5</idleTerminationMinutes>
          <sshLaunchTimeoutMinutes>1</sshLaunchTimeoutMinutes>
          <jvmOptions></jvmOptions>
          <javaPath></javaPath>
          <prefixStartSlaveCmd></prefixStartSlaveCmd>
          <suffixStartSlaveCmd></suffixStartSlaveCmd>
          <remoteFsMapping></remoteFsMapping>
          <remoteFs>/home/jenkins</remoteFs>
          <instanceCap>10</instanceCap>
        </com.nirima.jenkins.plugins.docker.DockerTemplate>
      </templates>
      <serverUrl>http://172.17.42.1:4243/</serverUrl>
      <containerCap>2147483647</containerCap>
      <connectTimeout>5</connectTimeout>
      <readTimeout>15</readTimeout>
      <version>1.5.0</version>
      <credentialsId></credentialsId>
    </com.nirima.jenkins.plugins.docker.DockerCloud>
  </clouds>
```

**Comment by mkamlesh** [comment]
Sorry for rather late reply but it's not an issue for me anymore. I guess, I had some configuration issues on the docker host itself. The moment, I stood up another docker host, things started working fine. One thing that was different was that in an earlier setup my Jenkins master and docker host were continents apart. This time, they both are in the same data center and that too seems to be helping.

**Comment by diranged** [comment]
@mkamlesh  I wish you hadn't closed this -- its still an ongoing issue for me (as evident by my most recent post).
