### ISSUE TITLE
a load of failed integration tests while trying to build current master docker-plugin-0.8-46-gc785fbc

### ISSUE THREAD

**Issue by yarikoptic** [jenkinsci/docker-plugin#170]
```
...
com/nirima/jenkins/plugins/docker/DockerSlave/config.jelly(org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyCheck)  Time elapsed: 0.013 sec  <<< FAILURE!
java.lang.AssertionError: <?jelly escape-by-default='true'?> is missing
        at org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyCheck.runTest(JellyTestSuiteBuilder.java:98)

com/nirima/jenkins/plugins/docker/DockerSlave/configure-entries.jelly(org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyCheck)  Time elapsed: 0.002 sec  <<< FAILURE!
java.lang.AssertionError: <?jelly escape-by-default='true'?> is missing
        at org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyCheck.runTest(JellyTestSuiteBuilder.java:98)

index.jelly(org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyCheck)  Time elapsed: 0.002 sec  <<< FAILURE!
java.lang.AssertionError: <?jelly escape-by-default='true'?> is missing
        at org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyCheck.runTest(JellyTestSuiteBuilder.java:98)


Results :

Failed tests:
  JellyTestSuiteBuilder$JellyCheck.runTest:98 <?jelly escape-by-default='true'?> is missing
  JellyTestSuiteBuilder$JellyCheck.runTest:98 <?jelly escape-by-default='true'?> is missing
  JellyTestSuiteBuilder$JellyCheck.runTest:98 <?jelly escape-by-default='true'?> is missing
  JellyTestSuiteBuilder$JellyCheck.runTest:98 <?jelly escape-by-default='true'?> is missing
  JellyTestSuiteBuilder$JellyCheck.runTest:98 <?jelly escape-by-default='true'?> is missing
  JellyTestSuiteBuilder$JellyCheck.runTest:98 <?jelly escape-by-default='true'?> is missing
  JellyTestSuiteBuilder$JellyCheck.runTest:98 <?jelly escape-by-default='true'?> is missing
...
```

Here are all the reports http://www.onerussian.com/tmp/docker-plugin-surefire-reports.tgz

**Comment by menski** [comment]
Have a look at this commit https://github.com/jenkinsci/docker-plugin/commit/e7fc25cf5bf1cf9c4f1749724ed98111ed6c9215. It fixes the errors but isn't yet on master.

**Comment by yarikoptic** [comment]
thanks @menski. I will try then that shade-dependencies branch

**Comment by yarikoptic** [comment]
so built this one with maven 3 as demanded for which switched from maven 2 (update-alternatives on debian). installed the beast and now got  possibly unrelated (FWIW I didn't try to enable https/openssl at any step I was building before docker-java)
```
FATAL: org/bouncycastle/openssl/PEMParser
java.lang.NoClassDefFoundError: org/bouncycastle/openssl/PEMParser
	at com.github.dockerjava.core.LocalDirectorySSLConfig.getSSLContext(LocalDirectorySSLConfig.java:35)
	at com.github.dockerjava.jaxrs.DockerCmdExecFactoryImpl.init(DockerCmdExecFactoryImpl.java:72)
	at com.github.dockerjava.core.DockerClientImpl.withDockerCmdExecFactory(DockerClientImpl.java:64)
	at com.github.dockerjava.core.DockerClientBuilder.build(DockerClientBuilder.java:65)
	at com.nirima.jenkins.plugins.docker.DockerCloud.buildConnection(DockerCloud.java:200)
	at com.nirima.jenkins.plugins.docker.DockerCloud.connect(DockerCloud.java:140)
	at com.nirima.jenkins.plugins.docker.DockerTemplate.provisionNew(DockerTemplate.java:269)
	at com.nirima.jenkins.plugins.docker.builder.DockerBuilderControlOptionProvisionAndStart.execute(DockerBuilderControlOptionProvisionAndStart.java:32)
	at com.nirima.jenkins.plugins.docker.builder.DockerBuilderControl.perform(DockerBuilderControl.java:59)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
	at hudson.model.Build$BuildExecution.build(Build.java:199)
	at hudson.model.Build$BuildExecution.doRun(Build.java:160)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:533)
	at hudson.model.Run.execute(Run.java:1745)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.openssl.PEMParser
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1375)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1325)
	at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1078)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 18 more
```

**Comment by KostyaSha** [comment]
fix for jelly escape was committed to master
