### ISSUE TITLE
Docker Image discovery broken in 0.9-MASTER after Jan24th...

### ISSUE THREAD

**Issue by diranged** [jenkinsci/docker-plugin#186]
I'm not sure why I'm the only person seeing this. I reported this issue in #161 (https://github.com/jenkinsci/docker-plugin/issues/161#issuecomment-84065455). Our host is running Docker 1.5.0, Ubuntu 14.04 and is actually running Jenkins inside of a docker container:

```shell
[root@xxx:~]# docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS                                                    NAMES
df032b4af314        jenkins:1.594       "/usr/local/bin/jenk   15 minutes ago      Up 15 minutes       127.0.0.1:8080->8080/tcp, 172.17.42.1:50000->50000/tcp   thirsty_stallman    
[root@xxx:~]# docker --version
Docker version 1.5.0, build a8a31ef
[root@xxx:~]# 
```

When the Docker plugin runs through the [instance counting code](https://github.com/jenkinsci/docker-plugin/blob/dcd1683abc5d793f15a24729098c31a3be16793e/docker-plugin/src/main/java/com/nirima/jenkins/plugins/docker/DockerCloud.java#L328-L375), it fails immediately. It seems to get a list of the images that are on the host and fail on the `getRepoTags()` call on line *350*.

Commit a42b48e9f09be862d94d80c91e482df3f0932152 seems to be the one that implemented this new method  call... and I don't understand it enough to know why it breaks. Here is the most detailed log I can get from Jenkins as its executing this:

```
Mar 26, 2015 4:10:55 PM FINE com.github.dockerjava.core.util.LoggingFilter log
198 * Client response received on thread jenkins.util.Timer [#9]
198 < 200
198 < Content-Length: 507
198 < Content-Type: application/json
198 < Date: Thu, 26 Mar 2015 16:10:55 GMT
[{"Created":1420497017,"Id":"5368c4eb049a759b17fc1dd4ef7f549e7659bdcebe7ba1792a0ff1497c1ffd6c","Repository":"jenkins","Size":521,"Tag":"weekly","VirtualSize":661712613}
,{"Created":1420496983,"Id":"d10085a084673a02035db2ab7cc2c93331ec77a06dcf4fb9f948f61c41866470","Repository":"jenkins","Size":521,"Tag":"1.594","VirtualSize":661717519}
,{"Created":1420496983,"Id":"d10085a084673a02035db2ab7cc2c93331ec77a06dcf4fb9f948f61c41866470","Repository":"jenkins","Size":521,"Tag":"latest","VirtualSize":661717519}
]

Mar 26, 2015 4:10:55 PM FINE shaded.org.apache.http.impl.conn.PoolingHttpClientConnectionManager releaseConnection
Connection [id: 0][route: {}->http://172.17.42.1:4243] can be kept alive indefinitely
Mar 26, 2015 4:10:55 PM FINE shaded.org.apache.http.impl.conn.PoolingHttpClientConnectionManager releaseConnection
Connection released: [id: 0][route: {}->http://172.17.42.1:4243][total kept alive: 1; route allocated: 1 of 2; total allocated: 1 of 20]
Mar 26, 2015 4:10:55 PM FINEST org.glassfish.jersey.process.internal.RequestScope
[DEBUG] Released scope instance Instance{id=809fce8c-ad28-4d1b-816b-e7b0f22fbba1, referenceCounter=0, store size=0} on thread jenkins.util.Timer [#9]
Mar 26, 2015 4:10:55 PM FINEST com.github.dockerjava.jaxrs.ListImagesCmdExec execute
Response: [com.github.dockerjava.api.model.Image@51c8cf41[created=1420497017,id=5368c4eb049a759b17fc1dd4ef7f549e7659bdcebe7ba1792a0ff1497c1ffd6c,parentId=<null>,repoTags=<null>,size=521,virtualSize=661712613], com.github.dockerjava.api.model.Image@569ede59[created=1420496983,id=d10085a084673a02035db2ab7cc2c93331ec77a06dcf4fb9f948f61c41866470,parentId=<null>,repoTags=<null>,size=521,virtualSize=661717519], com.github.dockerjava.api.model.Image@5817d17c[created=1420496983,id=d10085a084673a02035db2ab7cc2c93331ec77a06dcf4fb9f948f61c41866470,parentId=<null>,repoTags=<null>,size=521,virtualSize=661717519]]
Mar 26, 2015 4:10:55 PM SEVERE com.nirima.jenkins.plugins.docker.DockerCloud provision
Exception while provisioning for: default
java.lang.NullPointerException
	at java.util.Arrays$ArrayList.<init>(Arrays.java:2842)
	at java.util.Arrays.asList(Arrays.java:2828)
	at com.nirima.jenkins.plugins.docker.DockerCloud$2.apply(DockerCloud.java:350)
	at com.nirima.jenkins.plugins.docker.DockerCloud$2.apply(DockerCloud.java:347)
	at com.google.common.collect.Iterators.indexOf(Iterators.java:778)
	at com.google.common.collect.Iterators.any(Iterators.java:684)
	at com.google.common.collect.Iterables.any(Iterables.java:623)
	at com.nirima.jenkins.plugins.docker.DockerCloud.countCurrentDockerSlaves(DockerCloud.java:347)
	at com.nirima.jenkins.plugins.docker.DockerCloud.addProvisionedSlave(DockerCloud.java:384)
	at com.nirima.jenkins.plugins.docker.DockerCloud.provision(DockerCloud.java:235)
	at hudson.slaves.NodeProvisioner$StandardStrategyImpl.apply(NodeProvisioner.java:582)
	at hudson.slaves.NodeProvisioner.update(NodeProvisioner.java:245)
	at hudson.slaves.NodeProvisioner.access$000(NodeProvisioner.java:55)
	at hudson.slaves.NodeProvisioner$NodeProvisionerInvoker.doRun(NodeProvisioner.java:679)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by pedjak** [comment]
I can confirm that I am seeing the same issue - it seems that docker 1.5 is affected.

**Comment by KostyaSha** [comment]
Please try #210

**Comment by diranged** [comment]
Trying 0.9.0-rc1, still fails .. albeit differently:

```
May 04, 2015 10:50:34 PM FINEST com.github.dockerjava.jaxrs.ListContainersCmdExec execute
Response: [com.github.dockerjava.api.model.Container@5a1139ef[command=/usr/local/bin/jenkins.sh,created=1429039010,id=f72b49ad1e4f91aeb0107dc20919d7af519c73262011a948069af1f09595f991,image=jenkins:1.596.2,names={/serene_torvalds},ports={com.github.dockerjava.api.model.Container$Port@396dd94b[ip=172.17.42.1,privatePort=50000,publicPort=50000,type=tcp],com.github.dockerjava.api.model.Container$Port@5ad4e861[ip=127.0.0.1,privatePort=8080,publicPort=8080,type=tcp]},status=Up 3 days]]
May 04, 2015 10:50:34 PM FINE com.github.dockerjava.core.command.AbstrDockerCmd exec
Cmd: images 
May 04, 2015 10:50:34 PM FINEST com.github.dockerjava.jaxrs.ListImagesCmdExec execute
GET: JerseyWebTarget { http://172.17.42.1:4243/v1.5.0/images/json?all=0 }
May 04, 2015 10:50:34 PM FINE com.github.dockerjava.core.util.LoggingFilter log
11 * Sending client request on thread jenkins.util.Timer [#1]
11 > GET http://172.17.42.1:4243/v1.5.0/images/json?all=0
11 > Accept: application/json

May 04, 2015 10:50:34 PM FINE com.github.dockerjava.core.util.LoggingFilter log
12 * Client response received on thread jenkins.util.Timer [#1]
12 < 200
12 < Content-Length: 857
12 < Content-Type: application/json
12 < Date: Mon, 04 May 2015 22:50:34 GMT
[{"Created":1428438688,"Id":"8dab76f5fd7b46ccc330b6aafc74af3ab1df3904cd511155ccf2d3f35e7e094f","Repository":"jenkins","Size":602,"Tag":"1.596.2","VirtualSize":662048617}
,{"Created":1428438688,"Id":"8dab76f5fd7b46ccc330b6aafc74af3ab1df3904cd511155ccf2d3f35e7e094f","Repository":"jenkins","Size":602,"Tag":"latest","VirtualSize":662048617}
,{"Created":1420497017,"Id":"5368c4eb049a759b17fc1dd4ef7f549e7659bdcebe7ba1792a0ff1497c1ffd6c","Repository":"jenkins","Size":521,"Tag":"weekly","VirtualSize":661712613}
,{"Created":1420496983,"Id":"d10085a084673a02035db2ab7cc2c93331ec77a06dcf4fb9f948f61c41866470","Repository":"jenkins","Size":521,"Tag":"1.594","VirtualSize":661717519}
,{"Created":1419452556,"Id":"8880612971b0e41ecc5de6943c9680bb8dc08027dbae4d3a275ac827293cbf2e","Repository":"evarga/jenkins-slave","Size":0,"Tag":"latest","VirtualSize":610837405}
]

May 04, 2015 10:50:34 PM FINEST com.github.dockerjava.jaxrs.ListImagesCmdExec execute
Response: [com.github.dockerjava.api.model.Image@1c1d6025[created=1428438688,id=8dab76f5fd7b46ccc330b6aafc74af3ab1df3904cd511155ccf2d3f35e7e094f,parentId=<null>,repoTags=<null>,size=602,virtualSize=662048617], com.github.dockerjava.api.model.Image@4c932b8e[created=1428438688,id=8dab76f5fd7b46ccc330b6aafc74af3ab1df3904cd511155ccf2d3f35e7e094f,parentId=<null>,repoTags=<null>,size=602,virtualSize=662048617], com.github.dockerjava.api.model.Image@52109ee8[created=1420497017,id=5368c4eb049a759b17fc1dd4ef7f549e7659bdcebe7ba1792a0ff1497c1ffd6c,parentId=<null>,repoTags=<null>,size=521,virtualSize=661712613], com.github.dockerjava.api.model.Image@4130bb6f[created=1420496983,id=d10085a084673a02035db2ab7cc2c93331ec77a06dcf4fb9f948f61c41866470,parentId=<null>,repoTags=<null>,size=521,virtualSize=661717519], com.github.dockerjava.api.model.Image@666195d8[created=1419452556,id=8880612971b0e41ecc5de6943c9680bb8dc08027dbae4d3a275ac827293cbf2e,parentId=<null>,repoTags=<null>,size=0,virtualSize=610837405]]
May 04, 2015 10:50:34 PM WARNING com.nirima.jenkins.plugins.docker.DockerCloud provision
Bad template evarga/jenkins-slave: null. Trying next template...
```

**Comment by diranged** [comment]
I've tried a few different formats for the image, including the exact image ID as returned by `docker images`

**Comment by KostyaSha** [comment]
Is it actual?

**Comment by KostyaSha** [comment]
no replies.
