### ISSUE TITLE
Errors when running Jenkins slave containers using docker-plugin

### ISSUE THREAD

**Issue by brandocorp** [jenkinsci/docker-plugin#215]
I'm attempting to use the docker-plugin to provision jenkins slaves using docker containers. 

Slave Image: `evarga/jenkins-slave`
Jenkins Master: `1.612`
Docker: `1.6.0, build 4749651`

I was originally able to get a the plugin to create a container, but I had missed the step of adding the jenkins user credentials. After adding them, I was no longer able to create a container.

From the system logs:

```
May 05, 2015 4:47:49 PM INFO hudson.WebAppMain$3 run
Jenkins is fully up and running
May 05, 2015 4:49:27 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
Asked to provision 1 slave(s) for: null
May 05, 2015 4:49:27 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
Will provision "evarga/jenkins-slave" for: null
May 05, 2015 4:49:29 PM WARNING com.nirima.jenkins.plugins.docker.DockerCloud provision
Bad template evarga/jenkins-slave: null. Trying next template...
``` 

I did a search and found something about missing tags causing issues, so I added one to the template and one to the job I'm testing with.

```
May 05, 2015 4:56:57 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
Asked to provision 1 slave(s) for: docker
May 05, 2015 4:56:57 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
Will provision "evarga/jenkins-slave" for: docker
May 05, 2015 4:56:57 PM WARNING com.nirima.jenkins.plugins.docker.DockerCloud provision
Bad template evarga/jenkins-slave: null. Trying next template...
```

No luck. I remembered that the container launched when the image was missing so I removed the image from docker (`docker rmi evarga/jenkins-slave`) and tried again. This time I was again able to provision a slave container.

```
May 05, 2015 5:03:57 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
Asked to provision 1 slave(s) for: docker
May 05, 2015 5:03:57 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
Will provision "evarga/jenkins-slave" for: docker
May 05, 2015 5:03:57 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud countCurrentDockerSlaves
Pulling image "evarga/jenkins-slave" since one was not found.  This may take awhile...
May 05, 2015 5:04:57 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud countCurrentDockerSlaves
Finished pulling image "evarga/jenkins-slave"
May 05, 2015 5:04:57 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
Provisioning "evarga/jenkins-slave" number 0 on "Local Host"; Total containers: 0
May 05, 2015 5:04:57 PM INFO hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
Started provisioning Image of evarga/jenkins-slave from Local Host with 1 executors. Remaining excess workload: 0
May 05, 2015 5:04:58 PM INFO com.nirima.jenkins.plugins.docker.DockerComputerLauncher getSSHLauncher
Creating slave SSH launcher for 127.0.0.1:32769
May 05, 2015 5:05:07 PM INFO hudson.slaves.NodeProvisioner$2 run
Image of evarga/jenkins-slave provisioning successfully completed. We have now 2 computer(s)
```

The job I had scheduled was executed on the slave container, but appears to have caused an error upon completing.

```
May 05, 2015 5:07:06 PM INFO hudson.model.Run execute
long-running-build-1 #15 main build action completed: SUCCESS
May 05, 2015 5:07:06 PM WARNING hudson.model.Executor finish2
Executor #0 for 1c3a164e59a9@Local Host : executing long-running-build-1 #15 termination trace
hudson.model.Computer$TerminationRequest: Termination requested at Tue May 05 17:07:06 EDT 2015 by Thread[Executor #0 for 1c3a164e59a9@Local Host : executing long-running-build-1 #15,5,main] [id=124]
	at hudson.model.Computer.recordTermination(Computer.java:214)
	at hudson.slaves.AbstractCloudSlave.terminate(AbstractCloudSlave.java:63)
	at com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy.done(DockerOnceRetentionStrategy.java:76)
	at com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy.taskCompleted(DockerOnceRetentionStrategy.java:58)
	at hudson.slaves.SlaveComputer.taskCompleted(SlaveComputer.java:301)
	at com.nirima.jenkins.plugins.docker.DockerComputer.taskCompleted(DockerComputer.java:63)
	at hudson.model.queue.WorkUnitContext.synchronizeEnd(WorkUnitContext.java:145)
	at hudson.model.Executor.finish1(Executor.java:424)
	at hudson.model.Executor.run(Executor.java:394)

May 05, 2015 5:07:06 PM WARNING hudson.model.Executor finish2
Executor #0 for 1c3a164e59a9@Local Host : executing long-running-build-1 #15 termination trace
hudson.model.Computer$TerminationRequest: Termination requested at Tue May 05 17:07:06 EDT 2015 by Thread[Executor #0 for 1c3a164e59a9@Local Host : executing long-running-build-1 #15,5,main] [id=124]
	at hudson.model.Computer.recordTermination(Computer.java:214)
	at hudson.model.Computer.disconnect(Computer.java:466)
	at hudson.slaves.SlaveComputer.disconnect(SlaveComputer.java:601)
	at com.nirima.jenkins.plugins.docker.DockerSlave._terminate(DockerSlave.java:101)
	at hudson.slaves.AbstractCloudSlave.terminate(AbstractCloudSlave.java:67)
	at com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy.done(DockerOnceRetentionStrategy.java:76)
	at com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy.taskCompleted(DockerOnceRetentionStrategy.java:58)
	at hudson.slaves.SlaveComputer.taskCompleted(SlaveComputer.java:301)
	at com.nirima.jenkins.plugins.docker.DockerComputer.taskCompleted(DockerComputer.java:63)
	at hudson.model.queue.WorkUnitContext.synchronizeEnd(WorkUnitContext.java:145)
	at hudson.model.Executor.finish1(Executor.java:424)
	at hudson.model.Executor.run(Executor.java:394)

May 05, 2015 5:07:06 PM WARNING hudson.model.Executor finish2
Executor #0 for 1c3a164e59a9@Local Host : executing long-running-build-1 #15 termination trace
hudson.model.Computer$TerminationRequest: Termination requested at Tue May 05 17:07:06 EDT 2015 by Thread[Executor #0 for 1c3a164e59a9@Local Host : executing long-running-build-1 #15,5,main] [id=124]
	at hudson.model.Computer.recordTermination(Computer.java:214)
	at jenkins.model.Nodes$3.run(Nodes.java:165)
	at hudson.model.Queue._withLock(Queue.java:1212)
	at hudson.model.Queue.withLock(Queue.java:1148)
	at jenkins.model.Nodes.removeNode(Nodes.java:160)
	at jenkins.model.Jenkins.removeNode(Jenkins.java:1705)
	at hudson.slaves.AbstractCloudSlave.terminate(AbstractCloudSlave.java:70)
	at com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy.done(DockerOnceRetentionStrategy.java:76)
	at com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy.taskCompleted(DockerOnceRetentionStrategy.java:58)
	at hudson.slaves.SlaveComputer.taskCompleted(SlaveComputer.java:301)
	at com.nirima.jenkins.plugins.docker.DockerComputer.taskCompleted(DockerComputer.java:63)
	at hudson.model.queue.WorkUnitContext.synchronizeEnd(WorkUnitContext.java:145)
	at hudson.model.Executor.finish1(Executor.java:424)
	at hudson.model.Executor.run(Executor.java:394)

May 05, 2015 5:07:06 PM WARNING hudson.model.Executor finish2
Executor #0 for 1c3a164e59a9@Local Host : executing long-running-build-1 #15 termination trace
hudson.model.Computer$TerminationRequest: Termination requested at Tue May 05 17:07:06 EDT 2015 by Thread[Executor #0 for 1c3a164e59a9@Local Host : executing long-running-build-1 #15,5,main] [id=124]
	at hudson.model.Computer.recordTermination(Computer.java:214)
	at hudson.model.Computer.disconnect(Computer.java:466)
	at hudson.slaves.SlaveComputer.disconnect(SlaveComputer.java:601)
	at jenkins.model.Nodes$3.run(Nodes.java:166)
	at hudson.model.Queue._withLock(Queue.java:1212)
	at hudson.model.Queue.withLock(Queue.java:1148)
	at jenkins.model.Nodes.removeNode(Nodes.java:160)
	at jenkins.model.Jenkins.removeNode(Jenkins.java:1705)
	at hudson.slaves.AbstractCloudSlave.terminate(AbstractCloudSlave.java:70)
	at com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy.done(DockerOnceRetentionStrategy.java:76)
	at com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy.taskCompleted(DockerOnceRetentionStrategy.java:58)
	at hudson.slaves.SlaveComputer.taskCompleted(SlaveComputer.java:301)
	at com.nirima.jenkins.plugins.docker.DockerComputer.taskCompleted(DockerComputer.java:63)
	at hudson.model.queue.WorkUnitContext.synchronizeEnd(WorkUnitContext.java:145)
	at hudson.model.Executor.finish1(Executor.java:424)
	at hudson.model.Executor.run(Executor.java:394)

```

After that, I was seeing failures in the logs

```
May 05, 2015 5:07:07 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
Asked to provision 1 slave(s) for: docker
May 05, 2015 5:07:07 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
Will provision "evarga/jenkins-slave" for: docker
May 05, 2015 5:07:07 PM WARNING com.nirima.jenkins.plugins.docker.DockerCloud provision
Bad template evarga/jenkins-slave: null. Trying next template...
May 05, 2015 5:07:17 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
```

Is there something relatively easy I've missed in my configuration?

**Comment by KostyaSha** [comment]
please provide Cloud configuration block from config.xml

**Comment by brandocorp** [comment]
Here's what's in the <cloud></cloud> section:

```xml
  <clouds>
    <com.nirima.jenkins.plugins.docker.DockerCloud plugin="docker-plugin@0.9.0-rc1">
      <name>Local Host</name>
      <templates>
        <com.nirima.jenkins.plugins.docker.DockerTemplate>
          <image>evarga/jenkins-slave</image>
          <dockerCommand></dockerCommand>
          <lxcConfString></lxcConfString>
          <hostname></hostname>
          <dnsHosts/>
          <volumes/>
          <volumesFrom></volumesFrom>
          <environment/>
          <bindPorts></bindPorts>
          <bindAllPorts>false</bindAllPorts>
          <privileged>false</privileged>
          <tty>false</tty>
          <labelString></labelString>
          <credentialsId>691331cc-b095-432c-9a2b-a758c54df820</credentialsId>
          <idleTerminationMinutes>5</idleTerminationMinutes>
          <sshLaunchTimeoutMinutes>1</sshLaunchTimeoutMinutes>
          <jvmOptions></jvmOptions>
          <javaPath></javaPath>
          <prefixStartSlaveCmd></prefixStartSlaveCmd>
          <suffixStartSlaveCmd></suffixStartSlaveCmd>
          <remoteFsMapping></remoteFsMapping>
          <remoteFs>/home/jenkins</remoteFs>
          <instanceCap>2147483647</instanceCap>
          <mode>NORMAL</mode>
          <retentionStrategy class="com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy">
            <idleMinutes>0</idleMinutes>
            <idleMinutes defined-in="com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy">0</idleMinutes>
          </retentionStrategy>
          <numExecutors>1</numExecutors>
        </com.nirima.jenkins.plugins.docker.DockerTemplate>
      </templates>
      <serverUrl>http://127.0.0.1:2375</serverUrl>
      <containerCap>2147483647</containerCap>
      <connectTimeout>5</connectTimeout>
      <readTimeout>15</readTimeout>
      <version>1.6.0</version>
      <credentialsId></credentialsId>
    </com.nirima.jenkins.plugins.docker.DockerCloud>
  </clouds>
```

**Comment by ndobson** [comment]
I encountered this same issue this week and it drove me crazy for hours. Remove <version>1.6.0</version> from your cloud config, just leave it blank. It will work.
It's something to do with the plugin prepending v[version#]/ to docker api calls

**Comment by KostyaSha** [comment]
@brandocorp have you tried to remove "version" ?

**Comment by brandocorp** [comment]
@KostyaSha, yep this was my issue. Thank you @ndobson !

**Comment by jmiddleton** [comment]
Thanks @ndobson. I faced the same problem.

**Comment by alincalinciuc** [comment]
thanks @ndobson ...

**Comment by jovandeginste** [comment]
also thanks @ndobson

**Comment by svparijs** [comment]
Had the same issue, removing the version worked for me aswel.

**Comment by KostyaSha** [comment]
frankly speaking i not sure why we need allow user settings this version. It existed in api library and in docker-api, but i see no real cases for doing this and this only causes issues, maybe it makes sense remove it.

**Comment by joelacrisp** [comment]
I've just run into this issue and removing the version didn't work. I still get the error. Drilling into the code, the full stack trace is helpfully binned in the log statement which generates this message. I'm using plugin version 0.11.0 and docker 1.7.1, although it never seems to get as far as talking to docker according to tcpdump. Previously this configuration was working fine, it seems the upgrade from 0.10.0 to 0.11.0 broke something?

**Comment by joelacrisp** [comment]
Stack trace :
jenkins.util.Timer [#9][1] wherei
  [1] shaded.org.apache.http.util.Args.notNull (Args.java:48), pc = 30
  [2] shaded.org.apache.http.HttpHost.<init> (HttpHost.java:81), pc = 8
  [3] com.github.dockerjava.jaxrs.connector.ApacheConnector.getHost (ApacheConnector.java:525), pc = 31
  [4] com.github.dockerjava.jaxrs.connector.ApacheConnector.apply (ApacheConnector.java:443), pc = 72
  [5] org.glassfish.jersey.client.ClientRuntime.invoke (ClientRuntime.java:246), pc = 28
  [6] org.glassfish.jersey.client.JerseyInvocation$3.call (JerseyInvocation.java:705), pc = 15
  [7] org.glassfish.jersey.internal.Errors.process (Errors.java:315), pc = 36
  [8] org.glassfish.jersey.internal.Errors.process (Errors.java:297), pc = 2
  [9] org.glassfish.jersey.internal.Errors.process (Errors.java:228), pc = 2
  [10] org.glassfish.jersey.process.internal.RequestScope.runInScope (RequestScope.java:424), pc = 25
  [11] org.glassfish.jersey.client.JerseyInvocation.invoke (JerseyInvocation.java:701), pc = 40
  [12] org.glassfish.jersey.client.JerseyInvocation$Builder.method (JerseyInvocation.java:417), pc = 33
  [13] org.glassfish.jersey.client.JerseyInvocation$Builder.get (JerseyInvocation.java:313), pc = 4
  [14] com.github.dockerjava.jaxrs.ListContainersCmdExec.execute (ListContainersCmdExec.java:36), pc = 185
  [15] com.github.dockerjava.jaxrs.ListContainersCmdExec.execute (ListContainersCmdExec.java:15), pc = 5
  [16] com.github.dockerjava.jaxrs.AbstrDockerCmdExec.exec (AbstrDockerCmdExec.java:53), pc = 2
  [17] com.github.dockerjava.core.command.AbstrDockerCmd.exec (AbstrDockerCmd.java:29), pc = 16
  [18] com.nirima.jenkins.plugins.docker.DockerCloud.countCurrentDockerSlaves (DockerCloud.java:447), pc = 11
  [19] com.nirima.jenkins.plugins.docker.DockerCloud.addProvisionedSlave (DockerCloud.java:470), pc = 15
  [20] com.nirima.jenkins.plugins.docker.DockerCloud.provision (DockerCloud.java:203), pc = 106
  [21] hudson.slaves.NodeProvisioner$StandardStrategyImpl.apply (NodeProvisioner.java:683), pc = 384
  [22] hudson.slaves.NodeProvisioner.update (NodeProvisioner.java:284), pc = 133
  [23] hudson.slaves.NodeProvisioner.access$000 (NodeProvisioner.java:57), pc = 1
  [24] hudson.slaves.NodeProvisioner$NodeProvisionerInvoker.doRun (NodeProvisioner.java:780), pc = 44
  [25] hudson.triggers.SafeTimerTask.run (SafeTimerTask.java:51), pc = 8
  [26] java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:471), pc = 4
  [27] java.util.concurrent.FutureTask.runAndReset (FutureTask.java:304), pc = 47
  [28] java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301 (ScheduledThreadPoolExecutor.java:178), pc = 1
  [29] java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run (ScheduledThreadPoolExecutor.java:293), pc = 37
  [30] java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1,145), pc = 95
  [31] java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:615), pc = 5
  [32] java.lang.Thread.run (Thread.java:745), pc = 11
jenkins.util.Timer [#9][1]

**Comment by joelacrisp** [comment]
JerseryURIBuilder object has an Authority but null Host, if that helps. Possibly a change in the URI parser behavior and handling?

**Comment by joelacrisp** [comment]
jenkins.util.Timer [#9][4] locals
Method arguments:
clientRequest = instance of org.glassfish.jersey.client.ClientRequest(id=11323)
Local variables:
request = instance of shaded.org.apache.http.client.methods.RequestBuilder$InternalRequest(id=11322)
clientHeadersSnapshot = instance of jersey.repackaged.com.google.common.collect.RegularImmutableMap(id=11324)
context = instance of shaded.org.apache.http.client.protocol.HttpClientContext(id=11325)
jenkins.util.Timer [#9][4] dump clientRequest
 clientRequest = {
    clientConfig: instance of org.glassfish.jersey.client.ClientConfig(id=11326)
    propertiesDelegate: instance of org.glassfish.jersey.internal.MapPropertiesDelegate(id=11327)
    requestUri: instance of java.net.URI(id=11328)
    httpMethod: "GET"
    abortResponse: null
    workers: instance of org.glassfish.jersey.message.internal.MessageBodyFactory(id=11329)
    asynchronous: false
    entityWritten: false
    writerInterceptors: instance of java.util.Collections$UnmodifiableRandomAccessList(id=11330)
    readerInterceptors: instance of java.util.Collections$UnmodifiableRandomAccessList(id=11331)
    ignoreUserAgent: false
    LOGGER: instance of java.util.logging.Logger(id=11332)
    org.glassfish.jersey.message.internal.OutboundMessageContext.EMPTY_ANNOTATIONS: instance of java.lang.annotation.Annotation[0] (id=11333)
    org.glassfish.jersey.message.internal.OutboundMessageContext.headers: instance of org.glassfish.jersey.internal.util.collection.StringKeyIgnoreCaseMultivaluedMap(id=11334)
    org.glassfish.jersey.message.internal.OutboundMessageContext.committingOutputStream: instance of org.glassfish.jersey.message.internal.CommittingOutputStream(id=11335)
    org.glassfish.jersey.message.internal.OutboundMessageContext.entity: null
    org.glassfish.jersey.message.internal.OutboundMessageContext.entityType: null
    org.glassfish.jersey.message.internal.OutboundMessageContext.entityAnnotations: instance of java.lang.annotation.Annotation[0] (id=11333)
    org.glassfish.jersey.message.internal.OutboundMessageContext.entityStream: instance of org.glassfish.jersey.message.internal.CommittingOutputStream(id=11335)
}

**Comment by joelacrisp** [comment]
jenkins.util.Timer [#9][4] dump clientRequest.requestUri
 clientRequest.requestUri = {
    serialVersionUID: -6052424284110960213
    scheme: "http"
    fragment: null
    authority: "devops_scratch.internal.bitfusion.io:4243"
    userInfo: null
    host: null
    port: -1
    path: "/containers/json"
    query: "all=0&size=0"
    schemeSpecificPart: "//devops_scratch.internal.bitfusion.io:4243/containers/json?all=0&size=0"
    hash: 0
    decodedUserInfo: null
    decodedAuthority: null
    decodedPath: null
    decodedQuery: null
    decodedFragment: null
    decodedSchemeSpecificPart: null
    string: "http://devops_scratch.internal.bitfusion.io:4243/containers/json?all=0
    L_DIGIT: 287948901175001088
    H_DIGIT: 0
    L_UPALPHA: 0
    H_UPALPHA: 134217726
    L_LOWALPHA: 0
    H_LOWALPHA: 576460743713488896
    L_ALPHA: 0
    H_ALPHA: 576460743847706622
    L_ALPHANUM: 287948901175001088
    H_ALPHANUM: 576460743847706622
    L_HEX: 287948901175001088
    H_HEX: 541165879422
    L_MARK: 113808043409408
    H_MARK: 4611686020574871552
    L_UNRESERVED: 288062709218410496
    H_UNRESERVED: 5188146764422578174
    L_RESERVED: -6052670429821140992
    H_RESERVED: 671088641
    L_ESCAPED: 1
    H_ESCAPED: 0
    L_URIC: -5764607720602730495
    H_URIC: 5188146765093666815
    L_PCHAR: 2882162826460266497
    H_PCHAR: 5188146764422578175
    L_PATH: 3458764316252045313
    H_PATH: 5188146764422578175
    L_DASH: 35184372088832
    H_DASH: 0
    L_DOT: 70368744177664
    H_DOT: 0
    L_USERINFO: 3458623578763689985
    H_USERINFO: 5188146764422578174
    L_REG_NAME: 3458623578763689985
    H_REG_NAME: 5188146764422578175
    L_SERVER: 3458623578763689985
    H_SERVER: 5188146765093666815
    L_SERVER_PERCENT: 3458623716202643457
    H_SERVER_PERCENT: 5188146765093666815
    L_LEFT_BRACKET: 0
    H_LEFT_BRACKET: 134217728
    L_SCHEME: 288063250384289792
    H_SCHEME: 576460743847706622
    L_URIC_NO_SLASH: -5764748458091085823
    H_URIC_NO_SLASH: 5188146764422578175
    hexDigits: instance of char[16] (id=11341)
    $assertionsDisabled: true
}

**Comment by joelacrisp** [comment]
In my case this was caused by an '_' (underscore) character in the host name.

**Comment by KostyaSha** [comment]
@joelacrisp could you fill separate issue and especially try reproduce with plain code using docker-java library?

**Comment by joelacrisp** [comment]
Probably not needed, _ isn't legal in host names so it was my error, although AWS Route53 permits it.

**Comment by KostyaSha** [comment]
@joelacrisp so, is it docker limitation?

**Comment by joelacrisp** [comment]
No, host name specification and JVM library. At worst it's bad error reporting.
