### ISSUE TITLE
Hang while deleting docker containers, unable to create any more without restarting Jenkins

### ISSUE THREAD

**Issue by jdpaton** [jenkinsci/docker-plugin#24]
Seeing the following issue that gradually builds up over time. Containers get into a startup loop (for transient IO related startup issues it seems, where the agent fails to fully launch), but the prominent issue is they subsequently can't be deleted from Jenkins, the "delete node" option just hangs, and eventually no more containers are able to be created, requiring a Jenkins restart.

The following issue repeats in the slave log (container doesn't exist at this point):

```
[05/20/14 21:21:02] [SSH] Opening SSH connection to docker-ci-1.us.com:50368.
java.io.IOException: There was a problem while connecting to docker-ci-1.us.com:50368
    at com.trilead.ssh2.Connection.connect(Connection.java:818)
    at com.trilead.ssh2.Connection.connect(Connection.java:687)
    at com.trilead.ssh2.Connection.connect(Connection.java:587)
    at hudson.plugins.sshslaves.SSHLauncher.openConnection(SSHLauncher.java:1132)
    at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:648)
    at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:642)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.net.ConnectException: Connection refused
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:579)
    at com.trilead.ssh2.transport.TransportManager.establishConnection(TransportManager.java:346)
    at com.trilead.ssh2.transport.TransportManager.initialize(TransportManager.java:459)
    at com.trilead.ssh2.Connection.connect(Connection.java:758)
    ... 9 more
[05/20/14 21:21:02] [SSH] Connection closed.
[05/20/14 21:21:02] Launch failed - cleaning up connection
```

Log from the docker host shows the API returning 404, but the container persists in Jenkins:

```
[root@docker-ci-1 ~]# tail -f /var/log/docker
No such container: 05fd5f2e506af30fb8eb5ac4620cd395ace523f7802c623a6f7a38656c8eea73
[7b302e61] -job stop(05fd5f2e506af30fb8eb5ac4620cd395ace523f7802c623a6f7a38656c8eea73) = ERR (1)
[error] server.go:1011 Error: No such container: 05fd5f2e506af30fb8eb5ac4620cd395ace523f7802c623a6f7a38656c8eea73
[error] server.go:90 HTTP Error: statusCode=404 No such container: 05fd5f2e506af30fb8eb5ac4620cd395ace523f7802c623a6f7a38656c8eea73
2014/05/20 21:35:47 DELETE /containers/05fd5f2e506af30fb8eb5ac4620cd395ace523f7802c623a6f7a38656c8eea73
[7b302e61] +job container_delete(05fd5f2e506af30fb8eb5ac4620cd395ace523f7802c623a6f7a38656c8eea73)
No such container: 05fd5f2e506af30fb8eb5ac4620cd395ace523f7802c623a6f7a38656c8eea73
[7b302e61] -job container_delete(05fd5f2e506af30fb8eb5ac4620cd395ace523f7802c623a6f7a38656c8eea73) = ERR (1)
[error] server.go:1011 Error: No such container: 05fd5f2e506af30fb8eb5ac4620cd395ace523f7802c623a6f7a38656c8eea73
[error] server.go:90 HTTP Error: statusCode=404 No such container: 05fd5f2e506af30fb8eb5ac4620cd395ace523f7802c623a6f7a38656c8eea73
```

**Comment by scrichar** [comment]
HELP
