### ISSUE TITLE
NPE in DockerCloud

### ISSUE THREAD

**Issue by thomassuckow** [jenkinsci/docker-plugin#243]
When I left friday I had noticed a job that was having trouble

Seeing lots of
```
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:272)
```
and
```
WARNING: Provisioned slave Image of myImage failed to launch
java.lang.NullPointerException
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:272)
```

Beginning of log:
```
INFO: SCM changes detected in master-matrix. Triggering  #341
May 28, 2015 1:54:20 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
INFO: Asked to provision 1 slave(s) for: centos6&&myLabel
May 28, 2015 1:54:20 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
INFO: Will provision "myOtherImage" for: centos6&&myLabel
May 28, 2015 1:54:30 PM com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
INFO: Provisioning "myOtherImage" number 0 on "myServer"; Total containers: 0
May 28, 2015 1:54:30 PM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
INFO: Started provisioning Image of myOtherImage from myServer with 1 executors. Remaining excess workload: 0
Launching myOtherImage
May 28, 2015 1:54:30 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
INFO: Asked to provision 1 slave(s) for: rhel6&&myLabel
May 28, 2015 1:54:30 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
INFO: Will provision "myImage" for: rhel6&&myLabel
May 28, 2015 1:54:30 PM com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
INFO: Provisioning "myImage" number 0 on "myServer"; Total containers: 1
May 28, 2015 1:54:30 PM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
INFO: Started provisioning Image of myImage from myServer with 1 executors. Remaining excess workload: 0
Launching myImage
May 28, 2015 1:54:36 PM com.nirima.jenkins.plugins.docker.DockerComputerLauncher getSSHLauncher
INFO: Creating slave SSH launcher for myServer:32768
May 28, 2015 1:54:37 PM com.nirima.jenkins.plugins.docker.DockerComputerLauncher getSSHLauncher
INFO: Creating slave SSH launcher for myServer:32769
May 28, 2015 1:54:39 PM hudson.slaves.CloudRetentionStrategy check
INFO: Disconnecting 21830b349d9d@myServer
[05/28/15 13:54:39] SSH Launch of 21830b349d9d@myServer on myServer failed in 478 ms
May 28, 2015 1:54:39 PM com.nirima.jenkins.plugins.docker.DockerCloud$1 call
SEVERE: Error in provisioning; slave=DockerSlave{name=21830b349d9d@myServer, containerId=21830b349d9d0c0c64b9ce3b553cfb7a99a318196bcbc42f5c53bcc95128d118, template=DockerTemplate{image=myOtherImage, parent=DockerCloud{name=myServer, serverUrl=http://myServer:2
375}}}, template=DockerTemplate{image=myOtherImage, parent=DockerCloud{name=myServer, serverUrl=http://myServer:2375}}
java.util.concurrent.ExecutionException: java.io.IOException: Slave failed to connect, even though the launcher didn't report it. See the log output for details.
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:272)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:252)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Slave failed to connect, even though the launcher didn't report it. See the log output for details.
        at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:267)
        ... 5 more
May 28, 2015 1:54:40 PM hudson.slaves.NodeProvisioner$2 run
WARNING: Provisioned slave Image of myOtherImage failed to launch
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.io.IOException: Slave failed to connect, even though the launcher didn't report it. See the log output for details.
        at shaded.com.google.common.base.Throwables.propagate(Throwables.java:160)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:279)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:252)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: Slave failed to connect, even though the launcher didn't report it. See the log output for details.
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:272)
        ... 6 more
Caused by: java.io.IOException: Slave failed to connect, even though the launcher didn't report it. See the log output for details.
        at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:267)
        ... 5 more

May 28, 2015 1:54:40 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
INFO: Asked to provision 1 slave(s) for: centos6&&myLabel
May 28, 2015 1:54:40 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
INFO: Will provision "myOtherImage" for: centos6&&myLabel
May 28, 2015 1:54:41 PM com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
INFO: Provisioning "myOtherImage" number 0 on "myServer"; Total containers: 2
Launching myOtherImage
May 28, 2015 1:54:41 PM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
INFO: Started provisioning Image of myOtherImage from myServer with 1 executors. Remaining excess workload: 0
May 28, 2015 1:54:45 PM com.nirima.jenkins.plugins.docker.DockerComputerLauncher getSSHLauncher
INFO: Creating slave SSH launcher for myServer:32770
May 28, 2015 1:54:47 PM hudson.slaves.CloudRetentionStrategy check
INFO: Disconnecting b3ffa432a6e5@myServer
May 28, 2015 1:54:47 PM hudson.remoting.SynchronousCommandTransport$ReaderThread run
SEVERE: I/O error in channel b3ffa432a6e5@myServer
java.io.IOException: Unexpected termination of the channel
        at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:50)
Caused by: java.io.EOFException
        at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2328)
        at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2797)
        at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:802)
        at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
        at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:40)
        at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
        at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)

[05/28/15 13:54:47] SSH Launch of b3ffa432a6e5@myServer on myServer failed in 7,680 ms
[05/28/15 13:54:47] SSH Launch of b3ffa432a6e5@myServer on myServer failed in 3 ms
May 28, 2015 1:54:47 PM com.nirima.jenkins.plugins.docker.DockerCloud$1 call
SEVERE: Error in provisioning; slave=DockerSlave{name=b3ffa432a6e5@myServer, containerId=b3ffa432a6e56dc3a79c82f0dd9a64a420611e6db26f1915e87bbc41185fb26f, template=DockerTemplate{image=myImage, parent=DockerCloud{name=myServer, serverUrl=http://myServer:2375}}}, template=DockerTemplate{image=myImage, parent=DockerCloud{name=myServer, serverUrl=http://myServer:2375}}
java.util.concurrent.ExecutionException: java.io.IOException: Slave failed to connect, even though the launcher didn't report it. See the log output for details.
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:272)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:252)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Slave failed to connect, even though the launcher didn't report it. See the log output for details.
        at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:267)
        ... 5 more
May 28, 2015 1:54:47 PM hudson.slaves.CloudRetentionStrategy check
INFO: Disconnecting 4099a8c60af5@myServer
May 28, 2015 1:54:47 PM com.nirima.jenkins.plugins.docker.DockerCloud$1 call
SEVERE: Error in provisioning; slave=DockerSlave{name=4099a8c60af5@myServer, containerId=4099a8c60af5fbc46ca03d8840b3f8359ac07e6ed75d7bc8297acc7efc65c7f3, template=DockerTemplate{image=myOtherImage, parent=DockerCloud{name=myServer, serverUrl=http://myServer:2375}}}, template=DockerTemplate{image=myOtherImage, parent=DockerCloud{name=myServer, serverUrl=http://myServer:2375}}
java.lang.NullPointerException
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:272)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:252)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
May 28, 2015 1:54:50 PM hudson.slaves.NodeProvisioner$2 run
WARNING: Provisioned slave Image of myOtherImage failed to launch
java.lang.NullPointerException
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:272)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:252)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by KostyaSha** [comment]
During #234 i found some places where NPE may appear, it seems that #234 is impossible so i soon will start sending small fixes...

**Comment by KostyaSha** [comment]
Yes, this may happen because there is no delay before adding slave and creating computer.
After slave is added jenkins starts updating all computers and creates computer for this slave. 
if delay fails, then computer will be null. Then it fails and tries again.

**Comment by KostyaSha** [comment]
And this can be fixed by preparing cache in image to exclude long startup. I have plans to review latest LTS API, maybe it can somehow influence. 

Btw this probably can be fixed by moving container startup in slave.toComputer(), because then Computer object will be created really fast.

**Comment by KostyaSha** [comment]
@thomassuckow note, this NPE valid and it "as designed"

**Comment by thomassuckow** [comment]
I would question if returning null would be more appropriate.
I also question how Future & PendingNode behave on null & exception

To be honest, I don't trust any code in Jenkins. Especially since practically none of it is documented.

**Comment by KostyaSha** [comment]
After stephenc replies i have some ideas and will try another one round in #234 to implement best practises. My idea is unbundle launchers plus add methods that should handle wait for slave provisioning. Hope this will help us not have NPEs and move upper in @stephenc rating :)

**Comment by thomassuckow** [comment]
If we get more rating from him, we should send what we learned to the ec2 plugin maintainer since it does the same thing.

**Comment by KostyaSha** [comment]
@thomassuckow all cloud plugins hardcoding modes, i don't think that i should fix all other plugins. Like nobody send fixes to docker ;(

**Comment by thomassuckow** [comment]
I don't think you should "fix" it. Just tell them docker is better. ;)

**Comment by KostyaSha** [comment]
@thomassuckow is it still actual?

**Comment by thomassuckow** [comment]
I haven't seen it in a while. You have made a lot of changes. Will reopen if it returns.
