### ISSUE TITLE
Keep on provisioning new containers

### ISSUE THREAD

**Issue by quick-sort** [jenkinsci/docker-plugin#256]
I installed the latest docker plugin in jenkins and I am using a dind jenkins slave docker image as slave, This image will start dind first, then ssh. I found docker plugin kept on creating and destroying containers because of this exception. I guess it is caused by ssh connection timeout, so I set SSH Launch Timeout to 60. But it takes no effect. Where can I set a timeout to wait for the new container ready? 

Error in provisioning; slave=DockerSlave{name=e147a032d1bb@docker, containerId=e147a032d1bbb6607afda80f53d9a6bfdea2346fdc8ce6ffdb1129753497a7b1, template=DockerTemplate{image=quicksort/jenkins-slave, parent=DockerCloud{name=docker, serverUrl=http://10.174.35.1:4243}}}, template=DockerTemplate{image=quicksort/jenkins-slave, parent=DockerCloud{name=docker, serverUrl=http://10.174.35.1:4243}}
Jun 29, 2015 12:09:01 PM INFO com.nirima.jenkins.plugins.docker.DockerComputer updateAcceptingTasks
Slave agent not launched after checking 0 time(s).  Waiting for any retries...
Jun 29, 2015 12:09:08 PM WARNING hudson.slaves.NodeProvisioner$2 run
Provisioned slave Image of quicksort/jenkins-slave failed to launch
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.io.IOException: Slave failed to connect, even though the launcher didn't report it. See the log output for details.
	at shaded.com.google.common.base.Throwables.propagate(Throwables.java:160)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:228)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:201)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: Slave failed to connect, even though the launcher didn't report it. See the log output for details.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:221)
	... 6 more
Caused by: java.io.IOException: Slave failed to connect, even though the launcher didn't report it. See the log output for details.
	at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:267)
	... 5 more

**Comment by KostyaSha** [comment]
Please read https://github.com/jenkinsci/docker-plugin/blob/master/CONTRIBUTING.md
