### ISSUE TITLE
plugin can't connect to SSH

### ISSUE THREAD

**Issue by toejough** [jenkinsci/docker-plugin#269]
# Issue

The plugin seems to be able to connect to my docker instance and create a container, but then seems to be unable to connect to it.

It starts trying to connect to different ports, such as 49156, 49157, 49158, in order.  It always errors out and says it can't connect after 10 attempts, then destroys the container and tries again with a new one.  

Has anyone else seen this?  Does anyone have a clue as to how to fix it?  I did find [this blog](https://dantehranian.wordpress.com/2014/09/08/docker-jenkins-dynamically-provisioning-sles-11-build-containers/) which says that after docker 1.1.2, the plugin is unable to SSH to containers.  Is that true?  I'd really rather not have to downgrade my docker just to use this plugin.

# `Manage Jenkins` -> `Manage Old Data`
```
No old data was found.
```

# Plugins/versions & core version

![screen shot 2015-07-14 at 11 45 49 am](https://cloud.githubusercontent.com/assets/5317312/8677609/0bd8197e-2a1e-11e5-82fb-d32538a82041.png)

Jenkins version: 1.620

# System log
```
Jul 14, 2015 3:04:28 PM com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher getSSHLauncher
INFO: Creating slave SSH launcher for localhost:49153
[07/14/15 15:04:37] SSH Launch of local-docker-cloud-da936133b2d9 on localhost failed in 2 ms
Jul 14, 2015 3:04:37 PM hudson.slaves.NodeProvisioner$2 run
INFO: Image of jenkins-slave-android-1 provisioning successfully completed. We have now 2 computer(s)
Jul 14, 2015 3:04:37 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
INFO: Asked to provision 1 slave(s) for: android
Jul 14, 2015 3:04:37 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
INFO: Will provision 'jenkins-slave-android-1', for label: 'android'
Jul 14, 2015 3:04:37 PM com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
INFO: Provisioning 'jenkins-slave-android-1' number '0' on 'local-docker-cloud'; Total containers: '0'
Jul 14, 2015 3:04:37 PM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
INFO: Started provisioning Image of jenkins-slave-android-1 from local-docker-cloud with 1 executors. Remaining excess workload: 0
Jul 14, 2015 3:04:37 PM com.nirima.jenkins.plugins.docker.DockerCloud provisionWithWait
INFO: Trying to run container for jenkins-slave-android-1
Jul 14, 2015 3:04:37 PM com.nirima.jenkins.plugins.docker.utils.PortUtils bySshWithEveryRetryWaitFor
SEVERE: Failed to connect to localhost:49154 (try 1/10) - There was a problem while connecting to localhost:49154
Jul 14, 2015 3:04:38 PM com.nirima.jenkins.plugins.docker.DockerSlave _terminate
INFO: Disconnected computer
Jul 14, 2015 3:04:38 PM com.nirima.jenkins.plugins.docker.DockerSlave _terminate
SEVERE: Failed to stop instance da936133b2d9bde421fc0c379d19a6dd7b9d087b0760ac68806de3ecb2800bf7 for slave local-docker-cloud-da936133b2d9 due to exception
Jul 14, 2015 3:04:38 PM com.nirima.jenkins.plugins.docker.DockerSlave _terminate
INFO: Removed container da936133b2d9bde421fc0c379d19a6dd7b9d087b0760ac68806de3ecb2800bf7
Jul 14, 2015 3:04:47 PM com.nirima.jenkins.plugins.docker.utils.PortUtils bySshWithEveryRetryWaitFor
SEVERE: Failed to connect to localhost:49154 (try 2/10) - There was a problem while connecting to localhost:49154
Jul 14, 2015 3:04:57 PM com.nirima.jenkins.plugins.docker.utils.PortUtils bySshWithEveryRetryWaitFor
SEVERE: Failed to connect to localhost:49154 (try 3/10) - There was a problem while connecting to localhost:49154
Jul 14, 2015 3:05:07 PM com.nirima.jenkins.plugins.docker.utils.PortUtils bySshWithEveryRetryWaitFor
SEVERE: Failed to connect to localhost:49154 (try 4/10) - There was a problem while connecting to localhost:49154
Jul 14, 2015 3:05:17 PM com.nirima.jenkins.plugins.docker.utils.PortUtils bySshWithEveryRetryWaitFor
SEVERE: Failed to connect to localhost:49154 (try 5/10) - There was a problem while connecting to localhost:49154
Jul 14, 2015 3:05:27 PM com.nirima.jenkins.plugins.docker.utils.PortUtils bySshWithEveryRetryWaitFor
SEVERE: Failed to connect to localhost:49154 (try 6/10) - There was a problem while connecting to localhost:49154
Jul 14, 2015 3:05:37 PM com.nirima.jenkins.plugins.docker.utils.PortUtils bySshWithEveryRetryWaitFor
SEVERE: Failed to connect to localhost:49154 (try 7/10) - There was a problem while connecting to localhost:49154
Jul 14, 2015 3:05:47 PM com.nirima.jenkins.plugins.docker.utils.PortUtils bySshWithEveryRetryWaitFor
SEVERE: Failed to connect to localhost:49154 (try 8/10) - There was a problem while connecting to localhost:49154
Jul 14, 2015 3:05:57 PM com.nirima.jenkins.plugins.docker.utils.PortUtils bySshWithEveryRetryWaitFor
SEVERE: Failed to connect to localhost:49154 (try 9/10) - There was a problem while connecting to localhost:49154
Jul 14, 2015 3:06:07 PM com.nirima.jenkins.plugins.docker.utils.PortUtils bySshWithEveryRetryWaitFor
SEVERE: Failed to connect to localhost:49154 (try 10/10) - There was a problem while connecting to localhost:49154
Jul 14, 2015 3:06:07 PM com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher waitUp
WARNING: Can't connect to ssh
java.io.IOException: There was a problem while connecting to localhost:49154
        at com.trilead.ssh2.Connection.connect(Connection.java:818)
        at com.nirima.jenkins.plugins.docker.utils.PortUtils.bySshWithEveryRetryWaitFor(PortUtils.java:88)
        at com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher.waitUp(DockerComputerSSHLauncher.java:82)
        at com.nirima.jenkins.plugins.docker.DockerCloud.provisionWithWait(DockerCloud.java:279)
        at com.nirima.jenkins.plugins.docker.DockerCloud.access$000(DockerCloud.java:51)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:172)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:169)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:579)
        at com.trilead.ssh2.transport.TransportManager.establishConnection(TransportManager.java:354)
        at com.trilead.ssh2.transport.TransportManager.initialize(TransportManager.java:467)
        at com.trilead.ssh2.Connection.connect(Connection.java:758)
        ... 11 more

Jul 14, 2015 3:06:07 PM com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher getSSHLauncher
INFO: Creating slave SSH launcher for localhost:49154
[07/14/15 15:06:17] SSH Launch of local-docker-cloud-ac1698f9401d on localhost failed in 2 ms
Jul 14, 2015 3:06:17 PM hudson.slaves.NodeProvisioner$2 run
INFO: Image of jenkins-slave-android-1 provisioning successfully completed. We have now 2 computer(s)
Jul 14, 2015 3:06:17 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
INFO: Asked to provision 1 slave(s) for: android
Jul 14, 2015 3:06:17 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
INFO: Will provision 'jenkins-slave-android-1', for label: 'android'
Jul 14, 2015 3:06:17 PM com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
INFO: Provisioning 'jenkins-slave-android-1' number '0' on 'local-docker-cloud'; Total containers: '0'
Jul 14, 2015 3:06:17 PM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
INFO: Started provisioning Image of jenkins-slave-android-1 from local-docker-cloud with 1 executors. Remaining excess workload: 0
Jul 14, 2015 3:06:17 PM com.nirima.jenkins.plugins.docker.DockerCloud provisionWithWait
INFO: Trying to run container for jenkins-slave-android-1
Jul 14, 2015 3:06:17 PM com.nirima.jenkins.plugins.docker.utils.PortUtils bySshWithEveryRetryWaitFor
SEVERE: Failed to connect to localhost:49155 (try 1/10) - There was a problem while connecting to localhost:49155
Jul 14, 2015 3:06:27 PM com.nirima.jenkins.plugins.docker.utils.PortUtils bySshWithEveryRetryWaitFor
SEVERE: Failed to connect to localhost:49155 (try 2/10) - There was a problem while connecting to localhost:49155
Jul 14, 2015 3:06:37 PM com.nirima.jenkins.plugins.docker.utils.PortUtils bySshWithEveryRetryWaitFor
SEVERE: Failed to connect to localhost:49155 (try 3/10) - There was a problem while connecting to localhost:49155
Jul 14, 2015 3:06:38 PM com.nirima.jenkins.plugins.docker.DockerSlave _terminate
INFO: Disconnected computer
Jul 14, 2015 3:06:38 PM com.nirima.jenkins.plugins.docker.DockerSlave _terminate
SEVERE: Failed to stop instance ac1698f9401d826c746e1fad1af7d6194609aff7ef07984064a798e261bdf219 for slave local-docker-cloud-ac1698f9401d due to exception
Jul 14, 2015 3:06:38 PM com.nirima.jenkins.plugins.docker.DockerSlave _terminate
INFO: Removed container ac1698f9401d826c746e1fad1af7d6194609aff7ef07984064a798e261bdf219
Jul 14, 2015 3:06:47 PM com.nirima.jenkins.plugins.docker.utils.PortUtils bySshWithEveryRetryWaitFor
SEVERE: Failed to connect to localhost:49155 (try 4/10) - There was a problem while connecting to localhost:49155
Jul 14, 2015 3:06:57 PM com.nirima.jenkins.plugins.docker.utils.PortUtils bySshWithEveryRetryWaitFor
SEVERE: Failed to connect to localhost:49155 (try 5/10) - There was a problem while connecting to localhost:49155
Jul 14, 2015 3:07:07 PM com.nirima.jenkins.plugins.docker.utils.PortUtils bySshWithEveryRetryWaitFor
SEVERE: Failed to connect to localhost:49155 (try 6/10) - There was a problem while connecting to localhost:49155
Jul 14, 2015 3:07:17 PM com.nirima.jenkins.plugins.docker.utils.PortUtils bySshWithEveryRetryWaitFor
SEVERE: Failed to connect to localhost:49155 (try 7/10) - There was a problem while connecting to localhost:49155
Jul 14, 2015 3:07:27 PM com.nirima.jenkins.plugins.docker.utils.PortUtils bySshWithEveryRetryWaitFor
SEVERE: Failed to connect to localhost:49155 (try 8/10) - There was a problem while connecting to localhost:49155
Jul 14, 2015 3:07:37 PM com.nirima.jenkins.plugins.docker.utils.PortUtils bySshWithEveryRetryWaitFor
SEVERE: Failed to connect to localhost:49155 (try 9/10) - There was a problem while connecting to localhost:49155
Jul 14, 2015 3:07:47 PM com.nirima.jenkins.plugins.docker.utils.PortUtils bySshWithEveryRetryWaitFor
SEVERE: Failed to connect to localhost:49155 (try 10/10) - There was a problem while connecting to localhost:49155
Jul 14, 2015 3:07:47 PM com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher waitUp
WARNING: Can't connect to ssh
java.io.IOException: There was a problem while connecting to localhost:49155
        at com.trilead.ssh2.Connection.connect(Connection.java:818)
        at com.nirima.jenkins.plugins.docker.utils.PortUtils.bySshWithEveryRetryWaitFor(PortUtils.java:88)
        at com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher.waitUp(DockerComputerSSHLauncher.java:82)
        at com.nirima.jenkins.plugins.docker.DockerCloud.provisionWithWait(DockerCloud.java:279)
        at com.nirima.jenkins.plugins.docker.DockerCloud.access$000(DockerCloud.java:51)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:172)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:169)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:579)
        at com.trilead.ssh2.transport.TransportManager.establishConnection(TransportManager.java:354)
        at com.trilead.ssh2.transport.TransportManager.initialize(TransportManager.java:467)
        at com.trilead.ssh2.Connection.connect(Connection.java:758)
        ... 11 more
```
...and so on

# Cloud section from `$JENKINS_HOME/config.xml`
```xml
<clouds>
    <com.nirima.jenkins.plugins.docker.DockerCloud plugin="docker-plugin@0.10.0">
      <name>local-docker-cloud</name>
      <templates>
        <com.nirima.jenkins.plugins.docker.DockerTemplate>
          <configVersion>1</configVersion>
          <labelString>android</labelString>
          <launcher class="com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher">
            <sshConnector plugin="ssh-slaves@1.9">
              <port>22</port>
              <credentialsId>63558e37-868a-4155-8e07-b8873bbb9747</credentialsId>
              <jvmOptions></jvmOptions>
              <javaPath></javaPath>
              <maxNumRetries>0</maxNumRetries>
              <retryWaitTime>0</retryWaitTime>
            </sshConnector>
          </launcher>
          <remoteFsMapping></remoteFsMapping>
          <remoteFs>/home/jenkins</remoteFs>
          <instanceCap>2147483647</instanceCap>
          <mode>NORMAL</mode>
          <retentionStrategy class="com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy">
            <idleMinutes>0</idleMinutes>
            <idleMinutes defined-in="com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy">0</idleMinutes>
          </retentionStrategy>
          <numExecutors>1</numExecutors>
          <dockerTemplateBase>
            <image>jenkins-slave-android-1</image>
            <dockerCommand></dockerCommand>
            <lxcConfString></lxcConfString>
            <hostname></hostname>
            <dnsHosts/>
            <volumes/>
            <volumesFrom2/>
            <environment/>
            <bindPorts></bindPorts>
            <bindAllPorts>false</bindAllPorts>
            <privileged>false</privileged>
            <tty>false</tty>
          </dockerTemplateBase>
        </com.nirima.jenkins.plugins.docker.DockerTemplate>
      </templates>
      <serverUrl>http://127.0.0.1:2375</serverUrl>
      <containerCap>2147483647</containerCap>
      <connectTimeout>5</connectTimeout>
      <readTimeout>15</readTimeout>
      <version></version>
      <credentialsId></credentialsId>
    </com.nirima.jenkins.plugins.docker.DockerCloud>
  </clouds>
```

# Docker Infrastructure
A standard docker install on Ubuntu 14.04.1.

# Docker version
```
Docker version 1.5.0, build a8a31ef
```

# Steps for reproducing
Follow the instructions on the docker-plugin wiki.  Trigger a build.

# Other
The commandline invocation of my docker daemon is:

```
root@foo:~# ps auxwww | grep 48422
root     48422  0.6  0.0 264452 17384 ?        Ssl  15:01   0:00 /usr/bin/docker -d --bridge=docker0 --dns 8.8.8.8 --dns 8.8.4.4 --icc=false --iptables=true -H tcp://0.0.0.0:2375 -H
 unix:///var/run/docker.sock
```

**Comment by thomassuckow** [comment]
I have docker 1.6.2, I doubt the docker version is the issue.

Is docker really on localhost or are you tunneling port 2375 from another machine?

**Comment by toejough** [comment]
it's on localhost.  I added the docker version to the "docker version" field, and I'm now getting this showing up in the logs:

```
INFO: Will provision 'jenkins-slave-android-1', for label: 'android'
Jul 14, 2015 4:22:07 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
WARNING: Bad template 'jenkins-slave-android-1': 'null'. Trying next template...
```

Does that look familiar to anyone?

**Comment by thomassuckow** [comment]
I would try the evarga/jenkins-slave docker image to make sure it isn't your container.
Login info: https://registry.hub.docker.com/u/evarga/jenkins-slave/

I wouldn't specify the version in the config.

**Comment by toejough** [comment]
with `evarga/jenkins-slave`, same thing:
```
INFO: Asked to provision 1 slave(s) for: android
Jul 14, 2015 6:13:57 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
INFO: Will provision 'evarga/jenkins-slave', for label: 'android'
Jul 14, 2015 6:13:57 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
WARNING: Bad template 'evarga/jenkins-slave': 'null'. Trying next template...
```

Trying undoing the version next...

**Comment by toejough** [comment]
minus the version, evarga/jenkins-slave boots fine.  I wish I knew what the problem was so that I could fix the other image, rather than rebuilding it on top of evarga/jenkins-slave.  It had java and a functioning ssh server...

**Comment by toejough** [comment]
it appears to have been the "docker command" - when trying to launch "sshd -D", the image I was using did not have the right permissions without adding "sudo".

Is there a better way this could've been debugged?  Some additional logging to have just seen that sshd -D exited immediately with a bad RC?

**Comment by thomassuckow** [comment]
There could probably be a check to see if the container is still running. I imagine the best error you would get would be that the container exited. Unfortunately the protocol for docker is very asynchronous, it probably wouldn't be trivial to add and keep in sync.

**Comment by toejough** [comment]
ok.  well, I don't know enough to suggest a reasonable fix, so I'm closing this issue.

For anyone who stumbles upon this, the TLDR is that I needed to be running "sudo /usr/sbin/sshd -D" in the "docker command" field, because my default login user was not root.
