### ISSUE TITLE
Docker-plugin provisioning containers and then failing on SSH Launch

### ISSUE THREAD

**Issue by an1ket** [jenkinsci/docker-plugin#288]
We have setup a docker image as described on the plugin wiki (but named jenkie_uno). We are able to run and connect to the container when we run the image. Running a test build through Jenkins leads to a container being provisioned and successfully authenticated. But the build fails immediately after authentication with a "hudson.AbortException" and "SSH Launch of dock01-d217290c5339 on x.x.x.x failed in 328 ms" exceptions.

##### Set up:
Jenkins 1.609.1 on a Windows server
docker-plugin 0.10.2
Docker Client version: 1.7.1 on Red Hat Enterprise Linux Server release 6.6

##### Start up:
sudo docker -H 0.0.0.0:4243 -d

##### Docker Log
```
INFO[5636] GET /containers/json?all=0&size=0
INFO[5636] GET /containers/json?all=0&size=0
INFO[5636] GET /images/json?all=0
INFO[5636] GET /images/jenkie_uno/json
INFO[5636] POST /containers/create
INFO[5637] POST /containers/d217290c53396bf5c22dad5f9ce76320b6db3c3215ca70d13fae24f758dde88f/start
INFO[5637] GET /containers/d217290c53396bf5c22dad5f9ce76320b6db3c3215ca70d13fae24f758dde88f/json
INFO[5656] GET /v1.19/containers/json?all=1
INFO[5656] GET /containers/json?all=0&size=0
INFO[5656] GET /containers/json?all=0&size=0
INFO[5656] GET /images/json?all=0
INFO[5656] GET /images/jenkie_uno/json
INFO[5656] GET /containers/d217290c53396bf5c22dad5f9ce76320b6db3c3215ca70d13fae24f758dde88f/json
INFO[5666] GET /containers/json?all=0&size=0
INFO[5666] GET /containers/json?all=0&size=0
INFO[5666] GET /images/json?all=0
INFO[5666] GET /images/jenkie_uno/json
INFO[5666] GET /containers/d217290c53396bf5c22dad5f9ce76320b6db3c3215ca70d13fae24f758dde88f/json
INFO[5673] POST /containers/d217290c53396bf5c22dad5f9ce76320b6db3c3215ca70d13fae24f758dde88f/stop?t=10
INFO[5675] DELETE /containers/d217290c53396bf5c22dad5f9ce76320b6db3c3215ca70d13fae24f758dde88f?v=0&force=0
INFO[5676] GET /containers/json?all=0&size=0
INFO[5676] GET /containers/json?all=0&size=0
INFO[5676] GET /images/json?all=0
INFO[5676] GET /images/jenkie_uno/json
INFO[5676] POST /containers/create
INFO[5677] POST /containers/85b67396750b49f996f7dcb38f71a528a2b6aae40eb8e6975fe3fd472e58035d/start
INFO[5678] GET /containers/85b67396750b49f996f7dcb38f71a528a2b6aae40eb8e6975fe3fd472e58035d/json
INFO[5709] GET /v1.19/containers/json?all=1
INFO[5733] POST /containers/85b67396750b49f996f7dcb38f71a528a2b6aae40eb8e6975fe3fd472e58035d/stop?t=10
INFO[5735] DELETE /containers/85b67396750b49f996f7dcb38f71a528a2b6aae40eb8e6975fe3fd472e58035d?v=0&force=0
```

##### jenkins.err Log
```
Jul 23, 2015 3:14:24 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
INFO: Asked to provision 1 slave(s) for: docker_ubuntu
Jul 23, 2015 3:14:24 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
INFO: Will provision 'jenkie_uno', for label: 'docker_ubuntu', in cloud: 'dock01'
Jul 23, 2015 3:14:24 PM com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
INFO: Provisioning 'jenkie_uno' number '0' on 'dock01'; Total containers: '0'
Jul 23, 2015 3:14:24 PM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
INFO: Started provisioning Image of jenkie_uno from dock01 with 1 executors. Remaining excess workload: 0
Jul 23, 2015 3:14:24 PM com.nirima.jenkins.plugins.docker.DockerCloud provisionWithWait
INFO: Trying to run container for jenkie_uno
Jul 23, 2015 3:14:26 PM com.nirima.jenkins.plugins.docker.utils.PortUtils bySshWithEveryRetryWaitFor
INFO: SSH port is open on x.x.x.x:9014
Jul 23, 2015 3:14:26 PM com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher getSSHLauncher
INFO: Creating slave SSH launcher for x.x.x.x:9014
Jul 23, 2015 3:14:34 PM hudson.slaves.NodeProvisioner$2 run
INFO: Image of jenkie_uno provisioning successfully completed. We have now 2 computer(s)
Jul 23, 2015 3:14:44 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
INFO: Asked to provision 1 slave(s) for: docker_ubuntu
Jul 23, 2015 3:14:44 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
INFO: Will provision 'jenkie_uno', for label: 'docker_ubuntu', in cloud: 'dock01'
Jul 23, 2015 3:14:44 PM com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
INFO: Not Provisioning 'jenkie_uno'; Server '1' full with 'dock01' container(s)
Jul 23, 2015 3:14:54 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
INFO: Asked to provision 1 slave(s) for: docker_ubuntu
Jul 23, 2015 3:14:54 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
INFO: Will provision 'jenkie_uno', for label: 'docker_ubuntu', in cloud: 'dock01'
Jul 23, 2015 3:14:54 PM com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
INFO: Not Provisioning 'jenkie_uno'; Server '1' full with 'dock01' container(s)
Jul 23, 2015 3:15:02 PM com.nirima.jenkins.plugins.docker.DockerSlave _terminate
INFO: Disconnected computer
Jul 23, 2015 3:15:03 PM com.nirima.jenkins.plugins.docker.DockerSlave _terminate
INFO: Stopped container d217290c53396bf5c22dad5f9ce76320b6db3c3215ca70d13fae24f758dde88f
Jul 23, 2015 3:15:04 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
INFO: Asked to provision 1 slave(s) for: docker_ubuntu
Jul 23, 2015 3:15:04 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
INFO: Will provision 'jenkie_uno', for label: 'docker_ubuntu', in cloud: 'dock01'
Jul 23, 2015 3:15:04 PM com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
INFO: Provisioning 'jenkie_uno' number '0' on 'dock01'; Total containers: '0'
Jul 23, 2015 3:15:04 PM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
INFO: Started provisioning Image of jenkie_uno from dock01 with 1 executors. Remaining excess workload: 0
Jul 23, 2015 3:15:04 PM com.nirima.jenkins.plugins.docker.DockerCloud provisionWithWait
INFO: Trying to run container for jenkie_uno
Jul 23, 2015 3:15:05 PM com.nirima.jenkins.plugins.docker.DockerSlave _terminate
INFO: Removed container d217290c53396bf5c22dad5f9ce76320b6db3c3215ca70d13fae24f758dde88f
Jul 23, 2015 3:15:06 PM com.nirima.jenkins.plugins.docker.utils.PortUtils bySshWithEveryRetryWaitFor
INFO: SSH port is open on x.x.x.x:9015
Jul 23, 2015 3:15:06 PM com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher getSSHLauncher
INFO: Creating slave SSH launcher for x.x.x.x:9015
Jul 23, 2015 3:15:14 PM hudson.slaves.NodeProvisioner$2 run
INFO: Image of jenkie_uno provisioning successfully completed. We have now 2 computer(s)
Jul 23, 2015 3:16:02 PM com.nirima.jenkins.plugins.docker.DockerSlave _terminate
INFO: Disconnected computer
Jul 23, 2015 3:16:03 PM com.nirima.jenkins.plugins.docker.DockerSlave _terminate
INFO: Stopped container 85b67396750b49f996f7dcb38f71a528a2b6aae40eb8e6975fe3fd472e58035d
Jul 23, 2015 3:16:05 PM com.nirima.jenkins.plugins.docker.DockerSlave _terminate
INFO: Removed container 85b67396750b49f996f7dcb38f71a528a2b6aae40eb8e6975fe3fd472e58035d
```
##### jenkins.out Log
```
[07/23/15 15:14:35] SSH Launch of dock01-d217290c5339 on x.x.x.x failed in 328 ms
```

##### Jenkins Docker Plugin Configuration
```xml
<com.nirima.jenkins.plugins.docker.DockerCloud plugin="docker-plugin@0.10.2">
  <name>dock01</name>
  <templates>
	<com.nirima.jenkins.plugins.docker.DockerTemplate>
	  <configVersion>2</configVersion>
	  <labelString>docker_ubuntu</labelString>
	  <launcher class="com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher">
		<sshConnector plugin="ssh-slaves@1.9">
		  <port>22</port>
		  <credentialsId>5638b69d-89f5-4c21-a846-7c2302466b0b</credentialsId>
		  <jvmOptions></jvmOptions>
		  <javaPath></javaPath>
		  <launchTimeoutSeconds>60</launchTimeoutSeconds>
		  <maxNumRetries>0</maxNumRetries>
		  <retryWaitTime>0</retryWaitTime>
		</sshConnector>
	  </launcher>
	  <remoteFsMapping></remoteFsMapping>
	  <remoteFs>/home/jenkins</remoteFs>
	  <instanceCap>2147483647</instanceCap>
	  <mode>NORMAL</mode>
	  <retentionStrategy class="com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy">
		<idleMinutes>0</idleMinutes>
		<idleMinutes defined-in="com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy">0</idleMinutes>
	  </retentionStrategy>
	  <numExecutors>1</numExecutors>
	  <dockerTemplateBase>
		<image>jenkie_uno</image>
		<dockerCommand></dockerCommand>
		<lxcConfString></lxcConfString>
		<hostname>dock01</hostname>
		<dnsHosts/>
		<volumes/>
		<volumesFrom2/>
		<environment/>
		<bindPorts>4243</bindPorts>
		<bindAllPorts>false</bindAllPorts>
		<privileged>false</privileged>
		<tty>false</tty>
		<extraHosts class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
		  <c class="list"/>
		  <list reference="../c"/>
		</extraHosts>
	  </dockerTemplateBase>
	  <removeVolumes>false</removeVolumes>
	</com.nirima.jenkins.plugins.docker.DockerTemplate>
  </templates>
  <serverUrl>http://x.x.x.x:4243</serverUrl>
  <containerCap>1</containerCap>
  <connectTimeout>5</connectTimeout>
  <readTimeout>15</readTimeout>
  <version></version>
  <credentialsId></credentialsId>
</com.nirima.jenkins.plugins.docker.DockerCloud>
```

##### Jenkins Slave log
```
[07/23/15 15:14:34] [SSH] Opening SSH connection to x.x.x.x:9014.
[07/23/15 15:14:35] [SSH] Authentication successful.
SSH connection reports a garbage before a command execution.
Check your .bashrc, .profile, and so on to make sure it is quiet.
The received junk text is as follows:
Welcome to Ubuntu 14.04 LTS (GNU/Linux 3.2.0-77-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.


hudson.AbortException
	at hudson.plugins.sshslaves.SSHLauncher.verifyNoHeaderJunk(SSHLauncher.java:859)
	at hudson.plugins.sshslaves.SSHLauncher.access$100(SSHLauncher.java:133)
	at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:703)
	at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:696)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[07/23/15 15:14:35] Launch failed - cleaning up connection
[07/23/15 15:14:35] [SSH] Connection closed.
```

**Comment by KostyaSha** [comment]
Set Docker Once Retention to 10

**Comment by KostyaSha** [comment]
Also https://github.com/jenkinsci/docker-plugin/commit/cefdb0916faedc7f1ae86298af2fc68b596505ce

**Comment by an1ket** [comment]
Updated information:
##### Description
We have setup a docker image as described on the plugin wiki (but named jenkie_uno). We are able to run and connect to the container when we run the image.

Running a dumb freestyle build in Jenkins leads to a container being provisioned and successfully authenticated. But the build fails immediately after authentication with a "hudson.AbortException" and "SSH Launch of dock01-d217290c5339 on x.x.x.x failed in 328 ms" exceptions.

##### Manage Jenkins -> Manage Old Data
No old data was found.

##### Jenkins Plugins and Versions
Jenkins 1.609.1
active-directory - 1.41
ant - 1.2
antisamy-markup-formatter - 1.1
artifactory - 2.3.0
authentication-tokens - 1.1
credentials - 1.22
cvs - 2.11
docker-plugin - 0.10.2
durable-task - 1.5
external-monitor-job - 1.4
git - 2.3.5
git-client - 1.17.1
javadoc - 1.1
junit - 1.2-beta-4
ldap - 1.6
mailer - 1.11
matrix-auth - 1.1
matrix-project - 1.4.1
maven-plugin - 2.7.1
pam-auth - 1.1
scm-api - 0.2
scm-sync-configuration - 0.0.8
script-security - 1.13
ssh-credentials - 1.10
ssh-slaves - 1.9
subversion - 1.54
swarm - 1.24
token-macro - 1.10
translation - 1.10
windows-slaves - 1.0

**Comment by KostyaSha** [comment]
Did you set retention timeout to 10?

**Comment by an1ket** [comment]
> Set Docker Once Retention to 10

I retried the build after updating the above value. I still get the same errors i.e. authentication is successful but Jenkins loses connection to the slave right away.

The image we are using is created using the instructions for the `evarga/jenkins-slave` but saved using a different name. I will still try replicating this issue using the `evarga/jenkins-slave`.

**Comment by KostyaSha** [comment]
Try exact `evarga/jenkins-slave` image

**Comment by an1ket** [comment]
This works with the `evarga/jenkins-slave` image.
