### ISSUE TITLE
NPE on push

### ISSUE THREAD

**Issue by KostyaSha** [jenkinsci/docker-plugin#302]
Keeping for myself, happens when push configuration is wrong...
```
java.lang.NullPointerException
	at com.github.dockerjava.jaxrs.PushImageCmdExec.name(PushImageCmdExec.java:50)
	at com.github.dockerjava.jaxrs.PushImageCmdExec.execute(PushImageCmdExec.java:36)
	at com.github.dockerjava.jaxrs.PushImageCmdExec.execute(PushImageCmdExec.java:26)
	at com.github.dockerjava.jaxrs.AbstrDockerCmdExec.exec(AbstrDockerCmdExec.java:53)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:29)
	at com.github.dockerjava.core.command.PushImageCmdImpl.exec(PushImageCmdImpl.java:69)
	at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$Run.pushImages(DockerBuilderPublisher.java:276)
	at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$Run.run(DockerBuilderPublisher.java:192)
	at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher.perform(DockerBuilderPublisher.java:287)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:776)
	at hudson.model.Build$BuildExecution.build(Build.java:203)
	at hudson.model.Build$BuildExecution.doRun(Build.java:160)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:536)
	at hudson.model.Run.execute(Run.java:1738)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
```

**Comment by KostyaSha** [comment]
#298

**Comment by KostyaSha** [comment]
Can't reproduce with updated library.
