### ISSUE TITLE
NPE during DockerCloud.pullImage(..)

### ISSUE THREAD

**Issue by Jotschi** [jenkinsci/docker-plugin#315]
* Jenkins Version: 1.627
* Docker Plugin: 0.13.0
* Docker Host Version:
```
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

I'm seeing this NPE when trying to start a docker slave:
```
SEVERE: Error in provisioning; template='DockerTemplate{configVersion=2, labelString='dockerSlave', launcher=com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher@3d93595b, remoteFsMapping='', remoteFs='/home/jenkins', instanceCap=1, mode=EXCLUSIVE, retentionStrategy=com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy@4421368a, numExecutors=1, dockerTemplateBase=DockerTemplateBase{image=jenkins-1}, removeVolumes=false, pullStrategy=PULL_LATEST}' for cloud='satan3'
java.lang.NullPointerException
        at java.util.Arrays$ArrayList.<init>(Arrays.java:2842)
        at java.util.Arrays.asList(Arrays.java:2828)
        at com.nirima.jenkins.plugins.docker.DockerCloud$2.apply(DockerCloud.java:322)
        at com.nirima.jenkins.plugins.docker.DockerCloud$2.apply(DockerCloud.java:319)
        at shaded.com.google.common.collect.Iterators.indexOf(Iterators.java:778)
        at shaded.com.google.common.collect.Iterators.any(Iterators.java:684)
        at shaded.com.google.common.collect.Iterables.any(Iterables.java:623)
        at com.nirima.jenkins.plugins.docker.DockerCloud.pullImage(DockerCloud.java:319)
        at com.nirima.jenkins.plugins.docker.DockerCloud.provisionWithWait(DockerCloud.java:343)
        at com.nirima.jenkins.plugins.docker.DockerCloud.access$000(DockerCloud.java:58)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:233)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:230)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
```

I assume the used docker client is not able to deserialize the tags field within the JSON response.
My docker host returns this JSON to the Docker Plugin:

```json
GET /v1.6.2/images/json?all=0 HTTP/1.1
Accept: application/json
User-Agent: Jersey/2.11 (Apache HttpClient 4.3.1)
Host: docker:2375
Connection: Keep-Alive
Accept-Encoding: gzip,deflate

HTTP/1.1 200 OK
Content-Type: application/json
Date: Wed, 02 Sep 2015 14:17:46 GMT
Content-Length: 516

[{"Created":1440101955,"Id":"0653fde0f5c45dc51d3f1cf944b0013f8ca3797bcca654c9d81d3c29c42ed242","Repository":"debian","Size":0,"Tag":"stable","VirtualSize":125193302}
,{"Created":1419452556,"Id":"8880612971b0e41ecc5de6943c9680bb8dc08027dbae4d3a275ac827293cbf2e","Repository":"evarga/jenkins-slave","Size":0,"Tag":"latest","VirtualSize":610837147}
,{"Created":1419452556,"Id":"8880612971b0e41ecc5de6943c9680bb8dc08027dbae4d3a275ac827293cbf2e","Repository":"jenkins-1","Size":0,"Tag":"latest","VirtualSize":610837147}
]
```

I assume image.getRepoTags() is returning null. The docker server overview also lists no tags for my docker images.

```
$ docker images 
REPOSITORY             TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
debian                 stable              0653fde0f5c4        12 days ago         125.2 MB
evarga/jenkins-slave   latest              8880612971b0        8 months ago        610.8 MB
jenkins-1              latest              8880612971b0        8 months ago        610.8 MB
```

```
    private void pullImage(DockerTemplate dockerTemplate)  throws IOException {
        final String imageName = dockerTemplate.getDockerTemplateBase().getImage();

        List<Image> images = getClient().listImagesCmd().exec();

        NameParser.ReposTag repostag = NameParser.parseRepositoryTag(imageName);
        // if image was specified without tag, then treat as latest
        final String fullImageName = repostag.repos + ":" + (repostag.tag.isEmpty() ? "latest" : repostag.tag);

        boolean imageExists = Iterables.any(images, new Predicate<Image>() {
            @Override
            public boolean apply(Image image) {
                return Arrays.asList(image.getRepoTags()).contains(fullImageName);
            }
        });
```

**Comment by Jotschi** [comment]
I remote debugged the server and i can now confirm that repoTags is null for each image. I assume this issue is in fact a problem within docker-java rather then docker-plugin.

**Comment by Jotschi** [comment]
I'm also able to reproduce this issue with an even older docker version:

```
Client version: 1.2.0
Client API version: 1.14
Go version (client): go1.3.1
Git commit (client): fa7b24f
OS/Arch (client): linux/amd64
Server version: 1.2.0
Server API version: 1.14
Go version (server): go1.3.1
Git commit (server): fa7b24f
```

**Comment by KostyaSha** [comment]
https://github.com/jenkinsci/docker-plugin/blob/master/CONTRIBUTING.md

**Comment by Jotschi** [comment]
I installed the docker-plugin on a clean jenkins installation and i was unable to reproduce the problem. I assume that the problem is caused by a incompatibility with another plugin. I don't have the time to investigate any further. Setting Docker Version parameter in settings to 1.18 resolved the problem. I don't have any other issues with the plugin. Thanks.
