### ISSUE TITLE
can't pull

### ISSUE THREAD

**Issue by KostyaSha** [jenkinsci/docker-plugin#319]
after upgrade to 0.13.0
```
Asked to provision 1 slave(s) for: evarga
Sep 08, 2015 3:24:09 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
Will provision 'evarga/jenkins-slave:latest', for label: 'evarga', in cloud: 'docker'
Sep 08, 2015 3:24:09 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
Provisioning 'evarga/jenkins-slave:latest' number '0' on 'docker'; Total containers: '3'
Sep 08, 2015 3:24:09 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud pullImage
Pulling image 'evarga/jenkins-slave:latest' since one was not found. This may take awhile...
Sep 08, 2015 3:24:09 PM SEVERE com.nirima.jenkins.plugins.docker.DockerCloud$1 call
Error in provisioning; template='DockerTemplate{configVersion=2, labelString='evarga', launcher=com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher@4d6a904, remoteFsMapping='', remoteFs='/home/jenkins', instanceCap=1, mode=EXCLUSIVE, retentionStrategy=com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy@3635a11c, numExecutors=1, dockerTemplateBase=DockerTemplateBase{image=evarga/jenkins-slave:latest}, removeVolumes=false, pullStrategy=PULL_LATEST}' for cloud='docker'
com.github.dockerjava.api.DockerClientException: Could not pull image
	at com.github.dockerjava.core.command.PullImageResultCallback.awaitSuccess(PullImageResultCallback.java:44)
	at com.nirima.jenkins.plugins.docker.DockerCloud.pullImage(DockerCloud.java:336)
	at com.nirima.jenkins.plugins.docker.DockerCloud.provisionWithWait(DockerCloud.java:343)
	at com.nirima.jenkins.plugins.docker.DockerCloud.access$000(DockerCloud.java:58)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:233)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:230)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by KostyaSha** [comment]
Seems just can't pull, maybe timeout issue...
