### ISSUE TITLE
Plugin can't connect to ssh

### ISSUE THREAD

**Issue by fragpit** [jenkinsci/docker-plugin#348]
Hi all, 
facing some troubles right now

plugin version 0.15
docker 1.8.2
OS centos 7.1503

plugin starts container (I checked that ssh is avaliable) and the try to start another one. 

```
    Nov 04, 2015 4:47:39 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
    INFO: Asked to provision 1 slave(s) for: jenkins-slave-nodev4
    Nov 04, 2015 4:47:39 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
    INFO: Will provision 'jenkins-slave-nodev4', for label: 'jenkins-slave-nodev4', in cloud: 'buildagent6'
    Nov 04, 2015 4:47:39 PM com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
    INFO: Provisioning 'jenkins-slave-nodev4' number '0' on 'buildagent6'; Total containers: '0'
    Nov 04, 2015 4:47:39 PM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
    INFO: Started provisioning Image of jenkins-slave-nodev4 from buildagent6 with 1 executors.     Remaining excess workload: 0  
    Nov 04, 2015 4:47:39 PM com.nirima.jenkins.plugins.docker.DockerCloud provisionWithWait
    INFO: Trying to run container for jenkins-slave-nodev4
    Nov 04, 2015 4:47:41 PM com.nirima.jenkins.plugins.docker.DockerCloud$1 call
    SEVERE: Error in provisioning; template='DockerTemplate{configVersion=2, labelString='jenkins-slave-nodev4', launcher=com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher@2b6241af, remoteFsMapping='', remoteFs='/home/jenkins', instanceCap=1, mode=EXCLUSIVE, retentionStrategy=com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy@78606034, numExecutors=1, dockerTemplateBase=DockerTemplateBase{image=jenkins-slave-nodev4}, removeVolumes=false, pullStrategy=PULL_NEVER}' for cloud='buildagent6'
    java.lang.NullPointerException
        at com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher.getPortUtils(DockerComputerSSHLauncher.java:118)
        at com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher.waitUp(DockerComputerSSHLauncher.java:77)
        at com.nirima.jenkins.plugins.docker.DockerCloud.provisionWithWait(DockerCloud.java:378)
        at com.nirima.jenkins.plugins.docker.DockerCloud.access$000(DockerCloud.java:58)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:238)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:235)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
    Nov 04, 2015 4:47:49 PM hudson.slaves.NodeProvisioner update
    WARNING: Provisioned slave Image of jenkins-slave-nodev4 failed to launch
    java.lang.NullPointerException
        at com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher.getPortUtils(DockerComputerSSHLauncher.java:118)
        at com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher.waitUp(DockerComputerSSHLauncher.java:77)
        at com.nirima.jenkins.plugins.docker.DockerCloud.provisionWithWait(DockerCloud.java:378)
        at com.nirima.jenkins.plugins.docker.DockerCloud.access$000(DockerCloud.java:58)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:238)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:235)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
    Nov 04, 2015 4:47:49 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
    INFO: Asked to provision 1 slave(s) for: jenkins-slave-nodev4
    Nov 04, 2015 4:47:49 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
    INFO: Will provision 'jenkins-slave-nodev4', for label: 'jenkins-slave-nodev4', in cloud: 'buildagent6'
    Nov 04, 2015 4:47:49 PM com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
    INFO: Not Provisioning 'jenkins-slave-nodev4'. Instance limit of '1' reached on server 'buildagent6'
```

**Comment by KostyaSha** [comment]
Probably duplicates https://github.com/jenkinsci/docker-plugin/issues/339

**Comment by fragpit** [comment]
I've downgraded docker and plugin versions to
plugin 0.13
docker 1.8.1

but, the problem still remains.

**Comment by magnayn** [comment]
possibility: your slave image does not expose port 22 to any outside
connectable port number.

**Comment by fragpit** [comment]
I use port 10022, and configured it in Docker template. also I expose 22, but map it to 10022. I checked connection to container manually, and it works.

**Comment by KostyaSha** [comment]
@fragpit ssh launcher expects some things like EXPOSE 22, when you opened this issue you had notification about https://github.com/jenkinsci/docker-plugin/blob/master/CONTRIBUTING.md that states that you should try reproduce issue with evarga jenkin-slave. Have you tried?

**Comment by magnayn** [comment]
That may be so, but it's failing to find it. Your NPE is the last line of
the following:

final InspectContainerResponse.NetworkSettings networkSettings =
ir.getNetworkSettings();
        final Ports ports = networkSettings.getPorts();
        final Map<ExposedPort, Ports.Binding[]> bindings =
ports.getBindings();
        final Ports.Binding[] sshBindings = bindings.get(sshPort);

>>> Here        for (Ports.Binding b : sshBindings) {


So it's likely not finding any binding to the declared port.

**Comment by KostyaSha** [comment]
@fragpit also https://github.com/jenkinsci/docker-plugin/blob/master/CONTRIBUTING.md requires from you provide cloud section from `config.xml`

**Comment by fragpit** [comment]
my part of config.xml. Now, I'll try to check with port 22 and evarga/jenkins-slave image. 
```xml
<clouds>
    <com.nirima.jenkins.plugins.docker.DockerCloud plugin="docker-plugin@0.13.0">
      <name>buildagent6</name>
      <templates>
        <com.nirima.jenkins.plugins.docker.DockerTemplate>
          <configVersion>2</configVersion>
          <labelString>jenkins-slave-nodev4</labelString>
          <launcher class="com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher">
            <sshConnector plugin="ssh-slaves@1.10">
              <port>10022</port>
              <credentialsId>b7cfa20c-f131-4c3a-aa4f-e02f469c27cd</credentialsId>
              <jvmOptions></jvmOptions>
              <javaPath></javaPath>
              <launchTimeoutSeconds>15</launchTimeoutSeconds>
              <maxNumRetries>1</maxNumRetries>
              <retryWaitTime>1</retryWaitTime>
            </sshConnector>
          </launcher>
          <remoteFsMapping></remoteFsMapping>
          <remoteFs>/home/jenkins</remoteFs>
          <instanceCap>1</instanceCap>
          <mode>EXCLUSIVE</mode>
          <retentionStrategy class="com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy">
            <idleMinutes>10</idleMinutes>
            <idleMinutes defined-in="com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy">10</idleMinutes>
          </retentionStrategy>
          <numExecutors>1</numExecutors>
          <dockerTemplateBase>
            <image>jenkins-slave-nodev4</image>
            <dockerCommand>/usr/sbin/sshd -D -e</dockerCommand>
            <lxcConfString></lxcConfString>
            <hostname></hostname>
            <dnsHosts/>
            <volumes/>
            <volumesFrom2/>
            <environment/>
            <bindPorts>10022:22</bindPorts>
            <bindAllPorts>false</bindAllPorts>
            <privileged>false</privileged>
            <tty>true</tty>
            <extraHosts class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
              <c class="list"/>
              <list reference="../c"/>
            </extraHosts>
          </dockerTemplateBase>
          <removeVolumes>false</removeVolumes>
          <pullStrategy>PULL_LATEST</pullStrategy>
        </com.nirima.jenkins.plugins.docker.DockerTemplate>
      </templates>
      <serverUrl>http://buildagent6.dm.com:2375</serverUrl>
      <connectTimeout>3</connectTimeout>
      <readTimeout>15</readTimeout>
      <version>1.20</version>
      <credentialsId></credentialsId>
      <containerCap>5</containerCap>
    </com.nirima.jenkins.plugins.docker.DockerCloud>
  </clouds>
```

**Comment by fragpit** [comment]
Seems, that problem in custom ssh port. It's OK with default 22.

**Comment by jwnx** [comment]
Unfortunately, I'm still having this issue 

docker 1.10.3 build 20f81dd
plugin 0.16
Ubuntu 14.04 ppc64le

    May 07, 2016 2:31:00 AM WARNING hudson.model.Descriptor$NewInstanceBindInterceptor instantiate
		falling back to default instantiation com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy {"stapler-class":"com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy","idleMinutes":"10"}
		java.lang.NullPointerException
			at hudson.model.Descriptor$NewInstanceBindInterceptor.instantiate(Descriptor.java:641)
			at org.kohsuke.stapler.RequestImpl.instantiate(RequestImpl.java:747)
			at org.kohsuke.stapler.RequestImpl.access$200(RequestImpl.java:81)
			at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:672)
			at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:476)
			at org.kohsuke.stapler.RequestImpl.injectSetters(RequestImpl.java:836)
			at org.kohsuke.stapler.RequestImpl.instantiate(RequestImpl.java:775)
			at org.kohsuke.stapler.RequestImpl.access$200(RequestImpl.java:81)
			at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:672)
			at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:476)
			at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:472)
			at hudson.model.Descriptor.newInstance(Descriptor.java:590)
			at hudson.model.Descriptor$NewInstanceBindInterceptor.onConvert(Descriptor.java:661)
			at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:615)
			at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:710)
			at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:476)
			at org.kohsuke.stapler.RequestImpl.instantiate(RequestImpl.java:769)
			at org.kohsuke.stapler.RequestImpl.access$200(RequestImpl.java:81)
			at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:672)
			at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:476)
			at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:472)
			at hudson.model.Descriptor.newInstance(Descriptor.java:590)
			at hudson.model.Descriptor.newInstancesFromHeteroList(Descriptor.java:1043)
			at hudson.model.Descriptor.newInstancesFromHeteroList(Descriptor.java:1005)
			at hudson.util.DescribableList.rebuildHetero(DescribableList.java:208)
			at jenkins.model.GlobalCloudConfiguration.configure(GlobalCloudConfiguration.java:23)
			at jenkins.model.Jenkins.configureDescriptor(Jenkins.java:3403)
			at jenkins.model.Jenkins.doConfigSubmit(Jenkins.java:3366)
			at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
			at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
			at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
			at java.lang.reflect.Method.invoke(Method.java:498)
			at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:320)
			at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:163)
			at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:96)
			at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:124)
			at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
			at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
			at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
			at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
			at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
			at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
			at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
			at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
			at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:135)
			at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:126)
			at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
			at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:80)
			at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
			at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
			at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
			at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
			at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
			at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
		at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
			at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
			at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
			at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
			at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
			at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
			at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
			at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
			at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
			at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
			at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
			at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
			at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
			at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
			at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
			at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
			at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
			at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
			at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
			at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
			at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
			at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
			at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:553)
			at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
			at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
			at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
			at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
			at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
			at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
			at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
			at org.eclipse.jetty.server.Server.handle(Server.java:499)
			at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
			at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
			at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
			at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
			at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
			at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
			at java.lang.Thread.run(Thread.java:745)

		May 07, 2016 2:31:00 AM WARNING hudson.model.Descriptor$NewInstanceBindInterceptor instantiate
		falling back to default instantiation com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher {"stapler-class":"com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher","sshConnector":{"credentialsId":"d71c4cf5-6c7d-4c7d-9467-85ab3ff4b6b0","port":"22","javaPath":"","jvmOptions":"","prefixStartSlaveCmd":"","suffixStartSlaveCmd":"","launchTimeoutSeconds":"","maxNumRetries":"0","retryWaitTime":"0"}}
		java.lang.NullPointerException
			at hudson.model.Descriptor$NewInstanceBindInterceptor.instantiate(Descriptor.java:641)
			at org.kohsuke.stapler.RequestImpl.instantiate(RequestImpl.java:747)
			at org.kohsuke.stapler.RequestImpl.access$200(RequestImpl.java:81)
			at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:672)
			at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:476)
			at org.kohsuke.stapler.RequestImpl.injectSetters(RequestImpl.java:836)
			at org.kohsuke.stapler.RequestImpl.instantiate(RequestImpl.java:775)
			at org.kohsuke.stapler.RequestImpl.access$200(RequestImpl.java:81)
			at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:672)
			at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:476)
			at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:472)
			at hudson.model.Descriptor.newInstance(Descriptor.java:590)
			at hudson.model.Descriptor$NewInstanceBindInterceptor.onConvert(Descriptor.java:661)
			at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:615)
			at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:710)
			at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:476)
			at org.kohsuke.stapler.RequestImpl.instantiate(RequestImpl.java:769)
			at org.kohsuke.stapler.RequestImpl.access$200(RequestImpl.java:81)
			at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:672)
			at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:476)
			at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:472)
			at hudson.model.Descriptor.newInstance(Descriptor.java:590)
			at hudson.model.Descriptor.newInstancesFromHeteroList(Descriptor.java:1043)
			at hudson.model.Descriptor.newInstancesFromHeteroList(Descriptor.java:1005)
			at hudson.util.DescribableList.rebuildHetero(DescribableList.java:208)
			at jenkins.model.GlobalCloudConfiguration.configure(GlobalCloudConfiguration.java:23)
			at jenkins.model.Jenkins.configureDescriptor(Jenkins.java:3403)
			at jenkins.model.Jenkins.doConfigSubmit(Jenkins.java:3366)
			at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
			at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
			at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
			at java.lang.reflect.Method.invoke(Method.java:498)
			at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:320)
			at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:163)
			at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:96)
			at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:124)
			at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
			at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
			at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
			at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
			at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
			at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
			at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
			at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
			at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:135)
			at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:126)
			at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
			at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:80)
			at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
			at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
			at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
			at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
			at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
			at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
			at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
			at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
			at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
			at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
			at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
			at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
			at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
			at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
			at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
			at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
			at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
			at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
			at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
			at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
			at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
			at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
			at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
			at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
			at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
			at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
			at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
			at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
			at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:553)
			at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
			at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
			at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
			at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
			at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
			at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
			at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
			at org.eclipse.jetty.server.Server.handle(Server.java:499)
			at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
			at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
			at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
			at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
			at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
			at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
			at java.lang.Thread.run(Thread.java:745)

		May 07, 2016 2:31:20 AM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
		Asked to provision 1 slave(s) for: null
		May 07, 2016 2:31:20 AM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
		Will provision 'jenkins-slave', for label: 'null', in cloud: 'docker'
		May 07, 2016 2:31:22 AM INFO com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
		Provisioning 'jenkins-slave' number '1' on 'docker'; Total containers: '1'
		May 07, 2016 2:31:22 AM INFO hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
		Started provisioning Image of jenkins-slave from docker with 1 executors. Remaining excess workload: 0
		May 07, 2016 2:31:22 AM INFO com.nirima.jenkins.plugins.docker.DockerCloud provisionWithWait
		Trying to run container for jenkins-slave
		May 07, 2016 2:31:22 AM SEVERE com.nirima.jenkins.plugins.docker.DockerCloud$1 call
		Error in provisioning; template='DockerTemplate{configVersion=2, labelString='', launcher=com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher@1685c784, remoteFsMapping='', remoteFs='/home/jenkins', instanceCap=2, mode=NORMAL, retentionStrategy=com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy@1317e53f, numExecutors=1, dockerTemplateBase=DockerTemplateBase{image=jenkins-slave}, removeVolumes=false, pullStrategy=PULL_LATEST}' for cloud='docker'
		java.lang.NullPointerException
			at com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher.getAddressForSSHD(DockerComputerSSHLauncher.java:126)
			at com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher.waitUp(DockerComputerSSHLauncher.java:79)
			at com.nirima.jenkins.plugins.docker.DockerCloud.provisionWithWait(DockerCloud.java:393)
			at com.nirima.jenkins.plugins.docker.DockerCloud.access$000(DockerCloud.java:57)
			at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:242)
			at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:239)
			at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
			at java.util.concurrent.FutureTask.run(FutureTask.java:266)
			at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
			at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
			at java.lang.Thread.run(Thread.java:745)

		May 07, 2016 2:31:30 AM WARNING hudson.slaves.NodeProvisioner$2 run
		Provisioned agent Image of jenkins-slave failed to launch
		java.lang.NullPointerException
			at com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher.getAddressForSSHD(DockerComputerSSHLauncher.java:126)
			at com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher.waitUp(DockerComputerSSHLauncher.java:79)
			at com.nirima.jenkins.plugins.docker.DockerCloud.provisionWithWait(DockerCloud.java:393)
			at com.nirima.jenkins.plugins.docker.DockerCloud.access$000(DockerCloud.java:57)
			at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:242)
			at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:239)
			at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
			at java.util.concurrent.FutureTask.run(FutureTask.java:266)
			at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
			at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
			at java.lang.Thread.run(Thread.java:745)

**Comment by plainwu** [comment]
I have the same issue....

Docker version 1.11.1, build 5604cbe
Docker plugin 0.16.0
