### ISSUE TITLE
Error in provisioning if starting two containers at same time on same host with Pull once strategy

### ISSUE THREAD

**Issue by cjthorne** [jenkinsci/docker-plugin#356]
I've noticed several `SEVERE: Error in provisioning` errors in my error log when my Jenkins master is heavily loaded. 

Looking at the log file whenever I see this error I see the jenkins docker plugin trying to start two slave containers at the same time on the same host machine (a dedicated machine running docker for our builds). I am using the _Pull once and update latest_ Pull strategy.

The exception I see is:

```
SEVERE: Error in provisioning; template='DockerTemplate{configVersion=2, labelString='dockerbuild-local-fix', launcher=com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher@12989a17, remoteFsMapping='', remoteFs='/home/jenkins', instanceCap=5, mode=NORMAL, retentionStrategy=com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy@91920d14, numExecutors=1, dockerTemplateBase=DockerTemplateBase{image=alchemyregistry.hursley.ibm.com:5000/dockerbuild-fix:latest}, removeVolumes=true, pullStrategy=PULL_LATEST}' for cloud='flakebuilds01.hursley.ibm.com'
com.github.dockerjava.api.DockerClientException: Could not pull image: null
        at com.github.dockerjava.core.command.PullImageResultCallback.awaitSuccess(PullImageResultCallback.java:46)
        at com.nirima.jenkins.plugins.docker.DockerCloud.pullImage(DockerCloud.java:336)
        at com.nirima.jenkins.plugins.docker.DockerCloud.provisionWithWait(DockerCloud.java:343)
        at com.nirima.jenkins.plugins.docker.DockerCloud.access$000(DockerCloud.java:58)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:233)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:230)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:274)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1157)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:627)
        at java.lang.Thread.run(Thread.java:798)
```

I had a search for existing issues and I wonder if it is related to https://github.com/jenkinsci/docker-plugin/issues/339 and the way the docker java code determines if a pull is successful. I know that if you use docker to pull the same image twice on the same machine you get this message for the second pull:
`Repository alchemyregistry.hursley.ibm.com:5000/dockerbuild-fix already being pulled by another client. Waiting.`

My workaround for this issue is to change the Pull strategy to _Never pull_.

Plugin version: 0.13.0

**Comment by kepeket** [comment]
I have the exact same issue and I've used a different method to pull the images on the machines.

**Comment by ndeloof** [comment]
recent version of Docker do manage concurrent pulls, and should as such fix this issue
