### ISSUE TITLE
Slave went offline during build - leaves container instance(s) running indefinitely

### ISSUE THREAD

**Issue by dnwe** [jenkinsci/docker-plugin#357]
We periodically see builds get aborted mid-run after losing connectivity to the remote slave container via ssh. Whenever this happens, the running container on the remote host is never shutdown and removed, but instead it is left running indefinitely. Once the instance cap is reached, no more builds will ever run.

```
Slave went offline during the build
ERROR: Connection was broken: java.io.IOException: Unexpected termination of the channel
    at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:50)
Caused by: java.io.EOFException
    at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2428)
    at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2897)
    at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:883)
    at java.io.ObjectInputStream.<init>(ObjectInputStream.java:349)
    at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:40)
    at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
    at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)

Build step 'Invoke Gradle script' marked build as failure
FATAL: hudson.remoting.ChannelClosedException: channel is already closed
hudson.remoting.RemotingSystemException: hudson.remoting.ChannelClosedException: channel is already closed
    at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:195)
    at com.sun.proxy.$Proxy84.stop(Unknown Source)
    at com.cloudbees.jenkins.plugins.sshagent.SSHAgentBuildWrapper$SSHAgentEnvironment.tearDown(SSHAgentBuildWrapper.java:360)
    at hudson.model.Build$BuildExecution.doRun(Build.java:173)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
    at hudson.model.Run.execute(Run.java:1741)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:381)
Caused by: hudson.remoting.ChannelClosedException: channel is already closed
    at hudson.remoting.Channel.send(Channel.java:550)
    at hudson.remoting.Request.call(Request.java:129)
    at hudson.remoting.Channel.call(Channel.java:752)
    at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:179)
    ... 8 more
Caused by: java.io.IOException: Unexpected termination of the channel
    at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:50)
Caused by: java.io.EOFException
    at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2428)
    at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2897)
    at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:883)
    at java.io.ObjectInputStream.<init>(ObjectInputStream.java:349)
    at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:40)
    at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
    at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)
Finished: FAILURE
```

**Comment by KostyaSha** [comment]
https://github.com/jenkinsci/docker-plugin/blob/master/CONTRIBUTING.md

**Comment by xiajidexue** [comment]
also encountered this problems many times

**Comment by ndeloof** [comment]
very hard to diagnose why channel was closed prematurely. Maybe not even related to docker-plugin (container still running, I wonder how it could be involved here)
would at least help to know the launcher being used here.

**Comment by dnwe** [comment]
@ndeloof well, it was SSH launcher as you can see from the stacktrace and I did mention in the issue text. However, this was raised 2 years ago now so a lot has probably changed in Jenkins remoting, the ssh Agent Plugin and the docker plugin so I’m happy to close this one.

**Comment by ndeloof** [comment]
@dwe indeed, sorry for confusion. Currently doing triage on too many old issues :P
