### ISSUE TITLE
Could not build image

### ISSUE THREAD

**Issue by Rajh** [jenkinsci/docker-plugin#359]
Hi,

I'm using docker-plugin to build a project into a docker-slave. This works great.
But at the end of the build I'd like to create a docker image from a Dockerfile and I'm getting the following error : 

```
Docker Build
Docker Build: building image at path /var/jenkins_home/workspace/Test-DockerBuild/test
ERROR: Build step failed with exception
com.github.dockerjava.api.DockerClientException: Could not build image
    at com.github.dockerjava.core.command.BuildImageResultCallback.getImageId(BuildImageResultCallback.java:66)
    at com.github.dockerjava.core.command.BuildImageResultCallback.awaitImageId(BuildImageResultCallback.java:45)
    at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$Run$1.invoke(DockerBuilderPublisher.java:248)
```

1) Where is the docker build done ? On the host ? The jenkins-master docker or the jenkins-slave docker ?
2) Could I get some log ?

Tried with a simple project executing shell : 
mkdir -p test
echo "FROM tomcat:8.0.20-jre8" > test/Dockerfile

**Comment by Rajh** [comment]
Anybody have any idea about which can cause the error ?

**Comment by hcguersoy** [comment]
Hello Rajh,

running into same issue building images:

```
Docker Build
Docker Build: building image at path /home/jenkins/workspace/Create-Image/apache2
ERROR: Build step failed with exception
com.github.dockerjava.api.DockerClientException: Could not build image
    at com.github.dockerjava.core.command.BuildImageResultCallback.getImageId(BuildImageResultCallback.java:66)
    at com.github.dockerjava.core.command.BuildImageResultCallback.awaitImageId(BuildImageResultCallback.java:45)
    at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$Run$1.invoke(DockerBuilderPublisher.java:242)
    at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$Run$1.invoke(DockerBuilderPublisher.java:228)
    at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2691)
    at hudson.remoting.UserRequest.perform(UserRequest.java:120)
    at hudson.remoting.UserRequest.perform(UserRequest.java:48)
    at hudson.remoting.Request$2.run(Request.java:326)
    at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
    at ......remote call to slaves-71c3c2ac7065(Native Method)
    at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1416)
    at hudson.remoting.UserResponse.retrieve(UserRequest.java:220)
    at hudson.remoting.Channel.call(Channel.java:781)
    at hudson.FilePath.act(FilePath.java:980)
    at hudson.FilePath.act(FilePath.java:969)
    at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$Run.buildImage(DockerBuilderPublisher.java:228)
    at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$Run.run(DockerBuilderPublisher.java:186)
    at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher.perform(DockerBuilderPublisher.java:281)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:785)
    at hudson.model.Build$BuildExecution.build(Build.java:205)
    at hudson.model.Build$BuildExecution.doRun(Build.java:162)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
    at hudson.model.Run.execute(Run.java:1741)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:408)
Build step 'Build / Publish Docker Containers' marked build as failure 
```

This doesn't happen always, but I would assume between 5% to 10% of all out image builds fail due to this error. 

We're using Plugin version 0.15.0 on Jenkins 1.625.3 (we've not upgraded yet to latest LTS  due to several incompatibilities with several plugins).

**Comment by ndeloof** [comment]
docker build do always happens on docker host (`build` command do send context to daemon, nothing is ran locally)
if what you're looking for is "just" to build docker images from a Dockerfile you might better look at https://wiki.jenkins.io/display/JENKINS/CloudBees+Docker+Build+and+Publish+plugin

please reopen this issue if you have some more informations about this issue.
