### ISSUE TITLE
Exception into getAddressForSSHD

### ISSUE THREAD

**Issue by sergeychipiga** [jenkinsci/docker-plugin#360]
Hello!

I'm trying to use Jenkins Docker plugin, but provisining breaks with exception:

```
Dec 13, 2015 2:27:04 PM SEVERE com.nirima.jenkins.plugins.docker.DockerCloud$1 call

Error in provisioning; template='DockerTemplate{configVersion=2, labelString='docker-image', launcher=com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher@939fe2a, remoteFsMapping='', remoteFs='/home/user/jenkins', instanceCap=1, mode=NORMAL, retentionStrategy=com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy@461ab00d, numExecutors=1, dockerTemplateBase=DockerTemplateBase{image=my_ubuntu_image}, removeVolumes=false, pullStrategy=PULL_NEVER}' for cloud='docker'
java.lang.NullPointerException
	at com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher.getAddressForSSHD(DockerComputerSSHLauncher.java:126)
	at com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher.waitUp(DockerComputerSSHLauncher.java:79)
	at com.nirima.jenkins.plugins.docker.DockerCloud.provisionWithWait(DockerCloud.java:393)
	at com.nirima.jenkins.plugins.docker.DockerCloud.access$000(DockerCloud.java:57)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:242)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:239)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Jenkins v1.641
Docker v1.9.1
Plugin v0.16

Please, help

**Comment by Thomas-Clark** [comment]
If you're running your containers on a different host, do you have ports exposed? Check the output of "docker ps" on your Docker host when a slave is running.

**Comment by sergeychipiga** [comment]
Hello @Thomas-Clark,

I found the core of problem. It's related with API changing in docker v1.9. The patch from pr #320 fixed my issue.

**Comment by KostyaSha** [comment]
@sergeychipiga https://github.com/jenkinsci/docker-plugin/pull/320#issuecomment-140207974
Duplicates #320
