### ISSUE TITLE
[bug] build stuck in multiple containers boot loop due to port bindings

### ISSUE THREAD

**Issue by bernardgut** [jenkinsci/docker-plugin#365]
This is a bug:

So If you declare some port binding e.g. "1234:1234" and for some reason a container is already running the same build on your host, then the plugin will start a boot loop without cleaning up. This doesn't seem to time out at the "container limit" parameter neither.

REPRODUCE 
1. run a build that binds 1234:1234 and pause it (or run an instance of your build image with the exact same parameters on your host)
2. run another build instance of the same project on the same host
3. go to the host and try `docker ps -all` to see it get populated with countless instances at the rate of 1 every 5~10 secs.

I think the proper behaviour would be to fail the build if the port is already in use and not try again.

exerpt of the loop: 

```
Jan 11, 2016 10:43:54 AM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
Asked to provision 1 slave(s) for: docktest
Jan 11, 2016 10:43:54 AM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
Will provision 'internal_registry:5000/ix-build-base', for label: 'docktest', in cloud: 'docktest'
Jan 11, 2016 10:43:54 AM INFO com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
Provisioning 'internal_registry:5000/ix-build-base' number '1' on 'docktest'; Total containers: '9'
Jan 11, 2016 10:43:54 AM INFO hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
Started provisioning Image of internal_registry:5000/ix-build-base from docktest with 1 executors. Remaining excess workload: 0
Jan 11, 2016 10:43:54 AM INFO com.nirima.jenkins.plugins.docker.DockerCloud provisionWithWait
Trying to run container for internal_registry:5000/ix-build-base
Jan 11, 2016 10:44:06 AM SEVERE com.nirima.jenkins.plugins.docker.DockerCloud$1 call
Error in provisioning; template='DockerTemplate{configVersion=2, labelString='docktest', launcher=com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher@22f06660, remoteFsMapping='', remoteFs='/home/jenkins', instanceCap=4, mode=NORMAL, retentionStrategy=com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy@745aa72d, numExecutors=1, dockerTemplateBase=DockerTemplateBase{image=internal_registry:5000/ix-build-base}, removeVolumes=false, pullStrategy=PULL_LATEST}' for cloud='docktest'
com.github.dockerjava.api.InternalServerErrorException: Cannot start container 0d4e63819195ae609103b522ff94dc4c2f57f435829133296abf5bfb9927f51e: failed to create endpoint small_hawking on network bridge: Bind for 0.0.0.0:1234 failed: port is already allocated

    at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:53)
    at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:134)
    at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:123)
    at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
    at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:251)
    at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:667)
    at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:664)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
    at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:664)
    at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:424)
    at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:333)
    at com.github.dockerjava.jaxrs.StartContainerCmdExec.execute(StartContainerCmdExec.java:28)
    at com.github.dockerjava.jaxrs.StartContainerCmdExec.execute(StartContainerCmdExec.java:13)
    at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:24)
    at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:33)
    at com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:53)
    at com.nirima.jenkins.plugins.docker.DockerCloud.runContainer(DockerCloud.java:288)
    at com.nirima.jenkins.plugins.docker.DockerCloud.provisionWithWait(DockerCloud.java:366)
    at com.nirima.jenkins.plugins.docker.DockerCloud.access$000(DockerCloud.java:57)
    at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:242)
    at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:239)
    at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

Jan 11, 2016 10:44:14 AM WARNING hudson.slaves.NodeProvisioner$2 run
Provisioned slave Image of internal_registry:5000/ix-build-base failed to launch
com.github.dockerjava.api.InternalServerErrorException: Cannot start container 0d4e63819195ae609103b522ff94dc4c2f57f435829133296abf5bfb9927f51e: failed to create endpoint small_hawking on network bridge: Bind for 0.0.0.0:1234 failed: port is already allocated

    at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:53)
    at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:134)
    at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:123)
    at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
    at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:251)
    at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:667)
    at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:664)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
    at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:664)
    at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:424)
    at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:333)
    at com.github.dockerjava.jaxrs.StartContainerCmdExec.execute(StartContainerCmdExec.java:28)
    at com.github.dockerjava.jaxrs.StartContainerCmdExec.execute(StartContainerCmdExec.java:13)
    at Asked to provision 1 slave(s) for: docktest
Jan 11, 2016 10:44:14 AM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
Will provision 'internal_registry:5000/ix-build-base', for label: 'docktest', in cloud: 'docktest'
Jan 11, 2016 10:44:14 AM INFO com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
Provisioning 'internal_registry:5000/ix-build-base' number '1' on 'docktest'; Total containers: '9'com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:24)
    at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:33)
    at com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:53)
    at com.nirima.jenkins.plugins.docker.DockerCloud.runContainer(DockerCloud.java:288)
    at com.nirima.jenkins.plugins.docker.DockerCloud.provisionWithWait(DockerCloud.java:366)
    at com.nirima.jenkins.plugins.docker.DockerCloud.access$000(DockerCloud.java:57)
    at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:242)
    at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:239)
    at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Jan 11, 2016 10:44:14 AM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
Asked to provision 1 sAsked to provision 1 slave(s) for: docktest
Jan 11, 2016 10:44:14 AM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
Will provision 'internal_registry:5000/ix-build-base', for label: 'docktest', in cloud: 'docktest'
Jan 11, 2016 10:44:14 AM INFO com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
Provisioning 'internal_registry:5000/ix-build-base' number '1' on 'docktest'; Total containers: '9'lave(s) for: docktest
Jan 11, 2016 10:44:14 AM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
Will provision 'internal_registry:5000/ix-build-base', for label: 'docktest', in cloud: 'docktest'
Jan 11, 2016 10:44:14 AM INFO com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
Provisioning 'internal_registry:5000/ix-build-base' number '1' on 'docktest'; Total containers: '9'
etc.
```

**Comment by KostyaSha** [comment]
When you are opening issue you see https://github.com/blog/1184-contributing-guidelines please follow it before creating an issue.

**Comment by KostyaSha** [comment]
Seems i know where issue may happen...

**Comment by bernardgut** [comment]
any news ?..

**Comment by KostyaSha** [comment]
Well, i have reworked counting algorithm, so not sure what happened here without info require in https://github.com/jenkinsci/docker-plugin/blob/master/CONTRIBUTING.md

**Comment by magnayn** [comment]
So the inability to bind the port is causing an exception in docker-java.
It's a pity that it's not a checked exception, as the container has indeed
started (just not completely) since what you need to do in that
circumstance is a compensatory action (of stopping the just started
container).

If you wish to pursue a fix, I would catch the exception in DockerCloud:288
and do an equivalent stopContainerCommand, then rethrow the exception.

That said, binding to a fixed port in this way is likely a bad idea. Even
preventing containers being constantly started, Jenkins is still going to
get heavily bogged down constantly trying (and failing) to continuously
start up instances. You'd be advised to look at limiting the number of
concurrent builds in some way (perhaps a cloud instance maximum for that
label).


On Tue, Jan 12, 2016 at 2:36 PM, Bernard Gütermann <notifications@github.com

**Comment by bernardgut** [comment]
yes exactly. First it shoud probably be fixed with the stopContainerCommand fix described by @magnayn so there is no boot loop issue on fixed port exports.

Then, considering what @magnayn said about the system being bogged down by fixed ports containers (design issue), consider the following: The point of exposing a port in Jenkins is (as far as I can see) for the testing and validation plugins (I haven't put that in place yet in my builds but I am doing it today). Now I am trying to think ahead from a design perspective (bare with me):

- You need some way to perform tests on that container. (In my case I will for example connect and answer echo commands for a custom network stack that was built by jenkins in the previous step). In this case the container requires to be accessible from the outside at each build, successfully issue echo requests, then successfully answer echo requests; Else the build is marked as failed. In this case, the docker-plugin either need :
   - a way to declare a fixed port that somewhat allow you to limit the concurrent builds for this image per host to 1 (For example a check-box option that appears next to the "bind ports" box and says `limit image/host limit to 1 : [x]`). 
   - OR for the plugin to bind all exposed container ports to random host ports on container startup. Then catch these values in the ENV, and expose them to the Jenkins Job. (Assuming Bash 4, the environment shoud show something like `DP_PORTS=( ["1234"]="60342" ["22"]="53424")` so that I can do something like `echo "${DP_PORTS["1234"]}"` to access the binding and use it in my subsequent steps.

I am not sure this is the way to go but I would go for option 2 because the first one does not scale.

Right now I am going to work on putting in place my testing framework and will see where that brings me with respect to this design issue.

**Comment by ndeloof** [comment]
Why do you configure such a fixed port binding ? Just let docker assign a random one to avoid resource conflicts.
Please reopen this issue if you feel there's a valid use-case for this.
