### ISSUE TITLE
SSH launcher failing for unknown reason

### ISSUE THREAD

**Issue by fboudra** [jenkinsci/docker-plugin#380]
Hi,

When a build job is triggered, a container is provisioned as expected. However, the build job still waiting for the node to be online.

`
Feb 12, 2016 10:34:00 AM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
Asked to provision 1 slave(s) for: docker-utopic
Feb 12, 2016 10:34:00 AM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
Will provision 'test/utopic-amd64', for label: 'docker-utopic', in cloud: 'docker_cloud'
Feb 12, 2016 10:34:00 AM INFO com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
Not Provisioning 'test/utopic-amd64'; Server 'docker_cloud' full with '1' container(s)
`

As we can see, the plugin isn't provisioning because one container has already been started.

`
Feb 12, 2016 10:34:00 AM WARNING hudson.slaves.NodeProvisioner$2 run
Provisioned slave Image of test/utopic-amd64 failed to launch
java.lang.NullPointerException
    at com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher.getAddressForSSHD(DockerComputerSSHLauncher.java:126)
    at com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher.waitUp(DockerComputerSSHLauncher.java:79)
    at com.nirima.jenkins.plugins.docker.DockerCloud.provisionWithWait(DockerCloud.java:393)
    at com.nirima.jenkins.plugins.docker.DockerCloud.access$000(DockerCloud.java:57)
    at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:242)
    at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:239)
    at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
`

If I attach the container, I see ssh running as expected. And if I try to login with ssh localhost, it works as expected. Looks like the ssh credentials are properly set up.

Any ideas what's going on?
- Jenkins v1.642.1
- Docker 1.10.1
- Docker plugin 0.16.0

**Comment by fboudra** [comment]
It seems related to my image *don't* expose port 22. Previously, it worked just fine, so I suspect a behavior change maybe with docker 1.10.1 ...

**Comment by KostyaSha** [comment]
@fboudra try JNLP launcher.

**Comment by grimpy** [comment]
I am having same issue jnlp doenst seem to work for me.
Always end up with
```
Starting connection command for 926476e4362a494b8ac94eec2929a42f68021d43865f6a47982507196443aa5a
Successfully executed jnlp connection for 926476e4362a494b8ac94eec2929a42f68021d43865f6a47982507196443aa5a
Waiting slave connection...
```

**Comment by changsijay** [comment]
I see the log message in jenkins.log(I am running docker v1.12)

```
WARNING: Provisioned agent Image of evarga/jenkins-slave failed to launch
com.github.dockerjava.api.BadRequestException: {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}
```

**Comment by ndeloof** [comment]
This should be fixed now, please reopen if you still see this issue with latest release
