### ISSUE TITLE
Cannot change the username/password 

### ISSUE THREAD

**Issue by alexpenev-s** [jenkinsci/docker-plugin#391]
Hello,
When I try to change the username/password in the UI. The UI shows that the newly selected username and password are used. However when I run a job I notice that the old username & password are used.

I see the following error whenever I try to add a new user/password in the UI:

Apr 18, 2016 8:59:53 AM hudson.model.Descriptor$NewInstanceBindInterceptor instantiate
WARNING: falling back to default instantiation com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy {"stapler-class":"com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy","idleMinutes":"10"}
java.lang.NullPointerException
    at hudson.model.Descriptor$NewInstanceBindInterceptor.instantiate(Descriptor.java:643)
    at org.kohsuke.stapler.RequestImpl.instantiate(RequestImpl.java:675)
    at org.kohsuke.stapler.RequestImpl.access$200(RequestImpl.java:81)
    at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:600)
    at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:404)
    at org.kohsuke.stapler.RequestImpl.injectSetters(RequestImpl.java:764)
    at org.kohsuke.stapler.RequestImpl.instantiate(RequestImpl.java:703)
    at org.kohsuke.stapler.RequestImpl.access$200(RequestImpl.java:81)
    at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:600)
    at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:404)
    at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:400)
    at hudson.model.Descriptor.newInstance(Descriptor.java:588)
    at hudson.model.Descriptor$NewInstanceBindInterceptor.onConvert(Descriptor.java:663)
    at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:543)
    at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:638)
    at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:404)
    at org.kohsuke.stapler.RequestImpl.instantiate(RequestImpl.java:697)
    at org.kohsuke.stapler.RequestImpl.access$200(RequestImpl.java:81)
    at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:600)
    at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:404)
    at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:400)
    at hudson.model.Descriptor.newInstance(Descriptor.java:588)
    at hudson.model.Descriptor.newInstancesFromHeteroList(Descriptor.java:1034)
    at hudson.model.Descriptor.newInstancesFromHeteroList(Descriptor.java:996)
    at hudson.util.DescribableList.rebuildHetero(DescribableList.java:208)
    at jenkins.model.GlobalCloudConfiguration.configure(GlobalCloudConfiguration.java:23)
    at jenkins.model.Jenkins.configureDescriptor(Jenkins.java:2965)
    at jenkins.model.Jenkins.doConfigSubmit(Jenkins.java:2928)
    at sun.reflect.GeneratedMethodAccessor622.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:298)
    at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:161)
    at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:96)
    at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:121)
    at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
    at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
    at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
    at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)

**Comment by gclayburg** [comment]
I'm getting this same error when using the docker-plugin. I am using:
Jenkins 1.651.3
docker-plugin 0.16.0

What is odd is that when you bring up the config screen (Jenkins->Manage Jenkins->Configure System->Cloud->Images) it shows the correct credentials that were saved earlier.  In fact, you can change the credentials on that screen, but when you save the form, this NPE occurs.  If you come back to this config screen, the credentials look correct. However, if you try to launch the slave agent again, you can see that it uses the wrong credentialid.

**Comment by gclayburg** [comment]
Update: the NPE looks suspicious, but it may be a red herring.  I was able to work around this issue by first stopping the docker container that was launched.  Apparently, the docker-plugin does not bother to get updated settings like ssh credentials for launching the slave after the docker image has been started.   

Obviously, the usability of this plugin could be improved.

**Comment by ndeloof** [comment]
This issue should be fixed in 0.17+ with adoption of docker-commons for credentials
