### ISSUE TITLE
"HostConfig at API container start" is removed from Docker 1.12

### ISSUE THREAD

**Issue by MansM** [jenkinsci/docker-plugin#403]
jenkins | SEVERE: Error in provisioning; template='DockerTemplate{configVersion=2, labelString='buildslave-centos6', launcher=com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher@785ec7f5, remoteFsMapping='', remoteFs='/home/jenkins', instanceCap=1, mode=NORMAL, retentionStrategy=com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy@38f86c7b, numExecutors=1, dockerTemplateBase=DockerTemplateBase
{image=buildslave-centos6}
, removeVolumes=false, pullStrategy=PULL_LATEST}' for cloud='docker'
jenkins | com.github.dockerjava.api.BadRequestException:
{"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}
at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:123)
jenkins | at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
jenkins | at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:251)
jenkins | at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:667)
jenkins | at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:664)
jenkins | at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
jenkins | at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
jenkins | at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
jenkins | at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
jenkins | at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:664)
jenkins | at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:424)
jenkins | at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:333)
jenkins | at com.github.dockerjava.jaxrs.StartContainerCmdExec.execute(StartContainerCmdExec.java:28)
jenkins | at com.github.dockerjava.jaxrs.StartContainerCmdExec.execute(StartContainerCmdExec.java:13)
jenkins | at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:24)
jenkins | at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:33)
jenkins | at com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:53)
jenkins | at com.nirima.jenkins.plugins.docker.DockerCloud.runContainer(DockerCloud.java:288)
jenkins | at com.nirima.jenkins.plugins.docker.DockerCloud.provisionWithWait(DockerCloud.java:366)
jenkins | at com.nirima.jenkins.plugins.docker.DockerCloud.access$000(DockerCloud.java:57)
jenkins | at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:242)
jenkins | at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:239)
jenkins | at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
jenkins | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
jenkins | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
jenkins | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
jenkins | at java.lang.Thread.run(Thread.java:745)
jenkins |
jenkins | Jun 19, 2016 7:47:37 PM com.nirima.jenkins.plugins.docker.DockerCloud provision

**Comment by KostyaSha** [comment]
I know, that's ne 1.12 API, i will release small fix that will allow using current code with 1.12 daemon.

**Comment by KostyaSha** [comment]
Wrong plugin, sorry

**Comment by glennmcallister** [comment]
I've been bit by this as well. Are there any known workarounds for Docker 1.12?

**Comment by glennmcallister** [comment]
Looks like the root cause is this issue in the upstream docker-java project - docker-java/docker-java#619

**Comment by lattwood** [comment]
@glennmcallister any idea how one would go about making that change and recompiling themselves, or where the change could be made?

**Comment by KostyaSha** [comment]
> Looks like the root cause is this issue in the upstream docker-java project - docker-java/docker-java#619

There is no issues in docker-java. That thread only about layered API, not about unreleased 1.12 compatibility.

We had a lot of confusion in docker-plugin with wrong api versions that people placed in configuration and that's why removed it. Restore this configuration in unmaintained docker-plugin or try https://github.com/KostyaSha/yet-another-docker-plugin . Good luck.

**Comment by glennmcallister** [comment]
Yeah, I moved onto using yet-another-docker-plugin, and things are working for me now, much as @MansM apparently did.

**Comment by Kras4ooo** [comment]
I have the same issue

**Comment by jommgoncalves** [comment]
Which is expected to solve this major problem?

**Comment by KostyaSha** [comment]
> There is a workaround to solve the problem without using another plugin?

Pull request change, take maintainership, try reach Nigel.

**Comment by okram999** [comment]
freed up some hours to test the docker with Jenkins and ended here :(



Aug 23, 2016 10:33:55 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
INFO: Asked to provision 1 slave(s) for: docker-jenkins
Aug 23, 2016 10:33:55 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
INFO: Will provision 'jenkins-everga', for label: 'docker-jenkins', in cloud: 'docker-jenkins'
Aug 23, 2016 10:33:55 PM com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
INFO: Provisioning 'jenkins-everga' number '0' on 'docker-jenkins'; Total containers: '0'
Aug 23, 2016 10:33:55 PM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
INFO: Started provisioning Image of jenkins-everga from docker-jenkins with 1 executors. Remaining excess workload: 0
Aug 23, 2016 10:33:55 PM com.nirima.jenkins.plugins.docker.DockerCloud provisionWithWait
INFO: Trying to run container for jenkins-everga
Aug 23, 2016 10:33:55 PM com.nirima.jenkins.plugins.docker.DockerCloud$1 call
SEVERE: Error in provisioning; template='DockerTemplate{configVersion=2, labelString='docker-jenkins', launcher=com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher@45a2f4b2, remoteFsMapping='', remoteFs='/home/jenkins', instanceCap=1, mode=NORMAL, retentionStrategy=com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy@2fcd9aaa, numExecutors=1, dockerTemplateBase=DockerTemplateBase{image=jenkins-everga}, removeVolumes=false, pullStrategy=PULL_LATEST}' for cloud='docker-jenkins'
com.github.dockerjava.api.BadRequestException: {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}

        at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:43)
        at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:134)
        at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:123)
        at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:251)
        at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:667)
        at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:664)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:664)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:424)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:333)
        at com.github.dockerjava.jaxrs.StartContainerCmdExec.execute(StartContainerCmdExec.java:28)
        at com.github.dockerjava.jaxrs.StartContainerCmdExec.execute(StartContainerCmdExec.java:13)
        at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23)
        at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:33)
        at com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:53)
        at com.nirima.jenkins.plugins.docker.DockerCloud.runContainer(DockerCloud.java:294)
        at com.nirima.jenkins.plugins.docker.DockerCloud.provisionWithWait(DockerCloud.java:372)
        at com.nirima.jenkins.plugins.docker.DockerCloud.access$000(DockerCloud.java:58)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:248)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:245)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by KostyaSha** [comment]
> There is no issues in docker-java. That thread only about layered API, not about unreleased 1.12 compatibility.

Btw, i mistaken here, but was, but also docker daemon responded wrong message that makes me think such. Everything was fixed, docker will release in some version.

**Comment by okram999** [comment]
@KostyaSha are you suggesting to use this https://github.com/KostyaSha/yet-another-docker-plugin instead?

**Comment by KostyaSha** [comment]
@okram999 you can use anything that will work for you (for example it have no control commands atm (WIP)). I left maintainership (imho latest commits into master proves it more), but still subscribed to notifications for this plugin. Fixed, unsubscribed, wouldn't suggest anymore. Obviously somebody should take mainteinership https://github.com/jenkinsci/docker-plugin/graphs/contributors , but good luck to cooperate with plugin author =)

**Comment by magnayn** [comment]
Are you building against the master ?

You can adjust which API you communicate with the back-end again, which may
help.


On Tue, Aug 23, 2016 at 11:40 PM, niristotle okram <notifications@github.com

**Comment by hannesdejager** [comment]
Have the same issue. We've been using this plug-in for production builds for almost a year now and all was working fine until I setup a new host with docker 1.12. When I point the plugin back to the old host with docker 1.10 all works fine. Point to the docker 1.12 host and it breaks:

>SEVERE: Error in provisioning; template='DockerTemplate{configVersion=2, labelString='docker-java-8-maven', launcher=com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher@367de0d, remoteFsMapping='', remoteFs='/home/jenkins', instanceCap=5, mode=EXCLUSIVE, retentionStrategy=com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy@2c67ab37, numExecutors=1, dockerTemplateBase=DockerTemplateBase{image=dockerhub.entersect.co.za/jenkins/java8-mvn:latest}, removeVolumes=true, pullStrategy=PULL_NEVER}' for cloud='Jenkins Docker Slaves Host'
com.github.dockerjava.api.BadRequestException: {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}

and

>Aug 29, 2016 11:50:27 PM hudson.slaves.NodeProvisioner$2 run
WARNING: Provisioned agent Image of dockerhub.entersect.co.za/jenkins/java8-mvn:latest failed to launch
com.github.dockerjava.api.BadRequestException: {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}

>	at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:43)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:134)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:123)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:251)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:667)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:664)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:664)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:424)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:333)
	at com.github.dockerjava.jaxrs.StartContainerCmdExec.execute(StartContainerCmdExec.java:28)
	at com.github.dockerjava.jaxrs.StartContainerCmdExec.execute(StartContainerCmdExec.java:13)
	at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:33)
	at com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:53)
	at com.nirima.jenkins.plugins.docker.DockerCloud.runContainer(DockerCloud.java:294)
	at com.nirima.jenkins.plugins.docker.DockerCloud.provisionWithWait(DockerCloud.java:372)
	at com.nirima.jenkins.plugins.docker.DockerCloud.access$000(DockerCloud.java:58)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:248)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:245)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)

**Comment by ndeloof** [comment]
can't reproduce. 
I assume wrong api version is being used.
