### ISSUE TITLE
Cloning repository call git.exe

### ISSUE THREAD

**Issue by Liryna** [jenkinsci/docker-plugin#42]
Hi,

My Master is a Windows and slave who host the containers is on debian.

I have try evarga/jenkins-slave container and my own. Each times I have this error:
(I have install git on both and commit)

```
Cloning repository git@***:***
 > git.exe init /home/jenkins
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Could not init /home/jenkins
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$4.execute(CliGitAPIImpl.java:476)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:379)
    at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:153)
    at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:146)
    at hudson.remoting.UserRequest.perform(UserRequest.java:118)
    at hudson.remoting.UserRequest.perform(UserRequest.java:48)
    at hudson.remoting.Request$2.run(Request.java:328)
    at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
Caused by: hudson.plugins.git.GitException: Error performing command: git.exe init /home/jenkins
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1332)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1301)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1297)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1084)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$4.execute(CliGitAPIImpl.java:474)
    ... 12 more
Caused by: java.io.IOException: Cannot run program "git.exe" (in directory "/home/jenkins"): error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
    at hudson.Proc$LocalProc.<init>(Proc.java:244)
    at hudson.Proc$LocalProc.<init>(Proc.java:216)
    at hudson.Launcher$LocalLauncher.launch(Launcher.java:775)
    at hudson.Launcher$ProcStarter.start(Launcher.java:355)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1321)
    ... 16 more
Caused by: java.io.IOException: error=2, No such file or directory
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:135)
    at java.lang.ProcessImpl.start(ProcessImpl.java:130)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1021)
    ... 21 more
ERROR: null

```

Otherwise I have no problem if I select directly the slave debian.

Does someones have a idea about it ?

I use version 0.6.2.

**Comment by dungnt081191** [comment]
in the same issue like @Liryna

**Comment by saipavan9** [comment]
What is the solution to this issue??

**Comment by Liryna** [comment]
Sorry that was a while ago I cannot remember.

**Comment by thomassuckow** [comment]
@saipavan9 You need to change the settings for git in the Jenkins Global Tool Configuration.

Assuming you have jenkins installed on windows, add another configuration for git without .exe and then choose it in your Job that uses docker.
