### ISSUE TITLE
Is it possible to have slaves behind an ELB?

### ISSUE THREAD

**Issue by farahfa** [jenkinsci/docker-plugin#428]
Hello,

BTW: When I say "Slaves" in this post, I really mean "Docker Clouds"

Is there a way to put multiple slaves behind a load balancer and get it to work?

Because currently (even though "Test Connection" button works as expected).. When I try to run a job it just hangs there trying to find executor forever.. 

And I noticed that I get the following error:

```
[08/23/16 20:18:39] [SSH] Opening SSH connection to slaves.test.jenkins.company.com:32772.
Connection refused
SSH Connection failed with IOException: "Connection refused".
java.io.IOException: There was a problem while connecting to slaves.test.jenkins.company.com:32772
	at com.trilead.ssh2.Connection.connect(Connection.java:818)
	at com.trilead.ssh2.Connection.connect(Connection.java:687)
	at com.trilead.ssh2.Connection.connect(Connection.java:587)
	at hudson.plugins.sshslaves.SSHLauncher.openConnection(SSHLauncher.java:1185)
	at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:711)
	at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:706)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at com.trilead.ssh2.transport.TransportManager.establishConnection(TransportManager.java:354)
	at com.trilead.ssh2.transport.TransportManager.initialize(TransportManager.java:467)
	at com.trilead.ssh2.Connection.connect(Connection.java:758)
	... 9 more
[08/23/16 20:18:39] Launch failed - cleaning up connection
[08/23/16 20:18:39] [SSH] Connection closed.
```

I understand that the `32772` port is a random port, which is why this is happening.. But I just wanted to see if there's some kind of work-around or perhaps maybe add support to such thing? The reason why I want to put slaves behind a load balancer is well to balance the load on the different slaves and also have a proper fail-over plan (in case one of those slaves goes down)..

**Comment by farahfa** [comment]
@KostyaSha, do you think this is something that's feasible?

**Comment by KostyaSha** [comment]
If i right understand what you asked.

First of all for SshLauncher container must expose some port and jenkins must connect to the same slave as it started (it extracts this port). If you mean balance incoming ssh port between many containers, then you can't, because jenkins will get into unexpected container and slave itself already "balancing" load by running container per build. 

Secondary (from my yad-docs):
```
Jenkins slaves connection:
 - JNLP (requires working access from slave to master)
 - SSH (requires working access from master to slave)
```
You don't need at all balancer. Just allow jenkins connect to daemon, spin slaves and connect with launcher.

**Comment by KostyaSha** [comment]
If you want balance, then better use swarm client on top of docker daemons.

**Comment by KostyaSha** [comment]
Or at all in AWS there is container service, that would be better solution for scaling.

**Comment by farahfa** [comment]
Thanks for the information @KostyaSha.. :)
