### ISSUE TITLE
Failed to run container: com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher

### ISSUE THREAD

**Issue by shakedlokits** [jenkinsci/docker-plugin#432]
I am attempting to provision the evarga/jenkins-slave container and I am receiving the following exception:  
`falling back to default instantiation com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher {"stapler-class":"com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher","sshConnector":{"credentialsId":"204d76b9-3e23-4759-ae4e-ef0b6356ae6f","port":"22","javaPath":"","jvmOptions":"","prefixStartSlaveCmd":"","suffixStartSlaveCmd":"","launchTimeoutSeconds":"","maxNumRetries":"0","retryWaitTime":"0"}}
java.lang.NullPointerException
    at hudson.model.Descriptor$NewInstanceBindInterceptor.instantiate(Descriptor.java:641)
    at org.kohsuke.stapler.RequestImpl.instantiate(RequestImpl.java:749)
    at org.kohsuke.stapler.RequestImpl.access$200(RequestImpl.java:83)
    at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:674)
    at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:478)
    at org.kohsuke.stapler.RequestImpl.injectSetters(RequestImpl.java:827)
    at org.kohsuke.stapler.RequestImpl.instantiate(RequestImpl.java:777)
    at org.kohsuke.stapler.RequestImpl.access$200(RequestImpl.java:83)
    at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:674)
    at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:478)
    at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:474)
    at hudson.model.Descriptor.newInstance(Descriptor.java:590)
    at hudson.model.Descriptor$NewInstanceBindInterceptor.onConvert(Descriptor.java:661)
    at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:617)
    at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:712)
    at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:478)
    at org.kohsuke.stapler.RequestImpl.instantiate(RequestImpl.java:771)
    at org.kohsuke.stapler.RequestImpl.access$200(RequestImpl.java:83)
    at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:674)
    at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:478)
    at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:474)
    at hudson.model.Descriptor.newInstance(Descriptor.java:590)
    at hudson.model.Descriptor.newInstancesFromHeteroList(Descriptor.java:1043)
    at hudson.model.Descriptor.newInstancesFromHeteroList(Descriptor.java:1005)
    at hudson.util.DescribableList.rebuildHetero(DescribableList.java:208)
    at jenkins.model.GlobalCloudConfiguration.configure(GlobalCloudConfiguration.java:24)
    at jenkins.model.Jenkins.configureDescriptor(Jenkins.java:3531)
    at jenkins.model.Jenkins.doConfigSubmit(Jenkins.java:3494)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:324)
    at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:167)
    at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:100)
    at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:124)
    at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
    at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
    at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
    at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
    at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
    at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:135)
    at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:126)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
    at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:49)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
    at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
    at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
    at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
    at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
    at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:553)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at org.eclipse.jetty.server.Server.handle(Server.java:499)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
    at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)`

**My Build:**  
Jenkins Master: 2.20  
Docker Plugin: 0.16.1  
Docker Host: 4.6.7-200.fc23.x86_64  
Docker: 1.10.3, build 20f81dd  

**Daemon Options:**  
`ExecStart=/usr/bin/docker daemon --selinux-enabled -H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock`  

**Jenkins Settings:**  
![Docker-Plugin Settings](http://i.imgur.com/4IvUnhB.png)  
![Image Settings](http://i.imgur.com/eE2MM1L.png)

**Additional Information:**  
- I pass the docker plugin connection test
- **My docker daemon status:**

`[fedora@slokits-docker ~]$ sudo systemctl status -l docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2016-09-01 14:17:12 UTC; 1h 18min ago
     Docs: https://docs.docker.com
 Main PID: 401 (docker)
   CGroup: /system.slice/docker.service
           └─401 /usr/bin/docker daemon --selinux-enabled -H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock
Sep 01 14:21:14 slokits-docker.localdomain docker[401]: time="2016-09-01T14:21:14.397646570Z" level=warning msg="failed to cleanup ipc mounts:\nfailed to umount /var/lib/docker/containers/db164bb02d6aa32305f39893ef09d05615bb5c47d0aae84c07974a55a0981359/shm: invalid argument"
Sep 01 14:21:14 slokits-docker.localdomain docker[401]: time="2016-09-01T14:21:14.397663392Z" level=error msg="Error unmounting container db164bb02d6aa32305f39893ef09d05615bb5c47d0aae84c07974a55a0981359: not mounted"
Sep 01 14:21:45 slokits-docker.localdomain docker[401]: time="2016-09-01T14:21:45.819418815Z" level=warning msg="exit status 1"
Sep 01 14:21:45 slokits-docker.localdomain docker[401]: time="2016-09-01T14:21:45.942241135Z" level=error msg="error locating sandbox id e2f5ab3f1130c5ca4c52f719bec6e27217470026f9722e7b9c98847886aa43b3: sandbox e2f5ab3f1130c5ca4c52f719bec6e27217470026f9722e7b9c98847886aa43b3 not found"
Sep 01 14:21:45 slokits-docker.localdomain docker[401]: time="2016-09-01T14:21:45.942280531Z" level=warning msg="failed to cleanup ipc mounts:\nfailed to umount /var/lib/docker/containers/72edf4fb475c2155f03ecd01f939bf21dd5fba98be12720e43aeb72bf0de3144/shm: invalid argument"
Sep 01 14:21:45 slokits-docker.localdomain docker[401]: time="2016-09-01T14:21:45.942299553Z" level=error msg="Error unmounting container 72edf4fb475c2155f03ecd01f939bf21dd5fba98be12720e43aeb72bf0de3144: not mounted"
Sep 01 14:22:06 slokits-docker.localdomain docker[401]: time="2016-09-01T14:22:06.511426827Z" level=warning msg="exit status 1"
Sep 01 14:22:06 slokits-docker.localdomain docker[401]: time="2016-09-01T14:22:06.636471849Z" level=error msg="error locating sandbox id 8e38023979539dd2887848e526013062546faa55eab55a0d0addcd4eb21c3930: sandbox 8e38023979539dd2887848e526013062546faa55eab55a0d0addcd4eb21c3930 not found"
Sep 01 14:22:06 slokits-docker.localdomain docker[401]: time="2016-09-01T14:22:06.636527704Z" level=warning msg="failed to cleanup ipc mounts:\nfailed to umount /var/lib/docker/containers/df31f75214975c7e9b3fe0cb56d1634a7a084dc07fa67806a52ff31dd4334172/shm: invalid argument"
Sep 01 14:22:06 slokits-docker.localdomain docker[401]: time="2016-09-01T14:22:06.636541873Z" level=error msg="Error unmounting container df31f75214975c7e9b3fe0cb56d1634a7a084dc07fa67806a52ff31dd4334172: not mounted"`

**Comment by ndeloof** [comment]
please try 0.17 and reopen if this issue persists
