### ISSUE TITLE
The read/connect timeouts default to zero - which is potentially bad

### ISSUE THREAD

**Issue by fraz3alpha** [jenkinsci/docker-plugin#445]
I'm using the latest version of the plugin, version v0.16.2 .

I was running against a Docker Swarm endpoint when I observed this particular problem

I observed that Jenkins stopped processing work, and a container that was being terminated did not appear to be progressing with that task. Taking a stack trace using jstack I saw the following reference to _terminate()

```
"Computer.threadPoolForRemoting [#216]" #4966 daemon prio=5 os_prio=0 tid=0x00007fd2d0e25000 nid=0x2d17 runnable [0x00007fd2c8e8c000]
   java.lang.Thread.State: RUNNABLE
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
    at java.net.SocketInputStream.read(SocketInputStream.java:170)
    at java.net.SocketInputStream.read(SocketInputStream.java:141)
    at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
    at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
    at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
    at org.apache.http.impl.io.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:129)
    at org.apache.http.impl.io.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:53)
    at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
    at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
    at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
    at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
    at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
    at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:435)
    at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
    at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
    at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
    at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)
    at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:437)
    at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:343)
    at com.github.dockerjava.jaxrs.StopContainerCmdExec.execute(StopContainerCmdExec.java:31)
    at com.github.dockerjava.jaxrs.StopContainerCmdExec.execute(StopContainerCmdExec.java:12)
    at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23)
    at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
    at com.github.dockerjava.core.command.StopContainerCmdImpl.exec(StopContainerCmdImpl.java:63)
    at com.nirima.jenkins.plugins.docker.DockerSlave._terminate(DockerSlave.java:168)
    at hudson.slaves.AbstractCloudSlave.terminate(AbstractCloudSlave.java:67)
    at com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy$1$1.run(DockerOnceRetentionStrategy.java:112)
    at hudson.model.Queue._withLock(Queue.java:1315)
    at hudson.model.Queue.withLock(Queue.java:1192)
    at com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy$1.run(DockerOnceRetentionStrategy.java:106)
    at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

This was present in two invocations of jstack 7 minutes apart

```
Result: 2016-09-28 07:47:54
Full thread dump OpenJDK 64-Bit Server VM (25.91-b14 mixed mode): 
```

&

```
Result: 2016-09-28 07:55:50
Full thread dump OpenJDK 64-Bit Server VM (25.91-b14 mixed mode):
```

In particular it seems that having called the QueueLock() method, we are now blocking Jenkins from doing normal work. It could be the case that this is the underlying docker-java library not setting / providing a way to set a timeout - or it is just too large, but either way, this is detrimental to the operation of the server as a whole.

I don't know whether or not this affects all docker-java method calls that call out via HTTP, or because this particular one happens to take a lock that it then doesn't release it

I have only seen this once so far, but it seemed to have a bad enough effect to bring it up

**Comment by fraz3alpha** [comment]
I've also seen this again today, with a slightly different appearance, but the net result is the same - Jenkins is being blocked as a lock is not being released:

```
"jenkins.util.Timer [#10]" #66 daemon prio=5 os_prio=0 tid=0x0000000000a72000 nid=0x12d runnable [0x00007eff92bd6000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
	at org.apache.http.impl.io.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:129)
	at org.apache.http.impl.io.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:53)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:435)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
	at org.glassfish.jersey.client.JerseyInvocation$3.call(JerseyInvocation.java:724)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:720)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:430)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:321)
	at com.github.dockerjava.jaxrs.ListContainersCmdExec.execute(ListContainersCmdExec.java:47)
	at com.github.dockerjava.jaxrs.ListContainersCmdExec.execute(ListContainersCmdExec.java:19)
	at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at com.nirima.jenkins.plugins.docker.DockerCloud.countCurrentDockerSlaves(DockerCloud.java:551)
	at com.nirima.jenkins.plugins.docker.DockerCloud.addProvisionedSlave(DockerCloud.java:575)
	- eliminated <0x0000000086995a88> (a com.nirima.jenkins.plugins.docker.DockerCloud)
	at com.nirima.jenkins.plugins.docker.DockerCloud.provision(DockerCloud.java:245)
	- locked <0x0000000086995a88> (a com.nirima.jenkins.plugins.docker.DockerCloud)
	at hudson.slaves.NodeProvisioner$StandardStrategyImpl.apply(NodeProvisioner.java:701)
	at hudson.slaves.NodeProvisioner.update(NodeProvisioner.java:307)
	at hudson.slaves.NodeProvisioner.access$000(NodeProvisioner.java:60)
	at hudson.slaves.NodeProvisioner$NodeProvisionerInvoker.doRun(NodeProvisioner.java:798)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
This has led to a number of other threads blocked waiting on the DockerCloud lock, e.g.:
```
"Computer.threadPoolForRemoting [#1756]" #78039 daemon prio=5 os_prio=0 tid=0x0000000001789000 nid=0x5ce2 waiting for monitor entry [0x00007eff8b476000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at com.nirima.jenkins.plugins.docker.DockerCloud.getClient(DockerCloud.java:196)
	- waiting to lock <0x0000000086995a88> (a com.nirima.jenkins.plugins.docker.DockerCloud)
	at com.nirima.jenkins.plugins.docker.DockerCloud.pullImage(DockerCloud.java:341)
	at com.nirima.jenkins.plugins.docker.DockerCloud.provisionWithWait(DockerCloud.java:391)
	at com.nirima.jenkins.plugins.docker.DockerCloud.access$000(DockerCloud.java:64)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:261)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:258)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I think I might have tracked down the route cause in my particular infrastructure. It seems that the address of the target API host was temporarily not being routed correctly, and the connection appeared to hang, so when it came back to full health a little later it hasn't resent or otherwise done the right thing, resulting in the socketRead blocking.

It looks like we need to try and make sure that calls to the API, i.e. external to the Jenkins host (and potentially much beyond our control) are properly guarded against, including ensuring there are appropriate timeouts set

**Comment by fraz3alpha** [comment]
OK, so I'm going to look like a right fool now, because somehow the read / connection timeouts were set (back?) to 0, which is an infinite timeout - if that is the default, we should surely think about at least setting it to a finite number so as not to break Jenkins for, say, a whole weekend whilst no-one is around looking after it. Is there ever a reason we would want an infinite timeout?

**Comment by magnayn** [comment]
FWIW, there is both a connect and a read timeout specifiable at the cloud
level (see e.g DockerCmdExecConfigBuilderForPlugin).

If you have those set, and they're not being obeyed, it's likely a bug for
docker-java..

**Comment by magnayn** [comment]
That'll teach me to read via gmail and not on github.

I think this is a victim of changing API. It used to be the case that timeouts were set at a connection level (and it did a "only set timeouts if value > 0"). 

This changed in docker-java to be on the command factory level - and forced a value (albeit as an Integer, so I'm not sure what passing null would be, but I suspect that would be a reasonable default).

Yes, making the default to be infinite is a bit insane but not what was intended. I guess best route out would be

- allow plugin values to be Integers (not int) so to allow 'not specified' to be some sensible default (and not infinity).

**Comment by fraz3alpha** [comment]
Sounds reasonable to me, although since I've saved the configuration after the more recentl plugin updates, I guess I've got an actual zero in my config now, so I wouldn't get the new default.

I'm not sure how helpful the plugin can be to the users who now have 0 in there, as it could actually have been a legitimate conscious choice (although not necessarily sensible) or by mistake, and we can't differentiate between them after the fact,

I'm not sure when this change happened, but it has caused me to go and check all my servers to make sure I've got a sensible (>0) value specified

**Comment by PierreBtz** [comment]
I also came into this issue. Maybe a simple warning in the tooltip:

'Timeout for opening connection to Docker API. 0 is infinity.'
-> 'Timeout for opening connection to Docker API. 0 is infinity. Be careful as infinity can block the whole Jenkins Queue if the connection hangs.'

Also, maybe, 0 should not be the default value, as it seems more like something a user would want to do on purpose.

**Comment by ndeloof** [comment]
0.17 does not invoke docker API while owning Queue Lock.
