### ISSUE TITLE
Long running tasks without output causes build to get stuck

### ISSUE THREAD

**Issue by jstarcher** [jenkinsci/docker-plugin#475]
Actual:
Jenkins job that uses fabric to run an indexing command which takes several minutes to complete and does not have any output until finished causes build to get stuck and never finishes even after the fabric script finishes on the destination node.

Expected:
Jenkins job that uses fabric to run an indexing command which takes several minutes to complete and does not have any output until finished should not get stuck.

Plugin version: 0.16.2

Docker info:
```
Containers: 10
 Running: 9
 Paused: 0
 Stopped: 1
Images: 21
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 136
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: n8groekak3pju1jqjc2uvph4v
 Is Manager: true
 ClusterID: dm96j4qo4h9zdnj8kdeheb01q
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.0.100
 Manager Addresses:
  192.168.0.100:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-59-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.42 GiB
Name: ubuntu
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

Only thing relevant in the jenkins job:
```
Feb 11, 2017 3:24:02 AM INFO hudson.model.Run execute
MPJ Update Index #11 aborted
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at hudson.remoting.Request.call(Request.java:147)
	at hudson.remoting.Channel.call(Channel.java:821)
	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:256)
	at com.sun.proxy.$Proxy95.join(Unknown Source)
	at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:1029)
	at hudson.tasks.CommandInterpreter.join(CommandInterpreter.java:154)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:108)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:65)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1728)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
```

**Comment by raolivei** [comment]
Container is built.
Container is running.
container cmd prompt window: running a *.bat inside the container's C:\ (NOT the container's host C:\).
Bat starts running with lots of command lines and get stuck forever.

Could this issue be that container process got killed? How do I check? Thanks.

**Comment by ndeloof** [comment]
I'm running a job with a single shell step `sleep 1000` without any issue, so wonder what could be specific to your setup that would break. Can you please try to reduce the scope to something I can reproduce ?

**Comment by pjdarton** [comment]
Closing due to lack of response
