### ISSUE TITLE
Server didn't accept the handshake

### ISSUE THREAD

**Issue by weiguang1017** [jenkinsci/docker-plugin#490]
Docker plugin:0.16.2
Jenkins ver. 2.32.2
jenkins-system----config   Launch method:(Experimental)Docker JNLP launcher

May 02, 2017 11:23:06 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Locating server among [http://l-portalfd1.cm.beta.cn0.qunar.com:8080/]
May 02, 2017 11:23:06 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Agent discovery successful
  Agent address: l-portalfd1.cm.beta.cn0.qunar.com
  Agent port:    50000
  Identity:      a1:b0:7b:2f:d1:c3:d8:e6:5f:ca:83:9a:c1:35:26:9f
May 02, 2017 11:23:06 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Handshaking
May 02, 2017 11:23:06 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to l-portalfd1.cm.beta.cn0.qunar.com:50000
May 02, 2017 11:23:06 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Server reports protocol JNLP4-connect not supported, skipping
May 02, 2017 11:23:06 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Server reports protocol JNLP4-plaintext not supported, skipping
May 02, 2017 11:23:06 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Trying protocol: JNLP3-connect
May 02, 2017 11:23:06 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Protocol JNLP3-connect encountered an unexpected exception
java.util.concurrent.ExecutionException: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: JNLP3-connect: Master rejected connection: 
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at hudson.remoting.Engine.innerRun(Engine.java:385)
	at hudson.remoting.Engine.run(Engine.java:287)
Caused by: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: JNLP3-connect: Master rejected connection: 
	at org.jenkinsci.remoting.engine.JnlpProtocol3Handler.sendHandshake(JnlpProtocol3Handler.java:239)
	at org.jenkinsci.remoting.engine.JnlpProtocol3Handler.sendHandshake(JnlpProtocol3Handler.java:123)
	at org.jenkinsci.remoting.engine.LegacyJnlpProtocolHandler$2.call(LegacyJnlpProtocolHandler.java:162)
	at org.jenkinsci.remoting.engine.LegacyJnlpProtocolHandler$2.call(LegacyJnlpProtocolHandler.java:158)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at hudson.remoting.Engine$1$1.run(Engine.java:94)
	at java.lang.Thread.run(Thread.java:744)

May 02, 2017 11:23:06 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to l-portalfd1.cm.beta.cn0.qunar.com:50000
May 02, 2017 11:23:06 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Trying protocol: JNLP2-connect
May 02, 2017 11:23:06 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Protocol JNLP2-connect encountered an unexpected exception
java.util.concurrent.ExecutionException: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: Server didn't accept the handshake: 
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at hudson.remoting.Engine.innerRun(Engine.java:385)
	at hudson.remoting.Engine.run(Engine.java:287)
Caused by: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: Server didn't accept the handshake: 
	at org.jenkinsci.remoting.engine.JnlpProtocol2Handler.sendHandshake(JnlpProtocol2Handler.java:134)
	at org.jenkinsci.remoting.engine.LegacyJnlpProtocolHandler$2.call(LegacyJnlpProtocolHandler.java:162)
	at org.jenkinsci.remoting.engine.LegacyJnlpProtocolHandler$2.call(LegacyJnlpProtocolHandler.java:158)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at hudson.remoting.Engine$1$1.run(Engine.java:94)
	at java.lang.Thread.run(Thread.java:744)

May 02, 2017 11:23:06 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to l-portalfd1.cm.beta.cn0.qunar.com:50000
May 02, 2017 11:23:06 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Trying protocol: JNLP-connect
May 02, 2017 11:23:06 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Protocol JNLP-connect encountered an unexpected exception
java.util.concurrent.ExecutionException: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: Server didn't accept the handshake: 
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at hudson.remoting.Engine.innerRun(Engine.java:385)
	at hudson.remoting.Engine.run(Engine.java:287)
Caused by: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: Server didn't accept the handshake: 
	at org.jenkinsci.remoting.engine.JnlpProtocol1Handler.sendHandshake(JnlpProtocol1Handler.java:121)
	at org.jenkinsci.remoting.engine.LegacyJnlpProtocolHandler$2.call(LegacyJnlpProtocolHandler.java:162)
	at org.jenkinsci.remoting.engine.LegacyJnlpProtocolHandler$2.call(LegacyJnlpProtocolHandler.java:158)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at hudson.remoting.Engine$1$1.run(Engine.java:94)
	at java.lang.Thread.run(Thread.java:744)

May 02, 2017 11:23:06 AM hudson.remoting.jnlp.Main$CuiListener error
SEVERE: The server rejected the connection: None of the protocols were accepted
java.lang.Exception: The server rejected the connection: None of the protocols were accepted
	at hudson.remoting.Engine.onConnectionRejected(Engine.java:484)
	at hudson.remoting.Engine.innerRun(Engine.java:448)
	at hudson.remoting.Engine.run(Engine.java:287)

**Comment by tiendungitd** [comment]
got same issue

**Comment by yunxingwang** [comment]
@weiguang1017 is there a resolution for the issue? it was closed.

**Comment by magicpds** [comment]
?,what's the resolution？
