### ISSUE TITLE
Exclude jersey-apache-connector from docker-java-shaded to fix "org.apache.http.conn.UnsupportedSchemeException: unix protocol is not supported"

### ISSUE THREAD

**Issue by erioness1125** [jenkinsci/docker-plugin#495]
### Jenkins
```
2.46.1
```

### Installed plugins
```
Ant Plugin 1.5
Authentication Tokens API Plugin 1.3		
Autofavorite for Blue Ocean 0.7		
Blue Ocean 1.0.1		
Blue Ocean Pipeline Editor 0.2.0		
BlueOcean Display URL plugin 2.0		
bouncycastle API Plugin 2.16.1		
Branch API Plugin 2.0.9		
CloudBees Docker Build and Publish plugin 1.3.2		
Cobertura Plugin 1.10		
Common API for Blue Ocean 1.0.1		
Config API for Blue Ocean 1.0.1		
Config File Provider Plugin 2.16.0		
Consul KV Builder 2.0.13		
Credentials Binding Plugin 1.11		
Credentials Plugin 2.1.13		
Custom View Tabs Plugin 1.3		
Dashboard for Blue Ocean 1.0.1		
Dashboard View 2.9.10		
Display URL API 2.0		
Docker Commons Plugin 1.6		
Docker Pipeline 1.11		
Docker plugin 0.16.2
Durable Task Plugin 1.13		
Environment Injector Plugin 2.1		
Events API for Blue Ocean 1.0.1		
External Monitor Job Type Plugin 1.7		
Favorite 2.1.0		
Folders Plugin 6.0.4		
Git client plugin 2.4.6		
Git Parameter Plug-In 0.8.0		
Git Pipeline for Blue Ocean 1.0.1		
Git plugin 3.3.0		
GIT server Plugin 1.7		
GitHub API Plugin 1.85.1		
GitHub Authentication plugin 0.27		
GitHub Branch Source Plugin 2.0.6		
GitHub Pipeline for Blue Ocean 1.0.1		
GitHub plugin 1.27.0		
Global Variable String Parameter 1.2		
Google Container Registry Auth Plugin 0.3		
Google OAuth Credentials plugin 0.5		
HTML Publisher plugin 1.13		
HTTP Request Plugin 1.8.19		
i18n for Blue Ocean 1.0.1		
Icon Shim Plugin 2.0.3		
Jackson 2 API Plugin 2.7.3		
Javadoc Plugin 1.4		
JavaScript GUI Lib: ACE Editor bundle plugin 1.1		
JavaScript GUI Lib: Handlebars bundle plugin 1.1.1		
JavaScript GUI Lib: jQuery bundles (jQuery and jQuery UI) plugin 1.2.1		
JavaScript GUI Lib: Moment.js bundle plugin 1.1.1		
Job DSL 1.63		
jQuery plugin 1.11.2-0		
JUnit Plugin 1.20		
JWT for Blue Ocean 1.0.1		
Kubernetes plugin 0.11		
LDAP Plugin 1.15		
Mailer Plugin 1.20		
Matrix Authorization Strategy Plugin 1.6		
Matrix Project Plugin 1.11		
Maven Integration plugin 2.15.1		
Metrics Plugin 3.1.2.10		
Nested View Plugin 1.14		
OAuth Credentials plugin 0.3		
OWASP Markup Formatter Plugin 1.5		
PAM Authentication plugin 1.3		
Permissive Script Security Plugin 0.1		
Personalization for Blue Ocean 1.0.1		
Pipeline 2.5		
Pipeline Graph Analysis Plugin 1.3		
Pipeline REST API for Blue Ocean 1.0.1		
Pipeline: API 2.16		
Pipeline: Basic Steps 2.5		
Pipeline: Build Step 2.5		
Pipeline: Declarative Agent API 1.1.1		
Pipeline: Declarative Extension Points API 1.1.4		
Pipeline: Groovy 2.33		
Pipeline: Input Step 2.7		
Pipeline: Job 2.11		
Pipeline: Milestone Step 1.3.1		
Pipeline: Model API 1.1.4		
Pipeline: Model Definition 1.1.4		
Pipeline: Multibranch 2.15		
Pipeline: Nodes and Processes 2.11		
Pipeline: REST API Plugin 2.8		
Pipeline: SCM Step 2.4		
Pipeline: Shared Groovy Libraries 2.8		
Pipeline: Stage Step 2.2		
Pipeline: Stage Tags Metadata 1.1.4		
Pipeline: Stage View Plugin 2.8		
Pipeline: Step API 2.10		
Pipeline: Supporting APIs 2.14		
Plain Credentials Plugin 1.4		
Pub-Sub "light" Bus 1.8	
REST API for Blue Ocean 1.0.1		
REST Implementation for Blue Ocean 1.0.1		
SCM API Plugin 2.1.1		
Script Security Plugin 1.27		
Server Sent Events (SSE) Gateway Plugin 1.15		
Slack Notification Plugin 2.2		
SSH Credentials Plugin 1.13		
SSH Slaves plugin 1.17		
Static Analysis Collector Plug-in 1.51		
Static Analysis Utilities 1.87		
Structs Plugin 1.7		
Test Results Analyzer Plugin 0.3.4		
Token Macro Plugin 2.1		
Variant Plugin 1.1		
Violations plugin 0.7.11		
Warnings Plug-in 4.62		
Web for Blue Ocean 1.0.1		
Windows Slaves Plugin 1.3.1
```

### Docker host/api version
```
Client:
Version:      17.03.1-ce
API version:  1.27
Go version:   go1.7.5
Git commit:   c6d412e
Built:        Tue Mar 28 00:40:02 2017
OS/Arch:      darwin/amd64

Server:
Version:      17.04.0-ce
API version:  1.28 (minimum version 1.12)
Go version:   go1.7.5
Git commit:   4845c56
Built:        Wed Apr  5 18:45:47 2017
OS/Arch:      linux/amd64
Experimental: false
```

### Description
I used the Jenkins Docker image `jenkins:2.46.1` and installed the latest Docker plugin (0.16.2). The plugin failed to connect to: `unix:///var/run/docker.sock`, and I got the following error stacktrace:

```
org.apache.http.conn.UnsupportedSchemeException: unix protocol is not supported
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:108)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:435)
Caused: javax.ws.rs.ProcessingException
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:481)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
	at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:701)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:697)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:420)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:316)
	at com.github.dockerjava.jaxrs.VersionCmdExec.execute(VersionCmdExec.java:26)
	at com.github.dockerjava.jaxrs.VersionCmdExec.execute(VersionCmdExec.java:13)
	at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at com.nirima.jenkins.plugins.docker.DockerCloud$DescriptorImpl.doTestConnection(DockerCloud.java:723)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:343)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:184)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:117)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:129)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:845)
	at org.kohsuke.stapler.MetaClass$5.doDispatch(MetaClass.java:248)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:845)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:135)
	at org.jenkinsci.plugins.ssegateway.Endpoint$SSEListenChannelFilter.doFilter(Endpoint.java:225)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
	at io.jenkins.blueocean.ResourceCacheControl.doFilter(ResourceCacheControl.java:134)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
	at jenkins.metrics.impl.MetricsFilter.doFilter(MetricsFilter.java:125)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:126)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:80)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:553)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Following the stack trace, the `org.glassfish.jersey.apache.connector.ApacheConnector` class was loaded from jersey-apache-connector-2.23.1.jar, which should've been loaded from **docker-java-shaded-0.16.2.jar** as it includes all the classes in `org.glassfish` package. (according to `docker-java-shaded/pom.xml`) After I deleted the jar and restarted the jenkins, the problem was gone.

Unless there is any strong reason to keep the jersey-apache-connector jar, we should exclude it from the plugin.

**Comment by erioness1125** [comment]
#494

**Comment by erioness1125** [comment]
PR #494

**Comment by ndeloof** [comment]
docker-plugin now relies on [docker-java-api-plugin](https://github.com/jenkinsci/docker-java-api-plugin)
