### ISSUE TITLE
DockerCloud#getServerUrl() appears to have been deprecated and is always null, but is still used?

### ISSUE THREAD

**Issue by dnwe** [jenkinsci/docker-plugin#517]
Testing with 1.7:
e.g.,
```
java.lang.NullPointerException
	at com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher.getAddressForSSHD(DockerComputerSSHLauncher.java:81)
	at io.jenkins.docker.SSHDockerSlaveProvisioner.provision(SSHDockerSlaveProvisioner.java:75)
	at com.nirima.jenkins.plugins.docker.DockerCloud.provisionWithWait(DockerCloud.java:397)
	at com.nirima.jenkins.plugins.docker.DockerCloud.access$000(DockerCloud.java:72)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:290)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:287)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Seemingly as the main constructor for DockerCloud no longer initializes serverUrl to anything?

**Comment by ndeloof** [comment]
thanks for catching this.
short terms workaround : use "docker host name" to define your docker node IP/hostname
this ssh discovery is a pain, I plan to rework this so it stops making some voodoo trying to detect external IP.

**Comment by dnwe** [comment]
@ndeloof unfortunately the docker hostname field only gets around the extraction of the hostname from the URL. The SSH launcher always looks at the URL to check if it starts with `sock:` which is the NPE above

**Comment by dnwe** [comment]
@ndeloof thanks, I've done a mvn release-prepare for 0.17.1 locally (using fad7f3d) and will test out the .hpi later this evening
