### ISSUE TITLE
0.17 stops supporting Docker Certificates Directory

### ISSUE THREAD

**Issue by roman-vynar** [jenkinsci/docker-plugin#520]
We are using TLS certificates to protect a remote Docket tcp socket.
Previously, with 0.16.2 it was working fine.

With 0.17 the dropdown to choose `Server Credentials` shows nothing despite I still have Certificate Dir in the credentials. Also when I go ahead and add a new one, it doesn't help either.
```
SEVERE: Timer task hudson.slaves.NodeProvisioner$NodeProvisionerInvoker@1fdaafba failed
java.lang.NoClassDefFoundError: org/glassfish/jersey/SslConfigurator
	at com.github.dockerjava.core.LocalDirectorySSLConfig.getSSLContext(LocalDirectorySSLConfig.java:56)
	at com.github.dockerjava.netty.NettyDockerCmdExecFactory$InetSocketInitializer.initSsl(NettyDockerCmdExecFactory.java:340)
	at com.github.dockerjava.netty.NettyDockerCmdExecFactory$InetSocketInitializer.connect(NettyDockerCmdExecFactory.java:322)
	at com.github.dockerjava.netty.NettyDockerCmdExecFactory.connect(NettyDockerCmdExecFactory.java:220)
	at com.github.dockerjava.netty.NettyDockerCmdExecFactory.connect(NettyDockerCmdExecFactory.java:213)
	at com.github.dockerjava.netty.NettyDockerCmdExecFactory.access$000(NettyDockerCmdExecFactory.java:157)
	at com.github.dockerjava.netty.NettyDockerCmdExecFactory$1.getChannel(NettyDockerCmdExecFactory.java:183)
```

Downgraded to 0.16.2 to make it working.

Docker 17.03, 17.09
Jenkins LTS 2.73.1 (docker image)

**Comment by roman-vynar** [comment]
0.18 does not fix this.

**Comment by ndeloof** [comment]
I have a pending fix to manage migration, in the meantime you should switch to docker-commons credentials and enter TLS keys there
