### ISSUE TITLE
SSH-Connection can not be established / Port not bound

### ISSUE THREAD

**Issue by gamma** [jenkinsci/docker-plugin#529]
Please don't use the issue tracker to ask questions, join jenkins-users mailing list.

If you get some troubles with docker-plugin, please report
 - [x] docker-plugin version you use: 1.0.0
 - [x] jenkins version you use: 2.85
 - [x] docker engine version you use:
   - Version = swarm/1.2.6, API Version = 1.22
   - Version = 17.05.0-ce, API Version = 1.29

Stacktrace:

```
[10/17/17 13:54:34] [SSH] Opening SSH connection to 10.10.10.10:33509.
Connection refused (Connection refused)
SSH Connection failed with IOException: "Connection refused (Connection refused)".
java.io.IOException: There was a problem while connecting to 10.10.10.10:33509
	at com.trilead.ssh2.Connection.connect(Connection.java:834)
	at com.trilead.ssh2.Connection.connect(Connection.java:703)
	at com.trilead.ssh2.Connection.connect(Connection.java:617)
	at hudson.plugins.sshslaves.SSHLauncher.openConnection(SSHLauncher.java:1284)
	at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:804)
	at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:793)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.trilead.ssh2.transport.TransportManager.establishConnection(TransportManager.java:367)
	at com.trilead.ssh2.transport.TransportManager.initialize(TransportManager.java:480)
	at com.trilead.ssh2.Connection.connect(Connection.java:774)
	... 9 more
[10/17/17 13:54:34] Launch failed - cleaning up connection
[10/17/17 13:54:34] [SSH] Connection closed.
```

There are two problems here, but I think they might relate:

 1) the container is being started with the ssh port exposed just as it is stated in the stacktrace. I can connect to the sshd from another client and successfully authenticate.
 2) in addition: the container is configured to expose an additional port. The port does not get bound though (and only will be when the "expose all ports" option is set).

When I leave the second port away, the connection works successfully.

**Comment by gamma** [comment]
It is possible, that the startup of the container takes a little longer and therefore the port is not yet ready when the connection is initialized.

But when I try to launch the agent again, another error pops up:

`[10/17/17 14:33:22] [SSH] Opening SSH connection to 10.10.10.10:33526.
[10/17/17 14:33:22] [SSH] WARNING: SSH Host Keys are not being verified. Man-in-the-middle attacks may be possible against this connection.
ERROR: Server rejected the 1 private key(s) for root (credentialId:InstanceIdentity/method:publickey)
[10/17/17 14:33:22] [SSH] Authentication failed.
Authentication failed.
[10/17/17 14:33:22] Launch failed - cleaning up connection
[10/17/17 14:33:22] [SSH] Connection closed.`

This might be due to a non-root user that is required for the connection.

**Comment by ndeloof** [comment]
> I can connect to the sshd from another client and successfully authenticate.

how do you get your ssh key registered ? SSHDockerSlaveProvisioner do inject a master specific key as the sole AuthorizedKeys for sshd (until you override the command ?)

**Comment by gamma** [comment]
My container are prepped with sshd and a default user including credentials. I do not rely on AuthorizedKeys. My container also runs sshd and an x11 using supervisor which might which is overridden by the prepared command.

I have not found how to override the command from Jenkins.

Also: is it correct, that the ssh authorization set in the template configuration is not used at all? 

Anyway: is it possible that the preparation routine which sets the AuthorizedKeys also overrides the port configuration and therefore disabled additional ports?

**Comment by ndeloof** [comment]
You should configure your container so that starting x11 and other services is done by ENTRYPOINT script, then this one just `exec $@` for the command to actually execute (see [docker best practices](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#entrypoint))

A fixed authorized_key stored in your container is a major security issue.
That being said for backward compatibility I'm looking into a way to force use of ssh key configured on jenkins for authentication.

About port binding I need to investigate. SSH Launcher for sure define a port to be exposed for SSH, maybe there's some unexpected side effect when one also bind all ports.

**Comment by gamma** [comment]
Thanks, I’ll look into it. The containers have been set up this way for quite a while now ;)

Shall we leave this issue open until the port binding issue has been investigated?

In addition: I’m also using windows container in the same way - currently with Cygwin. It does not work as it is now. Are there plans for supporting winssh or other custom commands?

**Comment by ndeloof** [comment]
So far only openssh sshd is supported, but this might be refactored into a configurable component so you could select an alternative impl for winssh and others. Just need to find a way to start this ssh server with a runtime-injected authorized public key.

**Comment by ndeloof** [comment]
workaround available by 1e3fdaa900b72854fc61af40baddcff3e42bacc5
(allow to disable ssh key injection)

**Comment by ndeloof** [comment]
For better understanding, can you please explain why you need some extra port exposed on the build container ? Understanding your use-case might help to find possible workarounds

**Comment by gamma** [comment]
Thanks for the commits, I'll check the new version today.

In our specific scenario we're running a VNC server on top of an X11 setup to be able to live monitor our test suite. This way is the easiest one for most of our developers to have visual access to the test machine.

**Comment by gamma** [comment]
The option does what I want it to, thx. I also found the point where to set the command to customize my setup even further.

But it seems that the "disable SSH key management" option is not reflected in the configuration. It is always shown as unchecked even though it was checked.

**Comment by ndeloof** [comment]
@gamma can you please open a separate issue for port bindings ?
