### ISSUE TITLE
Failed to provision container with NPE error

### ISSUE THREAD

**Issue by Abubakar22** [jenkinsci/docker-plugin#535]
Please don't use the issue tracker to ask questions, join jenkins-users mailing list.

If you get some troubles with docker-plugin, please report
 - [ ] docker-plugin version you use 1.0.1
 - [ ] jenkins version you use 2.60.3
 - [ ] docker engine version you use 17.03.1-ce
![image](https://user-images.githubusercontent.com/17588727/31754496-23141064-b466-11e7-8ad4-0015c8c7ce45.png)

 - [ ] stack trace / logs / any technical details that could help diagnose this issue
Getting this error while trying to build in a docker container

Error in provisioning; template='DockerTemplate{configVersion=2, labelString='taaa-docker-snapshot.artifactrepo-dev.jnj.com/ubuntu/mvn-3.5-jdk-1.8.0_144:0.2', launcher=com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher@40058600, remoteFsMapping='/app/eatci/.cijenkins', remoteFs='/home/jenkins', instanceCap=10, mode=NORMAL, retentionStrategy=com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy@5aae64ce, numExecutors=1, dockerTemplateBase=DockerTemplateBase{image=taaa-docker-snapshot.artifactrepo-dev.jnj.com/ubuntu/mvn-3.5-jdk-1.8.0_144:0.2}, removeVolumes=false, pullStrategy=PULL_LATEST, nodeProperties=[]}' for cloud='Docker-Host'
java.lang.NullPointerException
        at com.nirima.jenkins.plugins.docker.DockerCloud.getAuthConfig(DockerCloud.java:761)
	at com.nirima.jenkins.plugins.docker.DockerCloud.setRegistryAuthentication(DockerCloud.java:744)
	at io.jenkins.docker.DockerSlaveProvisioner.pullImage(DockerSlaveProvisioner.java:91)
	at io.jenkins.docker.DockerSlaveProvisioner.runContainer(DockerSlaveProvisioner.java:55)
	at io.jenkins.docker.SSHDockerSlaveProvisioner.provision(SSHDockerSlaveProvisioner.java:64)
	at com.nirima.jenkins.plugins.docker.DockerCloud.provisionWithWait(DockerCloud.java:392)
	at com.nirima.jenkins.plugins.docker.DockerCloud.access$000(DockerCloud.java:75)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:293)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:290)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
![image](https://user-images.githubusercontent.com/17588727/31754274-a3f556ae-b464-11e7-8014-f67799309130.png)

**Comment by ndeloof** [comment]
This has been fixed on master branch already. If you have opportunity please give last CI build a try : 
https://ci.jenkins.io/job/Plugins/job/docker-plugin/job/master/lastSuccessfulBuild/artifact/

**Comment by Abubakar22** [comment]
My Credentials are good but still i am getting the Credential ID error. I have tried login manually, everything is working fine.
What docker-plugin has to do with my credential ID.?
Its fine if it looks at my Credential Username and Password. But why it is trying to authenticate with Credential ID?
 
Below is my log report and i have attached the image if the same

Error in provisioning; template='DockerTemplate{configVersion=2, labelString='taaa-docker-snapshot.artifactrepo-dev.jnj.com/ubuntu/mvn-3.5-jdk-1.8.0_144:0.2', launcher=com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher@24ff1876, remoteFsMapping='/app/eatci/.cijenkins', remoteFs='/home/jenkins', instanceCap=10, mode=NORMAL, retentionStrategy=com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy@1625f523, numExecutors=1, dockerTemplateBase=DockerTemplateBase{image=taaa-docker-snapshot.artifactrepo-dev.jnj.com/ubuntu/mvn-3.5-jdk-1.8.0_144:0.2}, removeVolumes=false, pullStrategy=PULL_LATEST, nodeProperties=[]}' for cloud='Docker-Host'
java.lang.IllegalArgumentException: Invalid Credential ID 0c3d9934-e586-4017-aa7a-9e034774d9a1
	at com.nirima.jenkins.plugins.docker.DockerCloud.getAuthConfig(DockerCloud.java:775)
	at com.nirima.jenkins.plugins.docker.DockerCloud.setRegistryAuthentication(DockerCloud.java:750)
	at io.jenkins.docker.DockerSlaveProvisioner.pullImage(DockerSlaveProvisioner.java:91)
	at io.jenkins.docker.DockerSlaveProvisioner.runContainer(DockerSlaveProvisioner.java:55)
	at io.jenkins.docker.SSHDockerSlaveProvisioner.provision(SSHDockerSlaveProvisioner.java:64)
	at com.nirima.jenkins.plugins.docker.DockerCloud.provisionWithWait(DockerCloud.java:398)
	at com.nirima.jenkins.plugins.docker.DockerCloud.access$000(DockerCloud.java:81)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:299)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:296)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

![image](https://user-images.githubusercontent.com/17588727/31774864-eee37ace-b4b4-11e7-91c5-e9cbe46ed578.png)

**Comment by ndeloof** [comment]
"Invalid Credential ID 0c3d9934-e586-4017-aa7a-9e034774d9a1" means failure to resolve this ID to a Credential object.
What's the scope for selected credentials ? (System/Global/User ?)

**Comment by Abubakar22** [comment]
Global

**Comment by Abubakar22** [comment]
Ok Thank you. Is this will be a enhancement or bug?

**Comment by Abubakar22** [comment]
Thank you. I appreciate your time and effort on this issue.
