### ISSUE TITLE
Errors with Docker 1.1.0

### ISSUE THREAD

**Issue by johnrengelman** [jenkinsci/docker-plugin#55]
Getting this error when trying to launch a slave with Docker 1.1.0:
```
Jul 09, 2014 4:02:40 PM WARNING com.nirima.jenkins.plugins.docker.DockerCloud provision
Failed to count the # of live instances on Docker
javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:917)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:822)
	at org.glassfish.jersey.client.JerseyInvocation.access$600(JerseyInvocation.java:90)
	at org.glassfish.jersey.client.JerseyInvocation$3.call(JerseyInvocation.java:693)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:422)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:689)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:405)
	at org.glassfish.jersey.client.proxy.WebResourceFactory.invoke(WebResourceFactory.java:318)
	at com.sun.proxy.$Proxy76.inspectImage(Unknown Source)
	at com.nirima.docker.client.DockerClient$Image.inspect(DockerClient.java:582)
	at com.nirima.jenkins.plugins.docker.DockerCloud.countCurrentDockerSlaves(DockerCloud.java:242)
	at com.nirima.jenkins.plugins.docker.DockerCloud.addProvisionedSlave(DockerCloud.java:262)
	at com.nirima.jenkins.plugins.docker.DockerCloud.provision(DockerCloud.java:146)
	at hudson.slaves.NodeProvisioner.update(NodeProvisioner.java:281)
	at hudson.slaves.NodeProvisioner.access$000(NodeProvisioner.java:51)
	at hudson.slaves.NodeProvisioner$NodeProvisionerInvoker.doRun(NodeProvisioner.java:368)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
```

Docker daemon is configured to listen on `tcp://0.0.0.0:2375` and Jenkins has Docker Host configured as `http://localhost:2375`.

Test Connection in Jenkins returns successfully.

**Comment by KostyaSha** [comment]
@abraverm please try new hpi from https://jenkins.ci.cloudbees.com/job/plugins/job/docker-plugin/246/com.nirima$docker-plugin/ if issue still exists please open new issue with full description https://wiki.jenkins-ci.org/display/JENKINS/How+to+report+an+issue#Howtoreportanissue-WhatinformationtoprovideforEnvironmentandDescription
