### ISSUE TITLE
can not use jenkins parameter in image label

### ISSUE THREAD

**Issue by mohaijiang** [jenkinsci/docker-plugin#554]
![image](https://user-images.githubusercontent.com/3366709/32772331-78c61958-c960-11e7-8c7b-aed45838abfa.png)

 - [x] docker-plugin version 1.04 
![image](https://user-images.githubusercontent.com/3366709/32772159-fcb0b710-c95f-11e7-9f08-112235580afd.png)

 - [x] jenkins version 2.73.3
 - [x] docker engine version 1.12.6
 - [x] stack trace / logs / any technical details that could help diagnose this issue
```
Docker Build
Docker Build: building image at path /var/lib/jenkins/workspace/nbo-cicd-5.0.0/admin
Step 1 : FROM java:8-jre

 ---> e44d62cf8862

Step 2 : VOLUME /tmp

 ---> Using cache

 ---> 62d3fda4ed65

Step 3 : ADD target/nbo-cicd-admin-*-SNAPSHOT.jar app.jar

 ---> 96d41cdccf5b

Removing intermediate container 1aeead391387

Step 4 : ENV JAVA_OPTS ""

 ---> Running in 22801adf2401

 ---> 2e7b8006a892

Removing intermediate container 22801adf2401

Step 5 : ENTRYPOINT sh -c java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar

 ---> Running in a24c73924d70

 ---> 5804290e1167

Removing intermediate container a24c73924d70

Successfully built 5804290e1167

Tagging built image with registry.one2.newtouch.com:5000/newtouchone-test/nbo-cicd-admin:${BUILD_NUMBER}
ERROR: Build step failed with exception
com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"invalid tag format"}

	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:109)
	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:33)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
Build step 'Build / Publish Docker Image' marked build as failure
Finished: FAILURE
```

**Comment by YuvarajMe** [comment]
Yes, Same issue. Is there any other plugin will do this job?

**Comment by ThStock** [comment]
Sounds like the problem #466
