### ISSUE TITLE
Error building image when using ARG

### ISSUE THREAD

**Issue by rmisra1234** [jenkinsci/docker-plugin#556]
Hi There,

I am using docker plugin version 1.0.4. I have the following lines in my Dockerfile:

_ARG BASEIMAGE=python:2.7.13-wheezy
FROM $BASEIMAGE_

but whenever I build docker image via : 
`step([$class: 'DockerBuilderPublisher', cleanImages: false, cleanupWithJenkinsJobDelete: false, cloud: 'docker-01'])`

I am getting error:

`com.github.dockerjava.api.exception.DockerClientException: Could not build image: Please provide a source image with `from` prior to commit
	at com.github.dockerjava.core.command.BuildImageResultCallback.getImageId(BuildImageResultCallback.java:79)
	at com.github.dockerjava.core.command.BuildImageResultCallback.awaitImageId(BuildImageResultCallback.java:51)
	at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$Run.buildImage(DockerBuilderPublisher.java:373)
	at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$Run.run(DockerBuilderPublisher.java:306)`

Is ARG not supported in this version of the plugin ? If not, is it possible to add the support please?

Thanks very much for your help,
Richa

**Comment by skamenetskiy** [comment]
Just curious @richa-misra how do you pass the arg to the build command?
