### ISSUE TITLE
1.1.1 spins up full amount of containers for single job

### ISSUE THREAD

**Issue by adveres** [jenkinsci/docker-plugin#575]
Similar to @alexeygrigorovaurea 's post in: https://github.com/jenkinsci/docker-plugin/issues/569

-----

If you get some troubles with docker-plugin, please report
 - docker-plugin version: `1.1.1`
 - jenkins version: `2.93`
 - docker engine version: `Docker version 17.09.0-ce, build afdb6d4`

Just upgraded from `1.0.4` to `1.1.1`. Tried to run a single job, and the plugin spun up 25 slaves, but never ran the job.

-----

<img width="362" alt="screen shot 2017-12-12 at 12 39 06 pm" src="https://user-images.githubusercontent.com/775690/33899662-2a17b970-df3a-11e7-9913-deed2e0b98c8.png">

```
Dec 12, 2017 12:28:37 PM hudson.WebAppMain$3 run
INFO: Jenkins is fully up and running
Dec 12, 2017 12:36:30 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
INFO: Asked to provision 1 slave(s) for: null
Dec 12, 2017 12:36:30 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
INFO: Will provision 'adveres/jenkins-slave', for label: 'null', in cloud: 'platform-ciw1.plab'
Dec 12, 2017 12:36:30 PM com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
INFO: Provisioning 'adveres/jenkins-slave' number '0' on 'platform-ciw1.plab'; Total containers: '0'
Dec 12, 2017 12:36:30 PM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
INFO: Started provisioning Image of adveres/jenkins-slave from platform-ciw1.plab with 1 executors. Remaining excess workload: 0
Dec 12, 2017 12:36:30 PM com.nirima.jenkins.plugins.docker.DockerTemplate pullImage
INFO: Pulling image 'adveres/jenkins-slave:latest'. This may take awhile...
Dec 12, 2017 12:36:34 PM com.nirima.jenkins.plugins.docker.DockerTemplate pullImage
INFO: Finished pulling image 'adveres/jenkins-slave:latest', took 3833 ms
Dec 12, 2017 12:36:34 PM com.nirima.jenkins.plugins.docker.DockerTemplate provisionNode
INFO: Trying to run container for adveres/jenkins-slave
Dec 12, 2017 12:36:35 PM com.nirima.jenkins.plugins.docker.utils.PortUtils$ConnectionCheckSSH execute
INFO: SSH port is open on platform-ciw1.plab:34274
Dec 12, 2017 12:36:35 PM hudson.slaves.NodeProvisioner$2 run
INFO: Image of adveres/jenkins-slave provisioning successfully completed. We have now 2 computer(s)
...
...
...
INFO: Image of adveres/jenkins-slave provisioning successfully completed. We have now 25 computer(s)
```

It also keeps spamming the log with

```
INFO: Asked to provision 1 slave(s) for: null
Dec 12, 2017 12:39:06 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
INFO: Will provision 'adveres/jenkins-slave', for label: 'null', in cloud: 'platform-ciw1.plab'
Dec 12, 2017 12:39:06 PM com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
INFO: Not Provisioning 'adveres/jenkins-slave'; Server 'platform-ciw1.plab' full with '25' container(s)
Dec 12, 2017 12:39:06 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
INFO: Asked to provision 1 slave(s) for: null
```

I do see `Will provision 'adveres/jenkins-slave', for label: 'null' [...]`, and it's true the jobs do NOT specifically restrict where they can be run. This should be okay because me docker agent template has "use this node as much as possible".

**Comment by ndeloof** [comment]
Those nodes all fail to connect, don't they ?
Seems to be same issue as https://github.com/jenkinsci/docker-plugin/issues/568

**Comment by adveres** [comment]
You are correct, looking at the node logs...

```
[12/15/17 10:12:28] [SSH] Opening SSH connection to <DOCKER_HOST>
Key exchange was not finished, connection is closed.
java.io.IOException: There was a problem while connecting to <DOCKER_HOST>
	at com.trilead.ssh2.Connection.connect(Connection.java:834)
	at com.trilead.ssh2.Connection.connect(Connection.java:703)
	at com.trilead.ssh2.Connection.connect(Connection.java:617)
	at hudson.plugins.sshslaves.SSHLauncher.openConnection(SSHLauncher.java:1302)
	at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:814)
	at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:803)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Key exchange was not finished, connection is closed.
	at com.trilead.ssh2.transport.KexManager.getOrWaitForConnectionInfo(KexManager.java:95)
	at com.trilead.ssh2.transport.TransportManager.getConnectionInfo(TransportManager.java:237)
	at com.trilead.ssh2.Connection.connect(Connection.java:786)
	... 9 more
Caused by: java.io.IOException: Cannot read full block, EOF reached.
	at com.trilead.ssh2.crypto.cipher.CipherInputStream.getBlock(CipherInputStream.java:81)
	at com.trilead.ssh2.crypto.cipher.CipherInputStream.read(CipherInputStream.java:108)
	at com.trilead.ssh2.transport.TransportConnection.receiveMessage(TransportConnection.java:232)
	at com.trilead.ssh2.transport.TransportManager.receiveLoop(TransportManager.java:706)
	at com.trilead.ssh2.transport.TransportManager$1.run(TransportManager.java:502)
	... 1 more
[12/15/17 10:12:28] Launch failed - cleaning up connection
[12/15/17 10:12:28] [SSH] Connection closed.
```
Anyways, regarding https://github.com/jenkinsci/docker-plugin/issues/568, I'm fine using docker attach if you want to deprecate SSH because of impl difficulties.   I've re-upgraded to `1.1.1` and successfully run a job using docker attach (user `jenkins` for me, not root, as specified in my docker image).

I will say the behavior of spinning up max containers is confusing in the event the spun-up containers fail to connect. I don't know a better way to do it besides maybe halting after one failed connection and logging it. It's an awful cleanup if I have 25 allowed containers or something.

Thank you! Feel free to close this.
