### ISSUE TITLE
Jobs cannot run after updating to 1.1

### ISSUE THREAD

**Issue by farahfa** [jenkinsci/docker-plugin#582]
After updating to 1.1 (and even 1.1.1) from 1.0.4, jobs suddenly does not run anymore. I see that containers are sometimes getting created, but then failing to connect due to the following:

```
[12/14/17 16:00:24] [SSH] Opening SSH connection to 10.96.14.31:42208.
Key exchange was not finished, connection is closed.
java.io.IOException: There was a problem while connecting to 10.96.14.31:42208
	at com.trilead.ssh2.Connection.connect(Connection.java:834)
	at com.trilead.ssh2.Connection.connect(Connection.java:703)
	at com.trilead.ssh2.Connection.connect(Connection.java:617)
	at hudson.plugins.sshslaves.SSHLauncher.openConnection(SSHLauncher.java:1302)
	at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:814)
	at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:803)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Key exchange was not finished, connection is closed.
	at com.trilead.ssh2.transport.KexManager.getOrWaitForConnectionInfo(KexManager.java:95)
	at com.trilead.ssh2.transport.TransportManager.getConnectionInfo(TransportManager.java:237)
	at com.trilead.ssh2.Connection.connect(Connection.java:786)
	... 9 more
Caused by: java.io.IOException: The server hostkey was not accepted by the verifier callback
	at com.trilead.ssh2.transport.KexManager.handleMessage(KexManager.java:548)
	at com.trilead.ssh2.transport.TransportManager.receiveLoop(TransportManager.java:790)
	at com.trilead.ssh2.transport.TransportManager$1.run(TransportManager.java:502)
	... 1 more
[12/14/17 16:00:24] Launch failed - cleaning up connection
[12/14/17 16:00:24] [SSH] Connection closed.
```

The `Host Key Verification Strategy` is set to: `Known hosts file Verification Strategy` (as it has always been set to). If I change that setting to `Non verifying Verification Strategy` the job runs (but it's not secure)!

Jenkins is on version 2.89.2 LTS
I'm running stand-alone Docker swarm (Version = swarm/1.2.8, API Version = 1.22).

**Comment by ndeloof** [comment]
duplicates https://github.com/jenkinsci/docker-plugin/issues/568
