### ISSUE TITLE
Cannot start docker container

### ISSUE THREAD

**Issue by tkaitoh** [jenkinsci/docker-plugin#591]
When I use jenkins 2.89.2 and docker-plugin 1.0.4, I can use docker container for build.
After I upgraded docker-plugin to 1.1.1, docker container cannot be started.
I tried docker Plugin 1.1.2, which also failed.
I use docker 17.09.1-ce.

Jenkins log is following.
-----------------------
```
INFO: Will provision 'is4/jenkins-slave00', for label: 'null', in cloud: 'dockerSlave'
Dec 18, 2017 4:40:06 PM com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
INFO: Provisioning 'is4/jenkins-slave00' number '0' on 'dockerSlave'; Total containers: '0'
Dec 18, 2017 4:40:06 PM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
INFO: Started provisioning Image of is4/jenkins-slave00 from dockerSlave with 1 executors. Remaining excess workload: 0
Dec 18, 2017 4:40:06 PM com.nirima.jenkins.plugins.docker.DockerTemplate pullImage
INFO: Pulling image 'is4/jenkins-slave00:latest'. This may take awhile...
Dec 18, 2017 4:40:08 PM com.github.dockerjava.core.async.ResultCallbackTemplate onError
SEVERE: Error during callback
com.github.dockerjava.api.exception.NotFoundException: {"message":"pull access denied for is4/jenkins-slave00, repositor
y does not exist or may require 'docker login'"}

        at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:103)
        at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:33)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by ndeloof** [comment]
do you have registry credentials configured for this image ?

**Comment by tkaitoh** [comment]
No, I don't set authentication for using this image.

**Comment by tkaitoh** [comment]
I changed the configuration "Pull strategy" from "Pull once and update latest" to "never pull".
Then error has changed like below.

```
Dec 19, 2017 11:22:25 AM com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
INFO: Provisioning 'is4/jenkins-slave00' number '0' on 'dockerSlave'; Total containers: '0'
Dec 19, 2017 11:22:25 AM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
INFO: Started provisioning Image of is4/jenkins-slave00 from dockerSlave with 1 executors. Remaining excess workload: -0
Dec 19, 2017 11:22:25 AM com.nirima.jenkins.plugins.docker.DockerTemplate provisionNode
INFO: Trying to run container for is4/jenkins-slave00
Dec 19, 2017 11:22:25 AM com.github.dockerjava.core.async.ResultCallbackTemplate onError
SEVERE: Error during callback
com.github.dockerjava.api.exception.NotFoundException: {"message":"No such container: 921daaa9405ae737303646355a33708bf1
6395d346606c6e7e5fe387b7883a51"}

        at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:103)
        at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:33)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:748)

Dec 19, 2017 11:22:26 AM com.nirima.jenkins.plugins.docker.utils.PortUtils$ConnectionCheckSSH execute
INFO: SSH port is open on localhost:33305
[12/19/17 11:22:26] SSH Launch of docker-8a67afb888ae on localhost failed in 32 ms
Dec 19, 2017 11:22:35 AM hudson.slaves.NodeProvisioner$2 run
INFO: Image of is4/jenkins-slave00 provisioning successfully completed. We have now 2 computer(s)
Dec 19, 2017 11:22:35 AM com.nirima.jenkins.plugins.docker.DockerCloud provision
INFO: Asked to provision 1 slave(s) for: null
Dec 19, 2017 11:22:35 AM com.nirima.jenkins.plugins.docker.DockerCloud provision
INFO: Will provision 'is4/jenkins-slave00', for label: 'null', in cloud: 'dockerSlave'
Dec 19, 2017 11:22:35 AM com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
INFO: Not Provisioning 'is4/jenkins-slave00'. Instance limit of '1' reached on server 'dockerSlave'
Dec 19, 2017 11:22:35 AM com.nirima.jenkins.plugins.docker.DockerCloud provision
INFO: Will provision 'is4/jenkins-slave01', for label: 'null', in cloud: 'dockerSlave'
Dec 19, 2017 11:22:35 AM com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
INFO: Provisioning 'is4/jenkins-slave01' number '0' on 'dockerSlave'; Total containers: '1'
Dec 19, 2017 11:22:35 AM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
INFO: Started provisioning Image of is4/jenkins-slave01 from dockerSlave with 1 executors. Remaining excess workload: 0
Dec 19, 2017 11:22:35 AM com.nirima.jenkins.plugins.docker.DockerTemplate provisionNode
INFO: Trying to run container for is4/jenkins-slave01
Dec 19, 2017 11:22:36 AM com.nirima.jenkins.plugins.docker.utils.PortUtils$ConnectionCheckSSH execute
INFO: SSH port is open on localhost:33306
[12/19/17 11:22:36] SSH Launch of unknown on localhost failed in 1 ms
```

**Comment by ndeloof** [comment]
this seems to demonstrate container failed to start. Please capture container's logs and state
(`docker logs ID` & `docker inspect ID`)

**Comment by tkaitoh** [comment]
Here are captured logs.

```
$ docker logs 1bf3a846b11b
<no log>
$ docker inspect 1bf3a846b11b
[
    {
        "Id": "1bf3a846b11b34e50f11a3f4b64d95f1768ce2431bf018dff15522e91d0e1a8d",
        "Created": "2017-12-20T00:17:37.246997947Z",
        "Path": "/usr/sbin/sshd",
        "Args": [
            "-D",
            "-p",
            "22"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 3121,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2017-12-20T00:17:38.050274917Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:c4d1e0e45fb0238f5b00afda7155bdc9c2448d22d5ac8e44c8caf9e125929076",
        "ResolvConfPath": "/var/lib/docker/containers/1bf3a846b11b34e50f11a3f4b64d95f1768ce2431bf018dff15522e91d0e1a8d/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/1bf3a846b11b34e50f11a3f4b64d95f1768ce2431bf018dff15522e91d0e1a8d/hostname",
        "HostsPath": "/var/lib/docker/containers/1bf3a846b11b34e50f11a3f4b64d95f1768ce2431bf018dff15522e91d0e1a8d/hosts",
        "LogPath": "/var/lib/docker/containers/1bf3a846b11b34e50f11a3f4b64d95f1768ce2431bf018dff15522e91d0e1a8d/1bf3a846b11b34e50f11a3f4b64d95f1768ce2431bf018dff15522e91d0e1a8d-json.log",
        "Name": "/reverent_wing",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/usr/local:/usr/local:ro",
                "/var/lib/is4/port/00:/var/lib/is4:ro",
                "/var/lib/is4/ref/00:/tmp/is4:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "22/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": ""
                    }
                ],
                "61000/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "61000"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/0f6e0d1c83b31a41b35d8aea2d8f431c0b5643643f6521eaebd092148c197b60-init/diff:/var/lib/docker/overlay2/ab5dde88688b8f156d95bab802cbd22e95d64f557ff15fac3054393aa0b065d6/diff:/var/lib/docker/overlay2/472295a381d5c6bab4854f4a8f9e59fc7ec84bf1393f146ffb27b7111032cb8d/diff:/var/lib/docker/overlay2/93d354c2771171a6a74100771316d999db0b97a70594f9b5e16be96fe8f6f6a5/diff:/var/lib/docker/overlay2/ccb2f8d81a90508baecd14f8739792a35b4b8e4f97fded8dc16b64b02fbf61a1/diff:/var/lib/docker/overlay2/da10d4f0fd30bfb06ae3248e7ad4cd5df286eec25c596929aabdd88f1ff84a88/diff:/var/lib/docker/overlay2/4d958572dc5984602775dc580c7516c76d1a0ac29978d86f246b6729f46537ad/diff:/var/lib/docker/overlay2/d66dbcb58abffeebf549609b0f5717feb5cdc62bc7c222dfe13ccdbeea1761a2/diff:/var/lib/docker/overlay2/7f2ba7df6384293ed178efe948a54a048d15800d90c5487fff5b80ba73a3b5d8/diff:/var/lib/docker/overlay2/47bbcdc84ecaec1ecf17858f46bd45ab394718b58ea49f02d8d8477a7666fe58/diff:/var/lib/docker/overlay2/c1242faa7e7caf368f4f5d6898420a4aa19f3f236a69076c9d0960816457ee1a/diff:/var/lib/docker/overlay2/a299deaa5e6da559fc0bc3189c2d9c6d061c49b1d199610022f2329e11643485/diff:/var/lib/docker/overlay2/b990a9b1bd49c5845445b2cdf265a8a2ddd1fd639b4ae1bc45bab5c24b6889d3/diff:/var/lib/docker/overlay2/152e966ac550f50a84d5e7c83a592a9a4ff309ef00d038d0bac19389e2efefcb/diff:/var/lib/docker/overlay2/8592749b32c1d1bec2aed25986163d10c5d1501e5c7c6c2f51786e10196eebfd/diff:/var/lib/docker/overlay2/5b24500a63a05bdca8e8c8c4ec4183a1de8b0e774c5e81d2aef325c4245ba5c6/diff:/var/lib/docker/overlay2/b5eb8c13bf2bcaa52bb7413bd9cd6edf93c09d9ab4939c04c89ab70a61807cf7/diff:/var/lib/docker/overlay2/aaed12c7bb53748cc8935e18e6c26cce8d917b128a4f7528052b0b75ad7adc52/diff:/var/lib/docker/overlay2/293b06afd19acbb172f1382edb3d695ffd19a6a5fed219d7bf57e93c56c89b14/diff:/var/lib/docker/overlay2/8399734b626ce7475e0c53718e3844c41dc502311d3e7d6d72c2bb13a4348ce6/diff:/var/lib/docker/overlay2/18339ab00ada17c4086a95431735bd2526d9fd167b6e5ae28322f997acac0766/diff:/var/lib/docker/overlay2/60a578951b5e8f57b530c242ab0da2398fc0c54d92f230fea678b19494a9a623/diff:/var/lib/docker/overlay2/0b174c54a69ce89025673cb9977e18a6ca4640566cf7061b205040092c820346/diff:/var/lib/docker/overlay2/ceb1bd9cc91b2b3987a2b8381eb95579cbd65c815ebc12a9a6b395223224b0a4/diff:/var/lib/docker/overlay2/5138485a9424158d74b8a68d290d02fd42725b2908cf641627572f1a5faf9fdd/diff:/var/lib/docker/overlay2/82b2025a6ad94a9ab1c17c4f7879a0b37e1a4898fed8532e3f5a4014c384bd7d/diff:/var/lib/docker/overlay2/7fdac7a1a5ba1e076d90abf00d051c89f4b37ab239a7ba686150bf057fcbf8b2/diff:/var/lib/docker/overlay2/14c447c9d3d18804b8579b018628dcfc7b3bf39e10ffbf5fb3aa2e902fce707a/diff:/var/lib/docker/overlay2/a3b477140eba0ec7b847f166b95b5d310ed5e956910eccfd4d2736785c43d69b/diff:/var/lib/docker/overlay2/adc4c674ba6f7410dc86fb0678b0ca314c2e7fe47ab01aff6c0e88276c281cc5/diff:/var/lib/docker/overlay2/f2defc72c401abe8512c4befefa52adf1be5a7c09215b020dd05fc5e397fbf54/diff:/var/lib/docker/overlay2/8f0077f39ee52d57e20be889f8d784e02e312bfcb9173d88b9c85fd3550404dc/diff:/var/lib/docker/overlay2/160c1c0e5f31c8d5820ea5d902ab8091c098ead027d087f37584b539d49978b3/diff:/var/lib/docker/overlay2/352442bc13436b63dce1925ac9669757e8f93cd33226e4bcc37716e05cb67fce/diff:/var/lib/docker/overlay2/f2ebff5c4cb10b3c41575436f2c484aef3ee1d2fe6271b6b28455cf36d635912/diff:/var/lib/docker/overlay2/ecf5b466b309028d6a7473a620b86dd0388e417e6544f4dfd1019a0d866555fc/diff:/var/lib/docker/overlay2/6c26a5fe57ad15e0cbb6bed8252cbdd143f55af6bc882bfdeef3e57a7fe9647f/diff:/var/lib/docker/overlay2/c6485b47c6b57a0ba6a922746e1722b152ff207e4cdda3674d06422d0fae86f0/diff",
                "MergedDir": "/var/lib/docker/overlay2/0f6e0d1c83b31a41b35d8aea2d8f431c0b5643643f6521eaebd092148c197b60/merged",
                "UpperDir": "/var/lib/docker/overlay2/0f6e0d1c83b31a41b35d8aea2d8f431c0b5643643f6521eaebd092148c197b60/diff",
                "WorkDir": "/var/lib/docker/overlay2/0f6e0d1c83b31a41b35d8aea2d8f431c0b5643643f6521eaebd092148c197b60/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/var/lib/is4/ref/00",
                "Destination": "/tmp/is4",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/usr/local",
                "Destination": "/usr/local",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/var/lib/is4/port/00",
                "Destination": "/var/lib/is4",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "1bf3a846b11b",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "22/tcp": {},
                "61000/tcp": {},
                "61001/tcp": {},
                <snip>
                "61898/tcp": {},
                "61899/tcp": {},
                "61900/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/usr/sbin/sshd",
                "-D",
                "-p",
                "22"
            ],
            "Image": "is4/jenkins-slave00",
            "Volumes": {
                "/tmp/is4": {},
                "/var/lib/is4": {}
            },
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "JenkinsId": "4dfa5637209c155f82356f732d8acf41"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "72a814fb95777c3a841793c3283430429ce49aa48e5b13256ceae3fd4b73ab78",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "22/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "33363"
                    }
                ],
                "61000/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "61000"
                    }
                ],
                "61001/tcp": null,
                "61002/tcp": null,
                "61003/tcp": null,
                <snip>
                "61898/tcp": null,
                "61899/tcp": null,
                "61900/tcp": null
            },
            "SandboxKey": "/var/run/docker/netns/72a814fb9577",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "171d8161e62ef67cbf9f2816baafc8dfbc2f39d7af60ac3ed2f0d28a34baf02f",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "5ec5a95bd4d404b14a10f9d23207dda1756c0e3c620bc6b4a38ae51b896f1abe",
                    "EndpointID": "171d8161e62ef67cbf9f2816baafc8dfbc2f39d7af60ac3ed2f0d28a34baf02f",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02",
                    "DriverOpts": null
                }
            }
        }
    }
]

```

**Comment by ndeloof** [comment]
so container is running with sshd configured according to your custom command. Sounds like you have some misconfiguration with the SSH key being used for authentication. Double check you can ssh this container with the configured credentials.

**Comment by tkaitoh** [comment]
I changed "Host Key Verification Strategy" from "Known hosts file Verification Stratety" to "Non verifying verification strategy" and docker slave worked again.
