### ISSUE TITLE
Pull Strategy option affects use of local Docker images

### ISSUE THREAD

**Issue by adam-kosseck** [jenkinsci/docker-plugin#599]
> docker-plugin version 1.1.2
> jenkins version lts-alpine (2.89.2)
> docker engine version 17.12.0-ce build c97c6d6

I have a Jenkins Docker container configured with the Job DSL & Docker plugins to checkout and build code in a sibling Docker container (Jenkins shares the Docker socket with the host).

Initially when I setup the system using the Jenkins slave image from Dockerhub (e.g. jenkins/slave:alpine) it worked fine.
When I switched to using a docker image hosted locally (one based off jenkins/slave with customisations) it no longer worked.  

When jobs are initiated Jenkins now shows the jobs as "pending - Jenkins doesn't have label slave"
Jenkins logs show:

```
Jan 03, 2018 5:13:16 AM com.nirima.jenkins.plugins.docker.DockerCloud$1 run
SEVERE: Error in provisioning; template='DockerTemplate{configVersion=2, labelString='slave', connector=io.jenkins.docker.connector.DockerComputerAttachConnector@57cd7bfc, remoteFs='/home/jenkins', instanceCap=2147483647, mode=EXCLUSIVE, retentionStrategy=com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy@7479ce5c, dockerTemplateBase=DockerTemplateBase{image='cv-utils-infra-jenkins-slave:1.0.0', pullCredentialsId='', registry=DockerRegistryEndpoint[null;credentialsId=null], dockerCommand='', hostname='', dnsHosts=[], network='bsl', volumes=[], volumesFrom2=[], environment=[], bindPorts='', bindAllPorts=false, memoryLimit=null, memorySwap=null, cpuShares=null, privileged=false, tty=false, macAddress='null', extraHosts=[]}, removeVolumes=false, pullStrategy=PULL_ALWAYS, nodeProperties=[]}' for cloud='Docker'
com.github.dockerjava.api.exception.NotFoundException: {"message":"pull access denied for cv-utils-infra-jenkins-slave, repository does not exist or may require 'docker login'"}
	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:103)
	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:33)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:997)
	at io.netty.channel.epoll.EpollDomainSocketChannel$EpollDomainUnsafe.epollInReady(EpollDomainSocketChannel.java:138)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:401)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:306)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
```

This is with the pull strategy set to "pull all images every time".
However if I change the pull strategy to "Pull once and update latest" and restart Jenkins it appears to work fine.
As soon as I switch the pull strategy back to "pull all images every time" it breaks again.

I have also noted someone posting about this on [StackOverflow](https://stackoverflow.com/questions/47758187/docker-container-as-build-slave-for-jenkins).

**Comment by adam-kosseck** [comment]
Also seems to have some relation to the "Discard old builds" setting.
Turning this setting off (was set to keep max 5 builds) appears to reduce the occurrence of the issue mentioned above.

**Comment by ndeloof** [comment]
if the image is installed on docker host(s) without pulling from a registry, just configure template to use strategy "never pull".
