### ISSUE TITLE
Error when pull the image from docker.io

### ISSUE THREAD

**Issue by iamchiho** [jenkinsci/docker-plugin#600]
Please don't use the issue tracker to ask questions, join jenkins-users mailing list.

Docer version: 1.12.6
Jenkins: 2.89.2 (running on top of Docker)
Docker API Plugin: 3.0.14

When I tried to pull an image tomcat:7.0-jre8 from docker.io in Jenkins, it failed. Console error below.

Building in workspace /var/jenkins_home/workspace/tomcat-pull-and-push
[Docker] INFO: Pulling image tomcat:7.0-jre8
[Docker] INFO: PullResponseItem[stream=<null>,status=Trying to pull repository docker.io/library/tomcat ... ,progressDetail=<null>,progress=<null>,id=<null>,from=<null>,time=<null>,errorDetail=<null>,error=<null>,aux=<null>]
[Docker] INFO: PullResponseItem[stream=<null>,status=Pulling from docker.io/library/tomcat,progressDetail=<null>,progress=<null>,id=7.0-jre8,from=<null>,time=<null>,errorDetail=<null>,error=<null>,aux=<null>]
[Docker] INFO: PullResponseItem[stream=<null>,status=Digest: sha256:312994f28fd98bb46b67dfe8d6c06ff194c78830708fc5f7eac6277af6db5a83,progressDetail=<null>,progress=<null>,id=<null>,from=<null>,time=<null>,errorDetail=<null>,error=<null>,aux=<null>]
ERROR: Build step failed with exception
com.github.dockerjava.api.exception.DockerClientException: Could not pull image: Digest: sha256:312994f28fd98bb46b67dfe8d6c06ff194c78830708fc5f7eac6277af6db5a83
	at com.github.dockerjava.core.command.PullImageResultCallback.awaitSuccess(PullImageResultCallback.java:50)
	at org.jenkinsci.plugins.dockerbuildstep.cmd.PullImageCommand.execute(PullImageCommand.java:92)
	at org.jenkinsci.plugins.dockerbuildstep.DockerBuilder.perform(DockerBuilder.java:74)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1724)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:421)
Build step 'Execute Docker command' marked build as failure
Finished: FAILURE

**Comment by ndeloof** [comment]
You're asking the wrong project.
see https://github.com/jenkinsci/docker-build-step-plugin
(don't ask me why there's so much comparable docker-* plugins)
