### ISSUE TITLE
Docker Plugin is creating issues in log and when manually creating non docker node

### ISSUE THREAD

**Issue by pteichner** [jenkinsci/docker-plugin#603]
- [ ] docker-plugin version you use: 1.1.2
 - [ ] jenkins version you use: 2.73.2
 - [ ] docker engine version you use: 17.09.1-ce
 - [ ] stack trace / logs / any technical details that could help diagnose this issue

Jenkins exception in the logs show the below error, even when there is no templates added or jobs running that would require a docker container to run in.

```
Timer task hudson.model.LoadStatistics$LoadStatisticsUpdater@1d3715b0 failed
java.lang.NullPointerException
	at com.nirima.jenkins.plugins.docker.DockerCloud.getTemplates(DockerCloud.java:388)
	at com.nirima.jenkins.plugins.docker.DockerCloud.getTemplate(DockerCloud.java:340)
	at com.nirima.jenkins.plugins.docker.DockerCloud.canProvision(DockerCloud.java:322)
	at hudson.model.Label.getClouds(Label.java:227)
	at hudson.model.Label.isEmpty(Label.java:436)
	at jenkins.model.Jenkins.getLabels(Jenkins.java:2018)
	at hudson.model.LoadStatistics$LoadStatisticsUpdater.doRun(LoadStatistics.java:395)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:51)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by dmitrynikolaev** [comment]
The same issue:

Jenkins v2.89.4
Docker plugin v1.1.3
Docker v17.12.0-ce

**Comment by jsalatiel** [comment]
+1

**Comment by pjdarton** [comment]
Hmm, that rather looks like [DockerCloud.java line 388](https://github.com/jenkinsci/docker-plugin/blob/docker-plugin-1.1.2/src/main/java/com/nirima/jenkins/plugins/docker/DockerCloud.java#L388) is referencing the (potentially null) `templates` field directly rather than calling `getTemplates()` (which never returns null).

**Comment by pjdarton** [comment]
FITNR

**Comment by agrrh** [comment]
Just faced same issue in 1.1.3.

@pjdarton which realease is the "next" one? Should I create another issue or better wait for 1.1.4?

**Comment by sdanieru** [comment]
On our jenkins deployment, the "Restrict where this project can be run" option had disappeared from all our job configurations. Looking in the log, I saw the error mentioned by the OP, which lead me here. After disabling the 'docker plugin', the "Restrict where this project can be run" option is again visible! Is anyone else seeing this or understand why this issue would cause the option to disappear?

**Comment by pjdarton** [comment]
For those in need of a workaround until there's an official release, I would suggest that you try going into Manage Jenkins -> Configure System and scroll down to the cloud section and add a Template to your Docker Cloud.
If you give it a nonsense label and only run it for builds matching that label then it should have zero impact.  It doesn't even need to have a valid image etc.
i.e. Because this bug is caused by having no "list of templates", I would expect that if you have _a_ template instead of _no_ templates, then the problem will vanish.

That should, I hope, tide you over until the next release.
