### ISSUE TITLE
Concurrent stages occasionally 'steal' agents from another stage

### ISSUE THREAD

**Issue by saxonww** [jenkinsci/docker-plugin#604]
I'm using docker-plugin version 1.1.2 on Jenkins 2.89.2. The Docker engine version is 17.09.0-ce. We're using the 'attach docker container' connect method.

We have several pipeline jobs which attempt to spin up images using label expressions matching Docker agent templates. The observed behavior is that a stage will attempt to allocate a node for label `someExpression`, it will be identified that there are no existing nodes matching `someExpression`, then a docker container will be spun up to meet the need; at that time, the job will instead depend on e.g. `docker-containerId` and begin using it as soon as it's spun up.

What we're seeing is that sometimes with two stages (A and B) which use the same label expression `someExpression`, A will be causing a new Docker container to be spun up right when B is trying to determine if one exists. B will 'steal' A's container, but by that point 'A' will be dependent on `docker-containerId` instead of `someExpression`. A will then stall.

Compounding this is that once stage B finishes and `docker-containerId` terminates, stage A goes back to depending on `someExpression`, but this does not immediately result in a new Docker container spinning up to meet the need. If there is a new stage C which also needs `someExpression`, _it_ will cause a new container to spin up, but then A will steal that one, and C will stall. And so on.

I believe restarting Jenkins will clear this condition. Also, assigning `someExpression` to a non-Docker agent will let the stalled stage complete, but then it seems that all stages want to (and will wait on) that non-Docker agent instead; we have to remove `someExpression` from the non-Docker agent, change `someExpression` to `someOtherExpression` for the Agent Template in Jenkins config, then change it back, before things get back to normal.

The relevant entries from jenkins.log:
```
Jan 11, 2018 10:31:23 AM com.nirima.jenkins.plugins.docker.DockerCloud provision
INFO: Asked to provision 1 slave(s) for: someExpression
Jan 11, 2018 10:31:23 AM com.nirima.jenkins.plugins.docker.DockerCloud provision
INFO: Will provision 'artifactory:5000/imageName:version', for label: 'someExpression', in cloud: 'Docker - Linux'
Jan 11, 2018 10:31:23 AM com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
INFO: Provisioning 'artifactory:5000/imageName:version' number '1' on 'Docker - Linux'; Total containers: '12'
Jan 11, 2018 10:31:23 AM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
INFO: Started provisioning Image of artifactory:5000/imageName:version from Docker - Linux with 1 executors. Remaining excess workload: 0
Jan 11, 2018 10:31:23 AM com.nirima.jenkins.plugins.docker.DockerTemplate pullImage
INFO: Pulling image 'artifactory:5000/imageName:version'. This may take awhile...
Jan 11, 2018 10:31:28 AM com.nirima.jenkins.plugins.docker.DockerTemplate pullImage
INFO: Finished pulling image 'artifactory:5000/imageName:version', took 5076 ms
Jan 11, 2018 10:31:28 AM com.nirima.jenkins.plugins.docker.DockerTemplate provisionNode
INFO: Trying to run container for artifactory:5000/imageName:version
Jan 11, 2018 10:31:30 AM com.nirima.jenkins.plugins.docker.DockerCloud$1 run
SEVERE: Error in provisioning; template='DockerTemplate{configVersion=2, labelString='someExpression', connector=io.jenkins.docker.connector.DockerComputerAttach
Connector@2bd76cef, remoteFs='/home/jenkins', instanceCap=2147483647, mode=EXCLUSIVE, retentionStrategy=com.nirima.jenkins.plugins.docker.strategy.DockerOnceRe
tentionStrategy@46952426, dockerTemplateBase=DockerTemplateBase{image='artifactory:5000/imageName:version', pullCredentialsId='', reg
istry=DockerRegistryEndpoint[null;credentialsId=null], dockerCommand='', hostname='', dnsHosts=[], network='', volumes=[/var/run/docker.sock:/var/run/docker.so
ck, /usr/bin/docker:/usr/bin/docker:ro], volumesFrom2=[], environment=[], bindPorts='', bindAllPorts=false, memoryLimit=null, memorySwap=null, cpuShares=null,
privileged=false, tty=false, macAddress='null', extraHosts=[]}, removeVolumes=false, pullStrategy=PULL_ALWAYS, nodeProperties=[]}' for cloud='Docker - Linux'
com.github.dockerjava.api.exception.DockerClientException: Unable to read temp file /tmp/docker-java8036914009658167143.tar.gz
        at com.github.dockerjava.core.command.CopyArchiveToContainerCmdImpl.exec(CopyArchiveToContainerCmdImpl.java:144)
        at io.jenkins.docker.connector.DockerComputerConnector.injectRemotingJar(DockerComputerConnector.java:87)
        at io.jenkins.docker.connector.DockerComputerAttachConnector.afterContainerStarted(DockerComputerAttachConnector.java:63)
        at com.nirima.jenkins.plugins.docker.DockerTemplate.provisionNode(DockerTemplate.java:435)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.run(DockerCloud.java:268)
        at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: dockerHost/10.0.0.10:2375
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267)
        at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        ... 1 more
```
 And at this same time on the Docker host:

```
Jan 11 10:30:27 dockerHost dockerd[134558]: time="2018-01-11T10:30:27.637806915-05:00" level=error msg="attach: stderr: write tcp 10.0.0.10:2375->10.99.99.10:37100: write: broken pipe"
Jan 11 10:30:27 dockerHost dockerd[134558]: time="2018-01-11T10:30:27.924120839-05:00" level=error msg="Error running exec in container: exec attach failed: write tcp 10.0.0.10:2375->10.99.99.10:37100: write: broken pipe"
Jan 11 10:30:37 dockerHost dockerd[134558]: time="2018-01-11T10:30:37.640352382-05:00" level=info msg="Container 0aa82b3ebb261fbb7db167956991a0fe868746cea8ceba74d002257d4c77c1de failed to exit within 10 seconds of signal 15 - using the force"
```

We see that the 'attach container' method is marked as experimental, but aside from the above we have not had major problems with it. I haven't tried replacing my containers with some which would work via JNLP.

**Comment by ndeloof** [comment]
if you have two tasks in the queue, `NodeProvisioner` should ask the Cloud plugin to create 2 extra nodes, or invoke it twice. I'll try to reproduce.

**Comment by saxonww** [comment]
It may be a coincidence, but I believe that both times this has happened, one of the jobs had just been restarted due to a new code push; we're using the Gerrit Trigger to kick off pipeline runs.

If there's anything we can set up to help gather more information if/when this happens again?

**Comment by pjdarton** [comment]
I _think_ this is now fixed (when I rewrote the retentionStrategy code to remove a race condition).
If you can still reproduce the issue, feel free to re-open this issue.
