### ISSUE TITLE
UnsupportedOperationException: Refusing to marshal com.github.dockerjava.api.command.InspectContainerResponse

### ISSUE THREAD

**Issue by wumpz** [jenkinsci/docker-plugin#614]
Seems to be a problem due to JEP 200. I use the latest version of Jenkins and this plugin.

```
java.io.IOException: java.lang.RuntimeException: Failed to serialize hudson.model.Slave#launcher for class io.jenkins.docker.DockerTransientNode
jenkins_1    |  at hudson.XmlFile.write(XmlFile.java:200)
jenkins_1    |  at jenkins.model.Nodes.save(Nodes.java:274)
jenkins_1    |  at hudson.util.PersistedList.onModified(PersistedList.java:173)
jenkins_1    |  at hudson.util.PersistedList.replaceBy(PersistedList.java:85)
jenkins_1    |  at hudson.model.Slave.setNodeProperties(Slave.java:299)
jenkins_1    |  at com.nirima.jenkins.plugins.docker.DockerTemplate.provisionNode(DockerTemplate.java:448)
jenkins_1    |  at com.nirima.jenkins.plugins.docker.DockerCloud$1.run(DockerCloud.java:268)
jenkins_1    |  at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
jenkins_1    |  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
jenkins_1    |  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
jenkins_1    |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jenkins_1    |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jenkins_1    |  at java.lang.Thread.run(Thread.java:748)
jenkins_1    | Caused by: java.lang.RuntimeException: Failed to serialize hudson.model.Slave#launcher for class io.jenkins.docker.DockerTransientNode
jenkins_1    |  at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:256)
jenkins_1    |  at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
jenkins_1    |  at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
jenkins_1    |  at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
jenkins_1    |  at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
jenkins_1    |  at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
jenkins_1    |  at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
jenkins_1    |  at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
jenkins_1    |  at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:82)
jenkins_1    |  at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
jenkins_1    |  at com.thoughtworks.xstream.XStream.marshal(XStream.java:1026)
jenkins_1    |  at com.thoughtworks.xstream.XStream.marshal(XStream.java:1015)
jenkins_1    |  at com.thoughtworks.xstream.XStream.toXML(XStream.java:988)
jenkins_1    |  at hudson.XmlFile.write(XmlFile.java:193)
jenkins_1    |  ... 12 more
jenkins_1    | Caused by: java.lang.RuntimeException: Failed to serialize hudson.slaves.DelegatingComputerLauncher#launcher for class io.jenkins.docker.connector.DockerComputerConnector$1
jenkins_1    |  at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:256)
jenkins_1    |  at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
jenkins_1    |  at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
jenkins_1    |  at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
jenkins_1    |  at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
jenkins_1    |  at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
jenkins_1    |  at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
jenkins_1    |  at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
jenkins_1    |  at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
jenkins_1    |  at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
jenkins_1    |  ... 25 more
jenkins_1    | Caused by: java.lang.RuntimeException: Failed to serialize io.jenkins.docker.connector.DockerComputerJNLPConnector$1#val$inspect for class io.jenkins.docker.connector.DockerComputerJNLPConnector$1
jenkins_1    |  at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:256)
jenkins_1    |  at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
jenkins_1    |  at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
jenkins_1    |  at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
jenkins_1    |  at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
jenkins_1    |  at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
jenkins_1    |  at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
jenkins_1    |  at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
jenkins_1    |  at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
jenkins_1    |  at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
jenkins_1    |  ... 34 more
jenkins_1    | Caused by: java.lang.UnsupportedOperationException: Refusing to marshal com.github.dockerjava.api.command.InspectContainerResponse for security reasons; see https://jenkins.io/redirect/class-filter/
jenkins_1    |  at hudson.util.XStream2$BlacklistedTypesConverter.marshal(XStream2.java:543)
jenkins_1    |  at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
jenkins_1    |  at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
jenkins_1    |  at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
jenkins_1    |  at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
jenkins_1    |  at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
jenkins_1    |  ... 43 more
```

**Comment by wumpz** [comment]
Here are more classes, that cannot be serialized:

com.github.dockerjava.api.command.InspectContainerResponse
com.github.dockerjava.api.model.ContainerConfig
com.github.dockerjava.api.model.HostConfig
com.github.dockerjava.api.model.Binds
com.github.dockerjava.api.model.Bind
com.github.dockerjava.api.model.Volume
com.github.dockerjava.api.model.LogConfig
com.github.dockerjava.api.model.Ports
com.github.dockerjava.api.model.RestartPolicy
com.github.dockerjava.api.model.NetworkSettings
com.github.dockerjava.api.model.ContainerNetwork
com.github.dockerjava.api.command.InspectContainerResponse$ContainerState

**Comment by bulanovk** [comment]
Additional Classes:
com.github.dockerjava.api.model.ExposedPorts

**Comment by u2g-tg** [comment]
Yup, this Docker plugin is now broken by the new Jenkins blacklist->whitelist for marshalling objects 

There is a workaround to add a JVM parameter to the Jenkins Server to add the classes to the whitelist (must add them all individually, ugh) 

```-Dhudson.remoting.ClassFilter=com.github.dockerjava.api.command.InspectContainerResponse,com.github.dockerjava.api.model.ContainerConfig,com.github.dockerjava.api.model.HostConfig,com.github.dockerjava.api.model.Binds,com.github.dockerjava.api.model.Bind,com.github.dockerjava.api.model.Volume,com.github.dockerjava.api.model.LogConfig,com.github.dockerjava.api.model.Ports,com.github.dockerjava.api.model.RestartPolicy,com.github.dockerjava.api.model.NetworkSettings,com.github.dockerjava.api.model.ContainerNetwork,com.github.dockerjava.api.command.InspectContainerResponse$ContainerState,com.github.dockerjava.api.model.ExposedPorts,com.github.dockerjava.api.model.ExposedPort```

**Comment by wumpz** [comment]
This workaround does not work at least for me. It does not accept subclasses the ones with $.

**Comment by bulanovk** [comment]
You could try to switch off whitelist using -Djenkins.security.ClassFilterImpl.SUPPRESS_WHITELIST=true

**Comment by wumpz** [comment]
@bulanovk OK, I will give it a try, since my jenkins instance is in office only its a way to go.

**Comment by wumpz** [comment]
@bulanovk The suppress whitelist parameter does the job for me. 
👍

**Comment by oleg-nenashev** [comment]
Hi guys. If you see JEP-200 regressions, please report them according to the suggestions in blogposts (e.g. see https://jenkins.io/blog/2018/03/15/jep-200-lts/#reporting-jep-200-issues). JEP-200 Maintainers monitor Jenkins JIRA, but not GitHub. So we have never heard about this issue and have never registered it properly in Wiki pages. If there was a JIRA ticket, we could have got a release of the fix more than 1 month ago

CC @bulanovk @sadovnikov @jglick

**Comment by oleg-nenashev** [comment]
Yes, the discussions got split-brained a bit. I will work with @ndeloof to agree on the next steps and to get it delivered

**Comment by Padma91** [comment]
We are getting below exceptions while running  the build flow jobs. We tried to whitelist in the build flow and dsl plugin but still same error persist

Caused by: java.lang.RuntimeException: Failed to serialize com.cloudbees.plugins.flow.FlowCause#associatedJob for class com.cloudbees.plugins.flow.FlowCause
        at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:256)
        at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
        at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
        at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
        at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
        at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
        at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
        at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
        at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:88)
        at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:64)
        at com.thoughtworks.xstream.converters.collections.MapConverter.marshal(MapConverter.java:78)
        at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
        at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
        at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
        at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
        at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
        ... 39 more
Caused by: java.lang.RuntimeException: Failed to serialize com.cloudbees.plugins.flow.JobInvocation#lock for class com.cloudbees.plugins.flow.JobInvocation
        at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:256)
        at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
        at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
        at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
        at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
        at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
        at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
        at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
        at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
        at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
        ... 54 more
Caused by: java.lang.UnsupportedOperationException: Refusing to marshal java.util.concurrent.locks.ReentrantLock for security reasons; see https://jenkins.io/redirect/class-filter/
        at hudson.util.XStream2$BlacklistedTypesConverter.marshal(XStream2.java:546)
        at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
        at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
        at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
        at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
        at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
        ... 63 more

Apr 17, 2019 6:46:49 AM hudson.model.Run execute
SEVERE: Failed to save build record
java.io.IOException: java.lang.RuntimeException: Failed to serialize hudson.model.Actionable#actions for class hudson.model.FreeStyleBuild
        at hudson.XmlFile.write(XmlFile.java:200)
        at hudson.model.Run.save(Run.java:2006)
