### ISSUE TITLE
Provision & Start Container build step doesn't work

### ISSUE THREAD

**Issue by vjuranek** [jenkinsci/docker-plugin#64]
It doesn't store `Docker Cloud name` and results into following exception:

```
FATAL: Cannot list cloud for docker action
java.lang.RuntimeException: Cannot list cloud for docker action
    at com.nirima.jenkins.plugins.docker.builder.DockerBuilderControlCloudOption.getCloud(DockerBuilderControlCloudOption.java:35)
    at com.nirima.jenkins.plugins.docker.builder.DockerBuilderControlOptionProvisionAndStart.execute(DockerBuilderControlOptionProvisionAndStart.java:25)
    at com.nirima.jenkins.plugins.docker.builder.DockerBuilderControl.perform(DockerBuilderControl.java:60)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:772)
    at hudson.model.Build$BuildExecution.build(Build.java:199)
    at hudson.model.Build$BuildExecution.doRun(Build.java:160)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:535)
    at hudson.model.Run.execute(Run.java:1732)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:88)
    at hudson.model.Executor.run(Executor.java:234)
```

**Comment by kummerer94** [comment]
+1
Still seeing this issue. I don't really know what to do to fix this.

**Comment by haysclark** [comment]
+1
Seeing this issue for "Start Container" using basic evarga/jenkins-slave container id.

Docker Plug-in 0.8
Docker 1.5.0
Running official Jenkins container

**Comment by wusel42** [comment]
+1.

Docker Plug-in 0.8 does not save the cloud information except for "run" (fields are empty each time you re-enter the config dialouge).

**Comment by Micheal-Github** [comment]
Hi,
Any workaround for this issue? 

FATAL: Cannot list cloud for docker action
java.lang.RuntimeException: Cannot list cloud for docker action
    at com.nirima.jenkins.plugins.docker.builder.DockerBuilderControlCloudOption.getCloud(DockerBuilderControlCloudOption.java:35)
    at com.nirima.jenkins.plugins.docker.builder.DockerBuilderControlOptionProvisionAndStart.execute(DockerBuilderControlOptionProvisionAndStart.java:25)
    at com.nirima.jenkins.plugins.docker.builder.DockerBuilderControl.perform(DockerBuilderControl.java:60)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:772)
    at hudson.model.Build$BuildExecution.build(Build.java:199)
    at hudson.model.Build$BuildExecution.doRun(Build.java:160)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:535)
    at hudson.model.Run.execute(Run.java:1732)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:88)
    at hudson.model.Executor.run(Executor.java:234)
