### ISSUE TITLE
ConflictException from docker-java when starting many containers at once

### ISSUE THREAD

**Issue by PeppyHare** [jenkinsci/docker-plugin#647]
Please don't use the issue tracker to ask questions, join jenkins-users mailing list.

If you get some troubles with docker-plugin, please report
 - [x] docker-plugin version you use: `docker-plugin-1.1.4`
 - [x] jenkins version you use: `2.107.1`
 - [x] docker engine version you use: `Version = swarm/1.2.8, API Version = 1.22, Docker 17.09.0-ce`
 - [x] stack trace / logs / any technical details that could help diagnose this issue

We are using the docker-plugin for basically all builds in a fairly large Jenkins installation (~70k builds / day). We infrequently (~5/day) see the following in the Jenkins log, followed by an automatic 5-minute "disabling" of a docker template by the plugin:

```
May 09, 2018 3:46:03 PM com.nirima.jenkins.plugins.docker.DockerCloud$1 run
SEVERE: Error in provisioning; template='DockerTemplate{configVersion=2, labelString='old-sl sl swarm_node sl_swarm_node sl_always_online sl_swarm_node_latest', connector=io.jenkins.docker.connector.DockerComputerSSHConnector@36cee2cb, remoteFs='/home/jenkins', instanceCap=500, mode=EXCLUSIVE, retentionStrategy=com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy@3ec64559, dockerTemplateBase=DockerTemplateBase{image='taas-docker-public.artifactory.swg-devops.com/swarm/dk-jenkins-slave:latest', pullCredentialsId='public.shared.artifactory.docker.registry.username.password', registry=null, dockerCommand='./setup_slave.sh', hostname='', dnsHosts=[9.9.9.9], network='', volumes=[], volumesFrom2=[], environment=[], bindPorts='', bindAllPorts=false, memoryLimit=null, memorySwap=null, cpuShares=null, privileged=true, tty=false, macAddress='null', extraHosts=[]}, removeVolumes=true, pullStrategy=PULL_NEVER, nodeProperties=[], disabled=BySystem,1 ms,4 min 59 sec,Template provisioning failed.}' for cloud='taas-internal-swarm'
com.github.dockerjava.api.exception.ConflictException: Conflict: The name 25bf9974eba5b0 is already assigned. You have to delete (or rename) that container to be able to assign 25bf9974eba5b0 to a container again.

	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:107)
	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:33)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
```

I suspect the problem lies in how the plugin chooses a name for each container: https://github.com/jenkinsci/docker-plugin/blob/master/src/main/java/com/nirima/jenkins/plugins/docker/DockerTemplate.java#L492-L495. The container names are chosen by hashing System.nanoTime(), but per https://docs.oracle.com/javase/8/docs/api/java/lang/System.html#nanoTime-- the available resolution for System.nanoTime() is only guaranteed to be "least as good as that of currentTimeMillis()," and so we may be finding a collision there.

**Comment by pjdarton** [comment]
I've been investigating and the problem is deeper than just the uniqueness of `nanoTime()`.
The docker plugin is specifying the name of the container, rather than leaving it empty and allowing the docker daemon itself to choose a unique name, so it needs to come up with a name that isn't just unique within the scope of the Jenkins docker plugin, but is unique within the scope of the docker daemon itself.
 - Docker container names must be unique with the scope of the docker engine that's running it.
 - Jenkins slave names must be unique within the scope of the Jenkins instance the slave belongs to.
 - *BUT* a docker engine can be shared between multiple Jenkins instances.
 - *AND* a Jenkins instance can talk to multiple docker engines.
i.e. coming up with something that's unique across the scope of multiple systems that don't talk to each other is tricky.

The way I see it, we have three options:
1) Let docker choose the container name.
 - Pros:
   - Makes the uniqueness issue purely docker's responsibility, not the plugin's. Nice and simple.
   - Container creation should work first time every time.
 - Cons:
   - Have to tweak the JNLP connector to calculate the slave name some other way.
     - Mitigation: We already store Jenkins meta-data in docker labels, we could put the slave name there with relative ease.
   - Makes it more difficult for a human operator to trace a container back to its Jenkins instance as they'll have to inspect the container instead of just looking at the name.
     - Mitigation: The existing container name doesn't tell you which Jenkins server a container belongs to anyway - if you have more than one Jenkins instance, you'll have to inspect the container anyway.
     - Mitigation: You can still trace from the Jenkins slave to the docker container as that tells you the ID.
2) Enhance the start-container logic to look out for this exception coming from the create-container command and try a new name if that happens.
  - Pros:
    - Humans can identify which container is which slave just from the name (if they only have one Jenkins server it could be from).
    - No need to modify the JNLP connector code.
  - Cons:
    - Complex functionality is required to safely retry without sometimes leaking containers.
     - Mitigation: We've got retry loops elsewhere; this isn't a new idea, but it is the first time we're retrying a remote operation.
    - Performance hit every time we get a naming collision.
    - If the retry logic is deterministic, multiple colliding Jenkins servers will continue to collide with each other and we'll still get a failure despite retries (and non-deterministic logic isn't nice).
3) Ignore the problem and live with the occasional failures
  - Pros:
    - No changes required.
  - Cons:
    - Leaves a source of unreliability in the plugin.
    - Causes a performance hit whenever a naming collision happens.
    - We'd have to make the "stop using that for 5 minutes" duration configurable in order to minimize its impact.

I guess it all depends on how much we value being able to easily trace a docker container back to its "owner".  At present, a human operator can take the name of a docker container and search the Jenkins node names for that name.  However, they'll have to search every Jenkins that uses that docker daemon, as they'll all use exactly the same kind of names - to be sure we're looking at the correct Jenkins, one would have to "docker inspect" the container to see the labels.

My personal "ideal" would be to disconnect container names (which need to be unique within a docker daemon) from Jenkins slave names (which need to be unique with a Jenkins server), make the Jenkins slave names configurable (not just "docker-xxxxx"), store the Jenkins slave name in a docker label so it's still easily traceable who's who, and let each docker daemon choose unique names itself.

@ndeloof What do you think?  Is having Jenkins set the container name really important to you?  I know that the current JNLP connector relies on it, but if we assume that we can code around that and make it a non-issue, do you want the container names set or was doing that merely done to make it easy for JNLP?

**Comment by PeppyHare** [comment]
👍 for tracing the node name backwards using a docker label. On the point of traceability and speaking from our experience, we already heavily rely on using the "JenkinsId" docker label to trace an individual docker container back to its origin and haven't found that process to be too troublesome. Having the Jenkins slave name similarly available would give some nice additional traceability back to the particular build(s) a container was responsible for, and would do so in a similar fashion to the currently-available metadata.

**Comment by ndeloof** [comment]
The initial intent was for agent name to use the container ID, so that the agent name in log gives you immediate information about the container being used, and the concept of "label" disappears behind just containers. But docker API lifecycle don't let us get the container ID _then_ configure command being ran, and this has been changed to this UUID-like agent ID. 

Using a label to track agent/container is a nice idea (I'd like we use them as well when collecting orphaned containers, but unfortunately this feature relies on some jackson code excluded from docker-java-api-plugin.

**Comment by pjdarton** [comment]
@ndeloof I believe that I can make this "nice idea" happen :-)

I coded a workaround to the jackson-code/docker-java-api issue (for docker labels only) back in #616.  A "proper fix" would require the same kind of changes to be applied to multiple places within the docker-java library, but the docker-plugin has enough of a workaround to get the docker-label code working.
This means that we can (and already do) use docker labels on the docker containers.  e.g. Since #616 every container is labelled with details of the Jenkins server it belongs to.

Re: The docker API not allowing us to configure the container CMD after we've started it:  Understood; I've looked at the code there and I understand the challenge - the container needs to be given the name of the Jenkins slave node name so that the JNLP code can function correctly.
However, if the code passed the Jenkins slave name to the JNLP code some other way (e.g. via a docker label), the JNLP code is able to function correctly even if the container name does not match the Jenkins slave node name.

So the only remaining reason (for setting the container name to match the Jenkins slave node name) is to make it easier for us (system administrators) to make sense of things...
 - We can already trace from a Jenkins slave node to a container because the slave states the docker API URL and the container ID in the description
 - if we set the Jenkins slave name (as well as the Jenkins URL) in docker labels then that would allow us to trace from a docker container to the Jenkins instance and slave.
i.e. problem solved :-)


I think we can do this.  I'll make a PR...
(and if it all works it will also make it possible to automate the collection of orphaned containers, which would be cool)

**Comment by pjdarton** [comment]
OK, I've created #651.  You'll find a build of the hpi file [here](https://ci.jenkins.io/job/Plugins/job/docker-plugin/job/PR-651/lastSuccessfulBuild/artifact/target/).

@ndeloof Please take a look at the code changes and tell me if you like what it looks like, and also try out the code and see if you like the results.  If you do like it, feel free to merge it without further comment.  If you don't like it then please let me know your concerns and I'll see what can be done to address the issues raised.

@PeppyHare and @fraz3alpha Please test the hpi file on your (busy) server and let me know how it goes.  I hope that this will have eliminated the last trace of "random but infrequent" exceptions but, if not, let me know (including stacktraces) and we can go bug-hunting again.

**Comment by PeppyHare** [comment]
I'd say we're quite happy! We've been running Peter's build since the morning of the 13th, and the com.github.dockerjava.api.exception.ConflictException hasn't shown up since. Our average queue wait times don't seem to have suffered either.

**Comment by pjdarton** [comment]
`Error response from daemon: endpoint with name fervent_visvesvaraya already exists in network bridge`?  That is odd...

My guess is that `fervent_visvesvaraya` is the container name that the docker daemon came up with.
Unless your template defines particular network stuff, I suspect that this is an error coming from the docker daemon caused by the docker daemon failing (internally) to create an otherwise-perfectly-valid container.
The only cure for this would be to fix the bug in the docker daemon :-/

I guess a good way of _mitigating_ this would be to make the 5-minute back-off period configurable so that folks with just one cloud can tell the docker-plugin to "just keep trying".  Dammit, I was hoping I could avoid doing that work...

Conclusion:
It seems that PR #651 is good, in that it fixes all the issues except where the docker daemon itself is the problem, but we really would like that 5-minute back-off period (that I hard-coded) made configurable.  I'll get on with that once I've cleared the stuff I'm currently working on.

**Comment by pjdarton** [comment]
I've updated PR #651 so that the 5-minute back-off period is now configurable.
