### ISSUE TITLE
getting error while running in jenkins

### ISSUE THREAD

**Issue by nandipatianil** [jenkinsci/docker-plugin#668]
Hi..
Can you please help me here how do I resolve this.

java.lang.NoClassDefFoundError: org/jenkinsci/plugins/workflow/job/WorkflowRun
at org.jenkinsci.plugins.workflow.job.WorkflowJob$SCMListenerImpl.onCheckout(WorkflowJob.java:750)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:609)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Finished: FAILURE

**Comment by pjdarton** [comment]
- Looks like class `org.jenkinsci.plugins.workflow.job.WorkflowRun` wasn't found.  Do you have the pipeline plugin(s) installed?
 - Looks like it's got nothing to do with the docker plugin - there's no code in that stacktrace from this plugin.
