### ISSUE TITLE
Can't get image jenkins/jnlp-slave with JNLP to work

### ISSUE THREAD

**Issue by bhoppeadoy** [jenkinsci/docker-plugin#671]
I'm unable to get jenkins to start docker container with JNLP.  

Jenkins 2.132
Docker-Plugin 1.1.5-rc592.907a3144f989 (tried 1.1.4 as well)
Docker Version: 1.12.6 API version: 1.24

I have docker plugin setup with mostly default settings. 
Labels: slave-docker
Name: docker
Docker Image docker.io/jenkins/jnlp-slave:latest
Remote Root: /home/jenkins
Connect with JNLP

I've pulled down jenkins/jnlp-slave image and set pull strategy to never pull.  I'm using pipeline and I can see the docker container start (docker ps -a) but then its removed. Here's the build console output:
`
[Pipeline] node
Running on docker-008s1dq46jht0 on Lewisville Docker in /home/jenkins/workspace/docker-test
[Pipeline] {
[Pipeline] sh
[docker-test] Running shell script
+ docker inspect -f . jenkins/jnlp-slave
/home/jenkins/workspace/docker-test@tmp/durable-bbbcdcb2/script.sh: 2: /home/jenkins/workspace/docker-test@tmp/durable-bbbcdcb2/script.sh: docker: not found
[Pipeline] sh
[docker-test] Running shell script
+ docker pull jenkins/jnlp-slave
/home/jenkins/workspace/docker-test@tmp/durable-5886619f/script.sh: 2: /home/jenkins/workspace/docker-test@tmp/durable-5886619f/script.sh: docker: not found
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 127
Finished: FAILURE
`

Here's the Jenkins log:
`
Jul 17, 2018 12:55:32 AM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
Asked to provision 1 slave(s) for: slave-docker
Jul 17, 2018 12:55:32 AM INFO com.nirima.jenkins.plugins.docker.DockerCloud canAddProvisionedSlave
Provisioning 'docker.io/jenkins/jnlp-slave:latest' on 'Lewi Docker'; Total containers: 0 (of 100)
Jul 17, 2018 12:55:32 AM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
Will provision 'docker.io/jenkins/jnlp-slave:latest', for label: 'slave-docker', in cloud: 'Lewi Docker'
Jul 17, 2018 12:55:32 AM INFO hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
Started provisioning Image of docker.io/jenkins/jnlp-slave:latest from Lewi Docker with 1 executors. Remaining excess workload: 0
Jul 17, 2018 12:55:32 AM INFO com.nirima.jenkins.plugins.docker.DockerTemplate doProvisionNode
Trying to run container for docker.io/jenkins/jnlp-slave:latest
Jul 17, 2018 12:55:32 AM INFO com.nirima.jenkins.plugins.docker.DockerTemplate doProvisionNode
Trying to run container for node docker-008s1dq46jht0 from image: docker.io/jenkins/jnlp-slave:latest
Jul 17, 2018 12:55:32 AM INFO com.nirima.jenkins.plugins.docker.DockerTemplate doProvisionNode
Started container ID 34f5009ed64e591fa6e6712359532e65e5c447678cab9101aecbb598645df15d for node docker-008s1dq46jht0 from image: docker.io/jenkins/jnlp-slave:latest
Jul 17, 2018 12:55:33 AM INFO hudson.TcpSlaveAgentListener$ConnectionHandler run
Accepted JNLP4-connect connection #8 from lelvdck0005/10.180.168.192:56976
Jul 17, 2018 12:55:36 AM INFO hudson.slaves.NodeProvisioner$2 run
Image of docker.io/jenkins/jnlp-slave:latest provisioning successfully completed. We have now 4 computer(s)
Jul 17, 2018 12:55:38 AM INFO io.jenkins.docker.DockerTransientNode$1 println
Disconnected computer for slave 'docker-008s1dq46jht0'.
Jul 17, 2018 12:55:38 AM WARNING jenkins.slaves.DefaultJnlpSlaveReceiver channelClosed
Computer.threadPoolForRemoting [#166] for docker-008s1dq46jht0 terminated
java.nio.channels.ClosedChannelException
	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onReadClosed(ChannelApplicationLayer.java:209)
	at org.jenkinsci.remoting.protocol.ApplicationLayer.onRecvClosed(ApplicationLayer.java:222)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:832)
	at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:287)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:181)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.switchToNoSecure(SSLEngineFilterLayer.java:283)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processWrite(SSLEngineFilterLayer.java:503)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processQueuedWrites(SSLEngineFilterLayer.java:248)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doSend(SSLEngineFilterLayer.java:200)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doCloseSend(SSLEngineFilterLayer.java:213)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.doCloseSend(ProtocolStack.java:800)
	at org.jenkinsci.remoting.protocol.ApplicationLayer.doCloseWrite(ApplicationLayer.java:173)
	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer$ByteBufferCommandTransport.closeWrite(ChannelApplicationLayer.java:314)
	at hudson.remoting.Channel.close(Channel.java:1450)
	at hudson.remoting.Channel.close(Channel.java:1403)
	at hudson.slaves.SlaveComputer.closeChannel(SlaveComputer.java:819)
	at hudson.slaves.SlaveComputer.access$800(SlaveComputer.java:105)
	at hudson.slaves.SlaveComputer$3.run(SlaveComputer.java:737)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Jul 17, 2018 12:55:38 AM INFO io.jenkins.docker.DockerTransientNode$1 println
Removed Node for slave 'docker-008s1dq46jht0'.
Jul 17, 2018 12:55:38 AM INFO org.jenkinsci.plugins.workflow.job.WorkflowRun finish
docker-test #2 completed: FAILURE
Jul 17, 2018 12:55:38 AM INFO io.jenkins.docker.DockerTransientNode$1 println
Stopped container '34f5009ed64e591fa6e6712359532e65e5c447678cab9101aecbb598645df15d' for slave 'docker-008s1dq46jht0'.
Jul 17, 2018 12:55:38 AM INFO io.jenkins.docker.DockerTransientNode$1 println
Removed container '34f5009ed64e591fa6e6712359532e65e5c447678cab9101aecbb598645df15d' for slave 'docker-008s1dq46jht0'.
`
What am I missing here that this isn't working?

**Comment by pjdarton** [comment]
Looks like it's being terminated before it's had a chance to start building anything.
I'd suggest you look for an "idle timeout" or similar settings and ensure they're not zero.
(I thought I'd fixed that bug; other folks thought they'd fixed it before I did; maybe we all missed something... If you find the setting that does the trick, please say which one)

**Comment by bhoppeadoy** [comment]
@pjdarton I read other places about the "idle timeout" missing default values before so I did make sure they're all there. Plus, idle timeout is set in minutes whereas every other timeout is in seconds. So just in case it wasn't minutes but in fact seconds I set to 300 (same as all other timeouts). Same error. It doesn't look like a timeout issue.

**Comment by bhoppeadoy** [comment]
Here's my simple pipeline script that I'm using:

`pipeline {
    agent {
        docker {
            label 'slave-docker'
            image 'jnlp-slave'
        }
    }
    stages {     
        stage ('Prepare') {
            steps {
                script {
                    echo "TESTING DOCKER"
                }
            }
        }
    }
}`

I don't understand why this is happening:

`[Pipeline] sh
[docker-test] Running shell script
+ docker pull jenkins/jnlp-slave
/home/jenkins/workspace/docker-test@tmp/durable-5886619f/script.sh: 2: /home/jenkins/workspace/docker-test@tmp/durable-5886619f/script.sh: docker: not found
[Pipeline]`

Why is it running docker pull? I set the strategy to never pull.

**Comment by bhoppeadoy** [comment]
I'm using a remote docker host, but it looks like the Jenkins server is trying to run docker. Does Jenkins server need docker executable installed locally?

**Comment by pjdarton** [comment]
I believe that, by using that pipeline syntax (as documented [here](https://jenkins.io/doc/book/pipeline/docker/)), you're using the `docker-workflow` plugin and not the `docker-plugin` plugin.
I'm not familiar with the `docker-workflow` plugin but you'll find further details on its [wiki page](https://plugins.jenkins.io/docker-workflow).

FYI the `docker-plugin` plugin (i.e. the one this github area is for) does _not_ run any docker commands.  It uses the `docker-java` library (which is a docker client written in Java) to talk to the docker server(s) it's configured to talk to.  I don't know what the `docker-workflow` uses to talk to docker servers, but it is possible that it requires a docker client.

**Comment by bhoppeadoy** [comment]
@pjdarton OK, so using this:

```
    agent {
         label 'slave-docker'
    }
```

instead of this

```
    agent {
        docker {
            label 'slave-docker'
            image 'jnlp-slave'
        }
    }
```

Is what got it working. So difficult to find the correct pipeline syntax to use.
