### ISSUE TITLE
Cannot use DockerBuilderNewTemplate in a pipeline

### ISSUE THREAD

**Issue by Benoit-DunandLaisin** [jenkinsci/docker-plugin#703]
- [ ] docker-plugin version 1.1.5
 - [ ] jenkins version 2.150.1
 - [ ] docker engine version 18.06.1-ce, build e68fc7a
 - [ ] details:
I wrote a multibranch pipeline to build/push docker images and add them to docker cloud.
Even if 'DockerBuilderNewTemplate' is described as [pipeline step](https://jenkins.io/doc/pipeline/steps/workflow-basic-steps), the job fails with the stack trace below.
- [ ] pipeline steps (partial):
```
step([$class                     : 'DockerBuilderPublisher',
      cleanImages                : false,
      cleanupWithJenkinsJobDelete: false,
      cloud                      : '', 
      dockerFileDirectory        : '.',
      pushOnSuccess              : true,
      tagsString                 : "${env.DOCKER_PUSH_REPOSITORY}/${image_name}:${cleaned_branch}",
      pushCredentialsId          : 'nexus_docker'])
def docker_template_base = [ 
    $class        : 'DockerTemplateBase',
    image         : "${image_name}:${cleaned_branch}"]
def docker_template = [ 
    name                : image_name,
    dockerTemplateBase  : docker_template_base,
    labelsString        : image_name.replaceAll('/', ' '), 
    disabled            : false]
step([$class            : 'DockerBuilderNewTemplate',
      dockerTemplate    : docker_template])
```

 - [ ] stack trace
```
java.lang.UnsupportedOperationException: no known implementation of interface jenkins.tasks.SimpleBuildStep is named DockerBuilderNewTemplate
	at org.jenkinsci.plugins.structs.describable.DescribableModel.resolveClass(DescribableModel.java:478)
	at org.jenkinsci.plugins.structs.describable.DescribableModel.coerce(DescribableModel.java:402)
	at org.jenkinsci.plugins.structs.describable.DescribableModel.buildArguments(DescribableModel.java:341)
	at org.jenkinsci.plugins.structs.describable.DescribableModel.instantiate(DescribableModel.java:282)
	at org.jenkinsci.plugins.workflow.steps.StepDescriptor.newInstance(StepDescriptor.java:201)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:264)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:178)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:157)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:155)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:155)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:159)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:129)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:129)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:129)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:129)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:129)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:129)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
```
- [ ] Note: It looks like the DockerBuilderNewTemplate doesn't implement SimpleBuildStep interface

**Comment by pjdarton** [comment]
Correct; `DockerBuilderNewTemplate` simply `extends Builder`, it does not `implement SimpleBuildStep`.
FYI this code pre-dates widespread SimpleBuildStep usage and has largely been rendered obsolete by the functionality that pipelines allow.

If you're writing pipeline code, you're better off reconfiguring the DockerCloud templates directly.  That way, your code can choose what to do when clouds already exist, when templates already exist etc.

**Comment by pjdarton** [comment]
...alternatively, if you're writing pipeline code, I'd suggest that you look at the [docker-workflow](https://plugins.jenkins.io/docker-workflow) plugin, not this one.
