### ISSUE TITLE
Can't pull image by digest -- "invalid reference format"

### ISSUE THREAD

**Issue by jakub-bochenski** [jenkinsci/docker-plugin#709]
I was trying to pull image by digest, which failed.
Apparently the plugin is adding `:latest` tag making the URL invalid
```
Pulling image '1234567.dkr.ecr.eu-west-1.amazonaws.com/jenkins/slave-libaio1@ab43ed9b632681cbd8414a7832d9031ad1c94863f490244cbec840cbc10fcaf0:latest'. This may take awhile...

Dec 18, 2018 5:44:11 PM SEVERE com.github.dockerjava.core.async.ResultCallbackTemplate onError

Error during callback
com.github.dockerjava.api.exception.BadRequestException: {"message":"invalid reference format"}

	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:99)
	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:33)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
```

Docker plugin 1.1.6-rc867.6e6f38dd6134 
Jenkins ver. 2.138.2

**Comment by pjdarton** [comment]
Hmm, you're right - the plugin was never intended to use digests, but I agree that it's a bit awkward and the addition of ":latest" is somewhat "invisible functionality".

My guess is that this could be difficult to fix without significant effort - all existing users are probably used to being able to just type the name of the image without ":latest" and have the plugin add it for them, so removing this functionality would break things.
I guess it'd be possible to have the plugin edit its own config to add :latest on the next upgrade (thus allowing users who don't want ":latest" in the image name to remove it), but configuration changes are always a tricky thing to get right...

If there's a particular regex by which one could recognize a digest (which does _not_ match under any other circumstance) then I guess the code that adds `:latest` could be made conditional fairly easily ... but ideally we'd also have some UI validation code warning folks that they'll get `:latest` appended.

Support for digests isn't something I've ever needed myself, but I agree that it could be useful to have, so I'm open to a PR that fixes this (the smaller/simpler the better, with unit-tests).

**Comment by jakub-bochenski** [comment]
I might be missing something, but can't the pattern simply look for something like `@[a-Z0-9]{64}`?

I tried but couldn't find any hard definition of how a digest can look like in docker documentation. However in the practice it's always 64 hex characters

**Comment by nilsmahlstaedt** [comment]
Just ran into this problem while working on a plugin.

The bit of code in question is: https://github.com/jenkinsci/docker-plugin/blob/master/src/main/java/com/nirima/jenkins/plugins/docker/DockerTemplateBase.java#L898

The [NameParser ](https://github.com/docker-java/docker-java/blob/master/docker-java-core/src/main/java/com/github/dockerjava/core/NameParser.java) will provided by the docker java dependency will honor the digest and will return a [ReposTag](https://github.com/docker-java/docker-java/blob/f9d2db6efff4d7fc7092b53209027d6846de1894/docker-java-core/src/main/java/com/github/dockerjava/core/NameParser.java#L52) that correctly has no tag set, as there is none (a digest is used). This in turn causes the Function [DockerTemplateBase.getFullIageId](https://github.com/jenkinsci/docker-plugin/blob/master/src/main/java/com/nirima/jenkins/plugins/docker/DockerTemplateBase.java#L898) to substitute the empty tag with `latest`.

A possible quick fix could be that the replacement for an empty tag will only be done if the image does not contains the substring `@sha256:` which is the same as what the name parser is doing anyway (quite literally!)

More involved idea: only do the latest thing if the Image Name (the repo part without registry/host) does NOT contain a ':' char. It can be extracted from the image string through [docker java's NameParser](https://github.com/docker-java/docker-java/blob/f9d2db6efff4d7fc7092b53209027d6846de1894/docker-java-core/src/main/java/com/github/dockerjava/core/NameParser.java#L101) aswell, using the resolveRepositoryName function. An existing tag not found by the NameParser has to be delimited from the image by a colon.

If you want, I can send you a pull request

**Comment by pjdarton** [comment]
I'd welcome a PR that resolved this ... as long as it doesn't break anything else while doing so 😉 
Unit test(s) for any new functionality is also highly desirable too.
See the [contribution guide](https://github.com/jenkinsci/docker-plugin/blob/master/CONTRIBUTING.md) for more details.

**Comment by nilsmahlstaedt** [comment]
@pjdarton 
any updates on the PR

**Comment by pjdarton** [comment]
Sorry for the delay - was on vacation.
PR looks good to me; now merged.

i.e. This will be fixed in the next release.

**Comment by nilsmahlstaedt** [comment]
Awesome, thanks for maintaining this useful project!
