### ISSUE TITLE
Null value not allowed as an environment variable: DOCKER_CONTAINER_ID

### ISSUE THREAD

**Issue by cpfeiffer** [jenkinsci/docker-plugin#759]
- docker-plugin 1.1.8
- matrix project plugin 1.1.4
- build name and description setter 2.0.3
- token macro plugin 2.10
- Jenkins 2.190.2

~~This probably happens early when there is no node yet, so `getEnvironment()` should make this an empty string in that case.~~
Actually this happens at the end of the build. We configured
`Set build name before build starts` and NOT 
`Set build name after build ends`, so  I don't quite understand why this happens in endBuild().
```
java.lang.IllegalArgumentException: Null value not allowed as an environment variable: DOCKER_CONTAINER_ID
	at hudson.EnvVars.put(EnvVars.java:379)
	at io.jenkins.docker.DockerComputer.getEnvironment(DockerComputer.java:51)
	at jenkins.model.CoreEnvironmentContributor.buildEnvironmentFor(CoreEnvironmentContributor.java:30)
	at hudson.model.Run.getEnvironment(Run.java:2350)
	at hudson.model.AbstractBuild.getEnvironment(AbstractBuild.java:864)
	at org.jenkinsci.plugins.tokenmacro.TokenMacro.expandAll(TokenMacro.java:220)
	at org.jenkinsci.plugins.tokenmacro.TokenMacro.expandAll(TokenMacro.java:207)
	at org.jenkinsci.plugins.buildnamesetter.Executor.evaluateMacro(Executor.java:75)
	at org.jenkinsci.plugins.buildnamesetter.Executor.setName(Executor.java:30)
	at org.jenkinsci.plugins.buildnamesetter.BuildNameSetter$2.endBuild(BuildNameSetter.java:117)
	at hudson.matrix.MatrixBuild$MatrixBuildExecution.post2(MatrixBuild.java:433)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1840)
	at hudson.matrix.MatrixBuild.run(MatrixBuild.java:323)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
```

**Comment by pjdarton** [comment]
Code changes went into released of docker-plugin version 1.1.9
