### ISSUE TITLE
Possible file descriptor leak due to #782

### ISSUE THREAD

**Issue by cpfeiffer** [jenkinsci/docker-plugin#786]
- docker-plugin 1.1.9
- docker-java-api 3.1.5
- jenkins 2.204.6
- docker 18.06.3-ce
- docker-connection via tcp://
- slave connection via ssh

We experienced a leak of file descriptors since the update to the above plugin versions (causing the NoClassDefFoundErrors com/github/dockerjava/netty/WebTarget as seen in #782).

The below stacktrace does not necessarily point to the leak, but merely to the place where the limit was first reached.

```
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]: java.io.IOException: Too many open files
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]:     at java.base/sun.nio.ch.EPoll.create(Native Method)
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]:     at java.base/sun.nio.ch.EPollSelectorImpl.<init>(EPollSelectorImpl.java:79)
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]:     at java.base/sun.nio.ch.EPollSelectorProvider.openSelector(EPollSelectorProvider.java:36)
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]:     at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:166)
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]: Caused: io.netty.channel.ChannelException: failed to open a new selector
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]:     at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:168)
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]:     at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:142)
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]:     at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:127)
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]:     at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36)
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]:     at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]: Caused: java.lang.IllegalStateException: failed to create a child event loop
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]:     at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:88)
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]:     at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]:     at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]:     at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]:     at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77)
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]:     at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72)
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]:     at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59)
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]:     at io.jenkins.docker.client.NettyDockerCmdExecFactory$InetSocketInitializer.init(NettyDockerCmdExecFactory.java:310)
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]:     at io.jenkins.docker.client.NettyDockerCmdExecFactory.init(NettyDockerCmdExecFactory.java:233)
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]:     at com.github.dockerjava.core.DockerClientImpl.withDockerCmdExecFactory(DockerClientImpl.java:193)
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]:     at com.github.dockerjava.core.DockerClientBuilder.build(DockerClientBuilder.java:45)
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]:     at io.jenkins.docker.client.DockerAPI.makeClient(DockerAPI.java:249)
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]:     at io.jenkins.docker.client.DockerAPI.getOrMakeClient(DockerAPI.java:199)
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]:     at io.jenkins.docker.client.DockerAPI.getClient(DockerAPI.java:168)
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]:     at io.jenkins.docker.client.DockerAPI.getClient(DockerAPI.java:151)
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]:     at com.nirima.jenkins.plugins.docker.DockerCloud.countContainersInDocker(DockerCloud.java:613)
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]:     at com.nirima.jenkins.plugins.docker.DockerCloud.canAddProvisionedSlave(DockerCloud.java:632)
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]:     at com.nirima.jenkins.plugins.docker.DockerCloud.provision(DockerCloud.java:352)
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]:     at hudson.slaves.NodeProvisioner$StandardStrategyImpl.apply(NodeProvisioner.java:725)
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]:     at hudson.slaves.NodeProvisioner.update(NodeProvisioner.java:332)
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]:     at hudson.slaves.NodeProvisioner.access$900(NodeProvisioner.java:63)
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]:     at hudson.slaves.NodeProvisioner$NodeProvisionerInvoker.doRun(NodeProvisioner.java:819)
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]:     at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:70)
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]:     at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]:     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]:     at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]:     at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]:     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]:     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Apr  3 10:27:27 host0125 16fef0b13d6f[1228]:     at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by ericcitaire** [comment]
docker-plugin 1.1.9 is not compatible with docker-java-api 3.1.5. 

I suggest you to :

- upgrade to docker-plugin 1.2.0 and docker-java-api 3.1.5.2

or

- downgrade to docker-java-api 3.0.14

**Comment by cpfeiffer** [comment]
Yes, that would fix the current symptom, but the leak will probably stay. The real fix would be to find the place(s) where a resource is not properly closed when an exception occurs (e.g. the NoClassDefFoundError).

**Comment by pjdarton** [comment]
I have some doubt those places are in the docker-plugin.
The docker-plugin caches the `DockerClient` connections that it _successfully_ creates ... but if it doesn't manage to obtain a connection in the first place then it's got nothing it can free up/dispose of.
I suspect that the issue will be buried deep inside the `docker-java` library (and may even be fixed in later releases of that library, although we're now rather wary of switching to different versions of that...)

By all means take a look through the [code](https://github.com/jenkinsci/docker-plugin/blob/docker-plugin-1.2.0/src/main/java/io/jenkins/docker/client/DockerAPI.java#L242-L250) and let me know if you can spot any easy improvements (and, ideally, submit a PR) but I think that what we've got "at this end" is as good as we can reasonably get.

**Comment by cpfeiffer** [comment]
Thanks for the pointer. 

After having a quick look it seems to me that the `NettyDockerCmdExecFactory` in https://github.com/jenkinsci/docker-plugin/blob/docker-plugin-1.2.0/src/main/java/io/jenkins/docker/client/DockerAPI.java#L247 should be closed (see here: https://github.com/docker-java/docker-java/blob/master/docker-java-transport-netty/src/main/java/com/github/dockerjava/netty/NettyDockerCmdExecFactory.java#L286)

**Comment by cpfeiffer** [comment]
So it is these few calls: 
```
at io.jenkins.docker.client.NettyDockerCmdExecFactory.init(NettyDockerCmdExecFactory.java:233)
at com.github.dockerjava.core.DockerClientImpl.withDockerCmdExecFactory(DockerClientImpl.java:193)
at com.github.dockerjava.core.DockerClientBuilder.build(DockerClientBuilder.java:45)
at io.jenkins.docker.client.DockerAPI.makeClient(DockerAPI.java:249)
```

`DockerClientImpl.withDockerCmdExecFactory()` should probably close the given factory when init() fails with an exception.
If `DockerClientImpl` doesn't do it, `DockerClientBuilder` -- as the provider of the factory -- would also have the possibility to close it.

**Comment by pjdarton** [comment]
I can't change code in the `com.github.dockerjava` package (and below) as that's not code in this plugin; this plugin's code is all in/under the `io.jenkins.docker` and `com.mirima.jenkins.plugins.docker` packages.
I can't change `io.jenkins.docker.client.NettyDockerCmdExecFactory` in this plugin either, as that code doesn't exist anymore 😉 

We can, however, change `io.jenkins.docker.client.DockerAPI`...

Take a look at https://github.com/jenkinsci/docker-plugin/pull/788/commits/7c0f48e404fe53e8912b3dbdfeb2249009bccc01#diff-a754d4ac91d54e84d61f054e543c9594R246
I think that addresses your concerns.

I would appreciate you feedback (either posted here, or in #788)

**Comment by cpfeiffer** [comment]
Thanks a lot for taking on this task! Yes, the diff looks excellent! :ok_hand:

**Comment by pjdarton** [comment]
OK, I'll merge it; it'll be fixed in the next release.
