### ISSUE TITLE
Cannot push to private artifactory using rtDockerPush

### ISSUE THREAD

**Issue by bhoppeadoy** [jenkinsci/docker-plugin#787]
- docker-plugin 1.2.0
 - docker-api-plugin 3.1.5.2
 - jenkins version 2.230
 - docker engine version 1.12.6, api 1.24
 - Connect using JNLP

This has been working before and now after some plugins were updated this no longer works. I'm unable to push my docker image to my private artifactory repository using rtDockerPush. 

I found issue #785 and thought it would solve my problem too so I updated plugin versions to those but the issue still persists.

Here's the stack trace:
```
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 10.180.168.192:56342
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1788)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:998)
		at org.jfrog.hudson.pipeline.common.docker.utils.DockerAgentUtils.pushImage(DockerAgentUtils.java:129)
		at org.jfrog.hudson.pipeline.common.executors.DockerExecutor.execute(DockerExecutor.java:70)
		at org.jfrog.hudson.pipeline.declarative.steps.docker.DockerPushStep$Execution.run(DockerPushStep.java:96)
		at org.jfrog.hudson.pipeline.declarative.steps.docker.DockerPushStep$Execution.run(DockerPushStep.java:71)
		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
		at hudson.security.ACL.impersonate(ACL.java:359)
		at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;C)V
	at com.google.common.io.BaseEncoding$Alphabet.<init>(BaseEncoding.java:458)
	at com.google.common.io.BaseEncoding$Base64Encoding.<init>(BaseEncoding.java:919)
	at com.google.common.io.BaseEncoding.<clinit>(BaseEncoding.java:322)
	at com.github.dockerjava.core.exec.AbstrDockerCmdExec.registryAuth(AbstrDockerCmdExec.java:45)
	at com.github.dockerjava.core.exec.AbstrDockerCmdExec.resourceWithAuthConfig(AbstrDockerCmdExec.java:77)
	at com.github.dockerjava.core.exec.PushImageCmdExec.execute0(PushImageCmdExec.java:39)
	at com.github.dockerjava.core.exec.PushImageCmdExec.execute0(PushImageCmdExec.java:16)
	at com.github.dockerjava.core.exec.AbstrAsyncDockerCmdExec.execute(AbstrAsyncDockerCmdExec.java:56)
	at com.github.dockerjava.core.exec.AbstrAsyncDockerCmdExec.exec(AbstrAsyncDockerCmdExec.java:21)
	at com.github.dockerjava.core.exec.AbstrAsyncDockerCmdExec.exec(AbstrAsyncDockerCmdExec.java:12)
	at com.github.dockerjava.core.command.AbstrAsyncDockerCmd.exec(AbstrAsyncDockerCmd.java:21)
	at org.jfrog.hudson.pipeline.common.docker.utils.DockerUtils.pushImage(DockerUtils.java:64)
	at org.jfrog.hudson.pipeline.common.docker.utils.DockerAgentUtils$2.call(DockerAgentUtils.java:137)
	at org.jfrog.hudson.pipeline.common.docker.utils.DockerAgentUtils$2.call(DockerAgentUtils.java:129)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:97)
	at java.lang.Thread.run(Thread.java:748)
Caused: java.io.IOException: Remote call on JNLP4-connect connection from 10.180.168.192:56342 failed
	at hudson.remoting.Channel.call(Channel.java:1004)
	at org.jfrog.hudson.pipeline.common.docker.utils.DockerAgentUtils.pushImage(DockerAgentUtils.java:129)
	at org.jfrog.hudson.pipeline.common.executors.DockerExecutor.execute(DockerExecutor.java:70)
	at org.jfrog.hudson.pipeline.declarative.steps.docker.DockerPushStep$Execution.run(DockerPushStep.java:96)
	at org.jfrog.hudson.pipeline.declarative.steps.docker.DockerPushStep$Execution.run(DockerPushStep.java:71)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:359)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745):1
```

**Comment by pjdarton** [comment]
@ericcitaire `java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;C)V`
What do you think?
Is this a similar issue to #782 ?

**Comment by ericcitaire** [comment]
Well, this one is really strange.

If I read correctly the method signature, it corresponds to the overload `Preconditions.checkArgument(boolean b, String s, char c)`, which [appeared in Guava 20.0, according to its javadoc](https://github.com/google/guava/blob/master/guava/src/com/google/common/base/Preconditions.java#L173). But [docker-java depends on Guava 19.0](https://github.com/docker-java/docker-java/blob/3.1.5/pom.xml#L71).

What am I missing?

**Comment by ericcitaire** [comment]
Unless docker-java was built with `-Dguava.version=20.0`!? I'll to build docker-java 3.1.5 locally.

**Comment by ericcitaire** [comment]
That's weird :

```
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;C)V
	at com.google.common.io.BaseEncoding$Alphabet.<init>(BaseEncoding.java:458)
```

In Guava 19.0, There is no call to `checkArgument` at [line 458 of `BaseEncoding.java`](https://github.com/google/guava/blob/v19.0/guava/src/com/google/common/io/BaseEncoding.java#L458).

The code calling `checkArgument` [moved to line 458 in Guava 24.0](https://github.com/google/guava/blob/v24.0/guava/src/com/google/common/io/BaseEncoding.java#L458).

**Comment by ericcitaire** [comment]
> Well, this one is really strange.
> 
> If I read correctly the method signature, it corresponds to the overload `Preconditions.checkArgument(boolean b, String s, char c)`, which [appeared in Guava 20.0, according to its javadoc](https://github.com/google/guava/blob/master/guava/src/com/google/common/base/Preconditions.java#L173). But [docker-java 3.1.5 depends on Guava 19.0](https://github.com/docker-java/docker-java/blob/3.1.5/pom.xml#L71).
> 
> What am I missing?

The method signature used with Guava 19.0 for parameters `checkArgument(boolean b, String s, char c)` is `checkArgument(boolean b, String s, Object... o)`.

That's why it compiles.

**Comment by ericcitaire** [comment]
In Guava 19.0, there is nothing in [`BaseEncoding` at line 322](https://github.com/google/guava/blob/v19.0/guava/src/com/google/common/io/BaseEncoding.java#L322) except javadoc and there's only [a closing bracket at line 919](https://github.com/google/guava/blob/v19.0/guava/src/com/google/common/io/BaseEncoding.java#L919).

And [jenkins-artifactory-plugin depends on Guava 18.0](https://github.com/jfrog/jenkins-artifactory-plugin/blob/master/pom.xml#L400). Still nothing in [`BaseEncoding` at line 322](https://github.com/google/guava/blob/v18.0/guava/src/com/google/common/io/BaseEncoding.java#L322) except an annotation and there's [no line 919](https://github.com/google/guava/blob/v18.0/guava/src/com/google/common/io/BaseEncoding.java#L919).

That's definitely not Guava 19.0 used here, nor Guava 18.0. It's really confusing...

**Comment by ericcitaire** [comment]
I just realized that this error has nothing to do with docker-plugin or docker-java-api. The Artifactory plugin doesn't depend on any of these plugins. It depends directly on docker-java 3.1.2.

According to Jenkins documentation on [Dependencies and Class Loading](https://jenkins.io/doc/developer/plugin-development/dependencies-and-class-loading/), this error is unlikely to be related to docker-plugin or docker-java-api. Unless I misread it.

You should probably open an issue on [the Artifactory plugin](https://github.com/jfrog/jenkins-artifactory-plugin).

**Comment by ericcitaire** [comment]
@bhoppeadoy out of curiosity : what is the benefit of using [`rtDockerPush()`](https://jenkins.io/doc/pipeline/steps/artifactory/#rtdockerpush-run-artifactory-docker-push) instead of `Image.push()` from [Docker Pipeline plugin](https://plugins.jenkins.io/docker-workflow/) or [`step([$class: 'DockerBuilderPublisher'])`](https://jenkins.io/doc/pipeline/steps/docker-plugin/#stepclass-dockerbuilderpublisher-build-publish-docker-image) from docker-plugin?

**Comment by ericcitaire** [comment]
> You should probably open an issue on [the Artifactory plugin](https://github.com/jfrog/jenkins-artifactory-plugin).

Actually, the issue already exists : jfrog/jenkins-artifactory-plugin#268.

**Comment by bhoppeadoy** [comment]
I can confirm downgrading OWASP solved the issue for me as well.

Thanks everyone!
