### ISSUE TITLE
The Readtimeout property do not apply when the connection is lost

### ISSUE THREAD

**Issue by mat1e** [jenkinsci/docker-plugin#813]
We are using Jenkins with docker plugin and sometimes, when our docker host is overloaded, we can have a thread wich run indefinitely and block all new provision of docker agents.

Here is the thread in question : 

```
Computer.threadPoolForRemoting [#7341]" id=157047 (0x26577) state=WAITING cpu=69%
    - waiting on <0x0f6ab72c> (a java.util.concurrent.CountDownLatch$Sync)
    - locked <0x0f6ab72c> (a java.util.concurrent.CountDownLatch$Sync)
    at java.base@11.0.5/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.5/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
    at java.base@11.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
    at java.base@11.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1039)
    at java.base@11.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1345)
    at java.base@11.0.5/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:232)
    at com.github.dockerjava.core.async.ResultCallbackTemplate.awaitCompletion(ResultCallbackTemplate.java:92)
    at com.github.dockerjava.netty.NettyInvocationBuilder$ResponseCallback.awaitResult(NettyInvocationBuilder.java:60)
    at com.github.dockerjava.netty.NettyInvocationBuilder.get(NettyInvocationBuilder.java:139)
    at com.github.dockerjava.core.exec.ListContainersCmdExec.execute(ListContainersCmdExec.java:44)
    at com.github.dockerjava.core.exec.ListContainersCmdExec.execute(ListContainersCmdExec.java:15)
    at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
    at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
    at com.nirima.jenkins.plugins.docker.DockerCloud.countContainersInDocker(DockerCloud.java:615)
    at com.nirima.jenkins.plugins.docker.DockerCloud.canAddProvisionedSlave(DockerCloud.java:633)
    at com.nirima.jenkins.plugins.docker.DockerCloud.provision(DockerCloud.java:352)
    at io.jenkins.docker.FastNodeProvisionerStrategy.applyFoCloud(FastNodeProvisionerStrategy.java:72)
    at io.jenkins.docker.FastNodeProvisionerStrategy.apply(FastNodeProvisionerStrategy.java:44)
    at hudson.slaves.NodeProvisioner.update(NodeProvisioner.java:334)
    at hudson.slaves.NodeProvisioner.lambda$suggestReviewNow$1(NodeProvisioner.java:183)
    at hudson.slaves.NodeProvisioner$$Lambda$495/0x00000007c14ca040.run(Unknown Source)
    at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
    at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
    at java.base@11.0.5/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base@11.0.5/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base@11.0.5/java.lang.Thread.run(Thread.java:834)
```

I did many tests by mocking docker apis to understand why this happens.

With a timeout set to 60s and the return of the api set to 90s, I got a readtimeout like expected : 
`java.net.SocketTimeoutException: Read timed out: No data received within 60000ms.  Perhaps the docker API`

But when I stop the api server during the call (like a crash) the Thread continu to wait indefinitely...
It happens when I ran the api server on CentOS server and my Jenkins on my computer.

With both on my local computer, it notify me that the socket is close and I got an exception as expected : 
```
java.io.IOException: Une connexion existante a dû être fermée par l’hôte distant
  at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method)
  at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
  at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
  at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
  at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
  at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
  at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253)
  at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1133)
  at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
  at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  at java.base/java.lang.Thread.run(Thread.java:834) 
```

Do you have an idea how to prevent this ? Is there a solution or an update to do to the Netty ?

Here is the context when the problem was encoutered first time : 
- Docker 1.13.1
- Jenkins 2.235.5
- OpenJDK 11.0.5 headless
- docker-plugin 1.2.0 which integrates **docker-java 3.1.5**

I tried with the last version on docker-plugin but got the same.

I tried to update docker-java into docker-plugin to **3.2.5** with no effect. And I try to update Netty to the last version in docker-java and it has no effect too.

I did a little repository to reproduce the bug with Jenkins with a tutorial : 
https://github.com/groupe-edf/jenkins-docker-timeout-issue

**Comment by realitix** [comment]
Hello, I worked on the problem and I localised where the Connection refused exception occurs.

It's in the docker-java [HERE](https://github.com/docker-java/docker-java/blob/3.1.5/src/main/java/com/github/dockerjava/netty/NettyInvocationBuilder.java#L135)

Code to update to catch the exception :

```
try(ResponseCallback<T> callback = new ResponseCallback<T>()) {
            get(typeReference, callback);

            return callback.awaitResult();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
```

Sadly that's not fixing the problem but it's a first stab

**Comment by pjdarton** [comment]
This sounds like a bug in the docker-java code.
The Jenkins docker-plugin _uses_ the docker-java code but it does not control the docker-java code.  You'll need to get the issue fixed in the docker-java code.
