### ISSUE TITLE
Can't mount NPIPE in version 1.2.3

### ISSUE THREAD

**Issue by pega-roska** [jenkinsci/docker-plugin#850]
### Version report

Jenkins and plugins versions report:

```
Jenkins: 2.303.1
OS: Linux - 3.10.0-1160.36.2.el7.x86_64
---
docker-commons:1.17
jdk-tool:1.5
pipeline-graph-analysis:1.11
script-security:1.78
command-launcher:1.6
pipeline-rest-api:2.19
cloudbees-folder:6.16
bouncycastle-api:2.23
docker-workflow:1.26
structs:1.23
jsch:0.1.55.2
workflow-step-api:2.24
scm-api:2.6.5
workflow-api:2.46
junit:1.52
workflow-job:2.41
antisamy-markup-formatter:2.1
token-macro:266.v44a80cf277fd
build-timeout:1.20
credentials:2.5
git-client:3.9.0
ssh-credentials:1.19
plain-credentials:1.7
git-server:1.10
credentials-binding:1.27
github-api:1.123
timestamper:1.13
workflow-cps-global-lib:2.21
workflow-support:3.8
durable-task:1.39
workflow-durable-task-step:2.39
matrix-project:1.19
resource-disposer:0.16
git:4.8.2
ws-cleanup:0.39
ant:1.11
gradle:1.37.1
pipeline-milestone-step:1.3.2
display-url-api:2.3.5
jquery-detached:1.2.1
github:1.34.0
jackson2-api:2.12.4
ace-editor:1.1
workflow-scm-step:2.13
workflow-cps:2.93
mailer:1.34
pipeline-input-step:2.12
pipeline-stage-step:2.5
handlebars:3.0.8
momentjs:1.1.1
branch-api:2.6.5
pipeline-stage-view:2.19
pipeline-build-step:2.15
workflow-multibranch:2.26
pipeline-model-api:1.9.1
pipeline-model-extensions:1.9.1
docker-plugin:1.2.3
apache-httpcomponents-client-4-api:4.5.13-1.0
lockable-resources:2.11
authentication-tokens:1.4
blueocean-jwt:1.24.8
workflow-basic-steps:2.24
pipeline-stage-tags-metadata:1.9.1
node-iterator-api:1.5.0
pipeline-model-definition:1.9.1
workflow-aggregator:2.6
github-branch-source:2.11.2
pipeline-github-lib:1.0
mapdb-api:1.0.9.0
subversion:2.14.4
ssh-slaves:1.33.0
matrix-auth:2.6.8
urltrigger:0.49
ldap:2.7
email-ext:2.83
jenkins-design-language:1.24.8
blueocean-core-js:1.24.8
blueocean-commons:1.24.8
blueocean-rest:1.24.8
pubsub-light:1.16
blueocean-pipeline-scm-api:1.24.8
htmlpublisher:1.25
variant:1.4
blueocean-web:1.24.8
groovy:2.4
favorite:2.3.3
blueocean-rest-impl:1.24.8
blueocean-pipeline-api-impl:1.24.8
blueocean-github-pipeline:1.24.8
blueocean-git-pipeline:1.24.8
blueocean-config:1.24.8
mercurial:2.15
handy-uri-templates-2-api:2.1.8-1.0
vsphere-cloud:2.26
cloudbees-bitbucket-branch-source:2.9.11
blueocean-bitbucket-pipeline:1.24.8
blueocean-dashboard:1.24.8
blueocean-personalization:1.24.8
pam-auth:1.6
blueocean-jira:1.24.8
jira:3.5
blueocean-display-url:2.4.1
sse-gateway:1.24
blueocean-events:1.24.8
blueocean-pipeline-editor:1.24.8
blueocean-i18n:1.24.8
blueocean-autofavorite:1.2.4
blueocean:1.24.8
docker-java-api:3.1.5.2
maven-plugin:3.12
copyartifact:1.46.1
javadoc:1.6
sshd:3.1.0
ansicolor:1.0.0
kubernetes-client-api:5.4.1
jjwt-api:0.11.2-9.c8b45b8bb173
kubernetes:1.30.1
plugin-util-api:2.4.0
trilead-api:1.0.13
run-condition:1.5
metrics:4.0.2.8
checks-api:1.7.2
snakeyaml-api:1.29.1
parameterized-trigger:2.41
echarts-api:5.1.2-11
google-oauth-plugin:1.0.6
oauth-credentials:0.4
jquery3-api:3.6.0-2
kubernetes-credentials:0.9.0
okhttp-api:3.14.9
periodicbackup:1.6
caffeine-api:2.9.2-29.v717aac953ff3
bootstrap4-api:4.6.0-3
popper2-api:2.9.3-1
conditional-buildstep:1.4.1
popper-api:1.16.1-2
font-awesome-api:5.15.4-1
bootstrap5-api:5.1.0-3


```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Controller:
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.9.2009 (Core)
Release:	7.9.2009
Codename:	Core

Agent node:
Edition: Windows Server 2019 Standard
Version: 1809
```

### Reproduction steps

- Create a Windows based docker template
- Enter a mount involving a named pipe, such as `type=npipe,source=\\.\pipe\docker_engine,destination=\\.\pipe\docker_engine`
- I also tried using type bind, but got a different error about it not being a directory

### Results

Expected result:

The agent was provisioned successfully with the named pipe mounted.

Actual result:
The agent fails to provision, with the below message in the log:
```
Unexpected exception encountered while provisioning agent Image of [REDACTED]
java.lang.IllegalArgumentException: No enum constant com.github.dockerjava.api.model.MountType.NPIPE
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.github.dockerjava.api.model.MountType.valueOf(MountType.java:9)
	at com.nirima.jenkins.plugins.docker.DockerTemplateBase.parseMountsString(DockerTemplateBase.java:875)
	at com.nirima.jenkins.plugins.docker.DockerTemplateBase.parseMountsStrings(DockerTemplateBase.java:857)
	at com.nirima.jenkins.plugins.docker.DockerTemplateBase.fillContainerConfig(DockerTemplateBase.java:786)
	at com.nirima.jenkins.plugins.docker.DockerTemplate.fillContainerConfig(DockerTemplate.java:272)
	at com.nirima.jenkins.plugins.docker.DockerTemplate.doProvisionNode(DockerTemplate.java:714)
	at com.nirima.jenkins.plugins.docker.DockerTemplate.provisionNode(DockerTemplate.java:676)
	at com.nirima.jenkins.plugins.docker.DockerCloud$1.run(DockerCloud.java:375)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Currently we are working around the issue by downgrading the plugin to 1.2.2 and restoring the previous configuration, where we had the volume configured as `\.\pipe\docker_engine:\\.\pipe\docker_engine`

**Comment by pjdarton** [comment]
This looks like it's an unintended consequence of #826 

@bguerin Can you comment?

**Comment by bguerin** [comment]
Bind mount is the way to go. You could post the stack with this configuration ?

**Comment by pega-roska** [comment]
@bguerin 
If I set it to bind (so the full value is `type=bind,source=\\.\pipe\docker_engine,destination=\\.\pipe\docker_engine`), I get this stacktrace:
```
Sep 07, 2021 4:41:13 PM SEVERE com.github.dockerjava.core.async.ResultCallbackTemplate onError

Error during callback
com.github.dockerjava.api.exception.BadRequestException: {"message":"invalid mount config for type \"bind\": source path must be a directory"}

	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:99)
	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:33)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1432)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1199)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1243)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

Also, npipe is explicitly mentioned in both the help for the field, and the referenced docker documentation, so I expect that's probably the type docker is expecting to receive when trying to mount that type of resource:
![image](https://user-images.githubusercontent.com/22380678/132408404-74ab210c-7ded-4630-b919-911751609517.png)
I'm not super familiar with how npipes work, but I don't think they're quite normal files like you'd find for things like unix sockets on Linux

**Comment by bguerin** [comment]
Thanks for the stack

`NPIPE` type is wrong, it does not exist :
https://github.com/docker-java/docker-java/blob/master/docker-java-api/src/main/java/com/github/dockerjava/api/model/MountType.java

And using `BIND` type, I cannot find any official documentation of the syntax ...

**Comment by pega-roska** [comment]
While `NPIPE` is not in the enum, it definitely exists in the docker documentation linked by the help for the field: https://docs.docker.com/engine/reference/commandline/service_create/#add-bind-mounts-volumes-or-memory-filesystems

As I said before, named pipes aren't normal files, so it's probable that this type will need to be passed to docker in order to mount them via this mechanism.  In order to address this use case, we'll probably need either the `npipe` type implemented in the docker-java library, or the option to specify the volumes how we used to without an explicit type.

**Comment by bguerin** [comment]
Many thanks for the link, that was what I looked for ...
Just looking at it in two seconds, I think npipe value is missing in the MountType Java API. I will dig into the API to confirm

**Comment by pega-roska** [comment]
docker-java should support npipe mounts now as of 3.2.13.  Are there any estimates on when this version will be adopted?

**Comment by pjdarton** [comment]
So, I'm a bit reticent on merging in PRs like #888 that bump the version of docker-java without allowing a period of time for the dust to settle (and the changes to the docker-java-api-plugin that provides docker-java are relatively recent).
I like there to be some time between "when upgrading is possible" and "when upgrading is mandatory" as, that way, early-adopters can find any issues and have the option of downgrading if necessary while things are fixed - I don't like having to rush out fixes.

...but I don't want folks such as yourself to be unable to use the latest Jenkins because of this plugin.


@pega-roska Can you help me understand *when* this inability to upgrade Jenkins is going to hit?
My [current understanding](https://www.jenkins.io/blog/2021/11/09/guava-upgrade/) is that Jenkins 2.320 (released last November) included the Guava changes so that would mean anyone using Jenkins 2.320 or later must use docker-plugin 1.2.3 or later (because the Guava changes went into that release along with #714).
i.e. I'm not aware of any _future_ reasons you can't upgrade, I think you're _already_ stuck ... so if that's the case, when is it going to start to be real-world problem? i.e. how far "out of date" are you allowed to be?  ...and if you're not already unable to upgrade, what's going to cause that and when will that be?

If I know roughly when things need to be done, I can then leave some time for the implications of the docker-java changes to be discovered (without forcing folks to have them) before I do another release that will force everyone to upgrade.
(as I don't want another flood of angry "it's all broken" github issues to respond to)

**Comment by pega-roska** [comment]
Since the functional change was entirely in the docker-java library, we were able to upgrade once the new docker-java-api-plugin released and this plugin supported running with it.  We are currently running with the latest version of docker-java-api-plugin and this plugin, and our npipe mounts are working successfully.
