### ISSUE TITLE
1.3.0: java.net.URISyntaxException: Illegal character in scheme name at index 0: "tcp://

### ISSUE THREAD

**Issue by Flow86** [jenkinsci/docker-plugin#936]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.375.2
OS: Linux - 5.10.0-0.deb10.16-amd64
---
ace-editor:1.1
ansicolor:1.0.2
ant:481.v7b_09e538fcca
antisamy-markup-formatter:155.v795fb_8702324
apache-httpcomponents-client-4-api:4.5.13-138.v4e7d9a_7b_a_e61
authentication-tokens:1.4
authorize-project:1.4.0
basic-branch-build-strategies:71.vc1421f89888e
bootstrap4-api:4.6.0-5
bootstrap5-api:5.2.1-3
bouncycastle-api:2.27
branch-api:2.1071.v1a_188a_562481
build-blocker-plugin:1.7.8
build-timeout:1.28
caffeine-api:2.9.3-65.v6a_47d0f4d1fe
checks-api:1.8.1
cloud-stats:267.v577e3742c282
cloudbees-folder:6.800.v71307ca_b_986b
command-launcher:90.v669d7ccb_7c31
commons-lang3-api:3.12.0-36.vd97de6465d5b_
commons-text-api:1.10.0-27.vb_fa_3896786a_7
config-file-provider:3.11.1
copyartifact:681.va_a_298c7f9c01
credentials:1214.v1de940103927
credentials-binding:523.vd859a_4b_122e6
data-tables-api:1.12.1-4
display-url-api:2.3.7
docker-build-step:2.9
docker-commons:1.21
docker-java-api:3.2.13-37.vf3411c9828b9
docker-plugin:1.3.0
docker-workflow:563.vd5d2e5c4007f
durable-task:504.vb10d1ae5ba2f
echarts-api:5.4.0-1
email-ext:2.93
extended-read-permission:3.2
external-monitor-job:203.v683c09d993b_9
font-awesome-api:6.2.1-1
git:5.0.0
git-client:4.1.0
git-parameter:0.9.18
git-server:99.va_0826a_b_cdfa_d
github:1.36.1
github-api:1.303-400.v35c2d8258028
github-branch-source:1701.v00cc8184df93
gitlab-api:5.0.1-78.v47a_45b_9f78b_7
gitlab-branch-source:644.va_a_66886e07b_5
gitlab-oauth:1.16
gitlab-plugin:1.6.0
handlebars:3.0.8
handy-uri-templates-2-api:2.1.8-22.v77d5b_75e6953
instance-identity:142.v04572ca_5b_265
ionicons-api:31.v4757b_6987003
jackson2-api:2.14.1-313.v504cdd45c18b
jakarta-activation-api:2.0.1-2
jakarta-mail-api:2.0.1-2
javadoc:226.v71211feb_e7e9
javax-activation-api:1.2.0-5
javax-mail-api:1.6.2-8
jaxb:2.3.7-1
jdk-tool:63.v62d2fd4b_4793
jersey2-api:2.38-1
jjwt-api:0.11.5-77.v646c772fddb_0
jnr-posix-api:3.1.16-1
job-dsl:1.81
jquery:1.12.4-1
jquery3-api:3.6.1-2
jsch:0.1.55.61.va_e9ee26616e7
junit:1166.va_436e268e972
ldap:659.v8ca_b_a_fe79fa_d
lockable-resources:1113.vf66761f17f1e
mailer:438.v02c7f0a_12fa_4
matrix-auth:3.1.6
matrix-project:785.v06b_7f47b_c631
maven-plugin:3.20
mina-sshd-api-common:2.9.2-50.va_0e1f42659a_a
mina-sshd-api-core:2.9.2-50.va_0e1f42659a_a
modernstatus:1.3
momentjs:1.1.1
okhttp-api:4.9.3-108.v0feda04578cf
pam-auth:1.10
pegdown-formatter:1.3
pipeline-build-step:2.18
pipeline-graph-analysis:202.va_d268e64deb_3
pipeline-groovy-lib:629.vb_5627b_ee2104
pipeline-input-step:466.v6d0a_5df34f81
pipeline-milestone-step:111.v449306f708b_7
pipeline-model-api:2.2118.v31fd5b_9944b_5
pipeline-model-definition:2.2118.v31fd5b_9944b_5
pipeline-model-extensions:2.2118.v31fd5b_9944b_5
pipeline-multibranch-defaults:2.1
pipeline-rest-api:2.30
pipeline-stage-step:305.ve96d0205c1c6
pipeline-stage-tags-metadata:2.2118.v31fd5b_9944b_5
pipeline-stage-view:2.30
pipeline-utility-steps:2.15.0
plain-credentials:143.v1b_df8b_d3b_e48
plugin-util-api:2.20.0
popper-api:1.16.1-3
popper2-api:2.11.6-2
scm-api:631.v9143df5b_e4a_a
script-security:1229.v4880b_b_e905a_6
simple-theme-plugin:136.v23a_15f86c53d
snakeyaml-api:1.33-90.v80dcb_3814d35
ssh-credentials:305.v8f4381501156
ssh-slaves:2.854.v7fd446b_337c9
sshd:3.275.v9e17c10f2571
structs:324.va_f5d6774f3a_d
token-macro:321.vd7cc1f2a_52c8
trilead-api:2.84.v72119de229b_7
variant:59.vf075fe829ccb
windows-slaves:1.8.1
workflow-aggregator:590.v6a_d052e5a_a_b_5
workflow-api:1208.v0cc7c6e0da_9e
workflow-basic-steps:994.vd57e3ca_46d24
workflow-cps:3606.v0b_d8b_e512dcf
workflow-durable-task-step:1223.v7f1a_98a_8863e
workflow-job:1268.v6eb_e2ee1a_85a
workflow-multibranch:716.vc692a_e52371b_
workflow-scm-step:400.v6b_89a_1317c9a_
workflow-step-api:639.v6eca_cd8c04a_a_
workflow-support:839.v35e2736cfd5c

  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux / Docker

### Reproduction steps

- Update from 1.2.10 to 1.3.0
- Set Docker Host URI to an `tcp://host:port` address as stated in the help box (or have it that way before the update)
- Click on "Test connection"
- Get `java.net.URISyntaxException: Illegal character in scheme name at index 0: tcp://host:port` exception

### Expected Results

docker container agent is correctly created & started.

### Actual Results

No docker container agent is created/started
```
java.net.URISyntaxException: Illegal character in scheme name at index 0: "tcp://dind:2375"
#011at java.base/java.net.URI$Parser.fail(URI.java:2913)
#011at java.base/java.net.URI$Parser.checkChars(URI.java:3084)
#011at java.base/java.net.URI$Parser.checkChar(URI.java:3094)
#011at java.base/java.net.URI$Parser.parse(URI.java:3109)
#011at java.base/java.net.URI.<init>(URI.java:600)
#011at java.base/java.net.URI.create(URI.java:881)
Caused: java.lang.IllegalArgumentException: Illegal character in scheme name at index 0: "tcp://dind:2375"
#011at java.base/java.net.URI.create(URI.java:883)
#011at com.github.dockerjava.core.DefaultDockerClientConfig$Builder.withDockerHost(DefaultDockerClientConfig.java:360)
#011at com.github.dockerjava.core.DefaultDockerClientConfig$Builder.withProperties(DefaultDockerClientConfig.java:342)
#011at com.github.dockerjava.core.DefaultDockerClientConfig.createDefaultConfigBuilder(DefaultDockerClientConfig.java:221)
#011at com.github.dockerjava.core.DefaultDockerClientConfig.createDefaultConfigBuilder(DefaultDockerClientConfig.java:210)
#011at com.github.dockerjava.core.DockerClientBuilder.getInstance(DockerClientBuilder.java:25)
#011at io.jenkins.docker.client.DockerAPI.makeClient(DockerAPI.java:257)
#011at io.jenkins.docker.client.DockerAPI.getOrMakeClient(DockerAPI.java:202)
#011at io.jenkins.docker.client.DockerAPI.getClient(DockerAPI.java:171)
#011at io.jenkins.docker.client.DockerAPI.getClient(DockerAPI.java:154)
#011at com.nirima.jenkins.plugins.docker.DockerContainerWatchdog.processCloud(DockerContainerWatchdog.java:207)
#011at com.nirima.jenkins.plugins.docker.DockerContainerWatchdog.execute(DockerContainerWatchdog.java:148)
#011at hudson.model.AsyncPeriodicWork.lambda$doRun$0(AsyncPeriodicWork.java:102)
#011at java.base/java.lang.Thread.run(Thread.java:829)
``` 

### Anything else?

After downgrading to 1.2.10 again, everything works as expected (i.e connection to docker is successfully established)

**Comment by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [comment]
It's strange, because I have the same situation but everything works:
 - Jenkins-2.375.3
 - docker-plugin-1.3.0
 - Docker Host URI = `tcp://jenkins-agent.local.domain:2376` with X.509 certs authentication

and everything works - "test connection" as well as containers start during the execution of jobs.
It worked before upgraid to 1.3.0 and after.

Did a simple test in Jenkins groovy console:

```groovy
println new URI('tcp://dind:2375')
println '---'
println new URI('"tcp://dind:2375"')
```
```
tcp://dind:2375
---
java.net.URISyntaxException: Illegal character in scheme name at index 0: "tcp://dind:2375"
	at java.base/java.net.URI$Parser.fail(Unknown Source)
	at java.base/java.net.URI$Parser.checkChars(Unknown Source)
	at java.base/java.net.URI$Parser.checkChar(Unknown Source)
	at java.base/java.net.URI$Parser.parse(Unknown Source)
	at java.base/java.net.URI.<init>(Unknown Source)
        .....
```

Looks like your docker URI is specified with quotes (but should not).
Can you check ?

**Comment by Flow86** [comment]
weird, its not specified with quotes though:

![grafik](https://user-images.githubusercontent.com/656249/223547161-1f30bfcb-59df-4a91-b18e-32024fcd5cef.png)

**Comment by Flow86** [comment]
or a better image:
![grafik](https://user-images.githubusercontent.com/656249/223548121-8cbc716b-8891-4208-9dbc-6bacfc8b5434.png)

**Comment by Flow86** [comment]
inside the script console, it does work btw:

```
println new URI('tcp://dind:2375')
println '---'
println new URI('"tcp://dind:2375"')
```


``` 
tcp://dind:2375
---
java.net.URISyntaxException: Illegal character in scheme name at index 0: "tcp://dind:2375"
	at java.base/java.net.URI$Parser.fail(URI.java:2913)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3084)
	at java.base/java.net.URI$Parser.checkChar(URI.java:3094)
	at java.base/java.net.URI$Parser.parse(URI.java:3109)
	at java.base/java.net.URI.<init>(URI.java:600)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:238)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:250)
	at Script1.run(Script1.groovy:3)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:574)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:612)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:583)
	at hudson.util.RemotingDiagnostics$Script.call(RemotingDiagnostics.java:149)
	at hudson.util.RemotingDiagnostics$Script.call(RemotingDiagnostics.java:118)
	at hudson.remoting.LocalChannel.call(LocalChannel.java:47)
	at hudson.util.RemotingDiagnostics.executeGroovy(RemotingDiagnostics.java:115)
	at jenkins.model.Jenkins._doScript(Jenkins.java:4729)
	at jenkins.model.Jenkins.doScript(Jenkins.java:4700)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:397)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:409)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:207)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:140)
	at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:558)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:59)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:762)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:894)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:830)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:894)
	at org.kohsuke.stapler.MetaClass$9.dispatch(MetaClass.java:475)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:762)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:894)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:690)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:240)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:157)
	at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:129)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
	at jenkins.security.ResourceDomainFilter.doFilter(ResourceDomainFilter.java:81)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
	at org.jenkinsci.plugins.modernstatus.ModernStatusFilter.doFilter(ModernStatusFilter.java:50)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:160)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:154)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:94)
	at jenkins.security.AcegiSecurityExceptionFilter.doFilter(AcegiSecurityExceptionFilter.java:52)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:54)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:122)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:116)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:109)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:106)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:97)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:223)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:217)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:97)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:63)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:111)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:172)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:53)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:86)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at jenkins.security.SuspiciousRequestFilter.doFilter(SuspiciousRequestFilter.java:38)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:549)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1571)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1383)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1544)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1305)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:139)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:933)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1077)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by Flow86** [comment]
Sorry for the notification spam:

running
```
println(Jenkins.getInstance().clouds)
```
gets me:

```
[DockerCloud{name='docker', dockerApi=DockerAPI{dockerHost=DockerServerEndpoint[tcp://dind:2375;credentialsId=null] ....
```

so no "" in there?

**Comment by Peter-Darton-i2** [comment]
My guess is that the `"` thing is a false alarm; it's probably just the error message that's wrapping the actual value in quotes so that it'd be obvious if there were spaces around it etc.
i.e. the code is probably saying `Illegal character in scheme name at index 0: "${actualValue}"` or somesuch.

I'd suggest you use the groovy console to examine each character of the string in turn, e.g. turn it into an array of bytes and hexdump it so you can see _exactly_ what you've got there.
In my professional life, I've traced more than one "weird bug" to invisible characters in strings making things be invalid while appearing to be correct; any string that can contain unicode characters could include weird (and potentially invisible) stuff.
e.g. we had an issue not long ago at work where a sysadmin had copy/pasted data from a browser, and the browser had "helpfully" added an extra space (which wasn't present in the copied data) to the end of each line that was pasted, and so we ended up with a user group called e.g. "my-user-group " instead of "my-user-group".
...but unicode allows for much more hard-to-spot things than just unwanted spaces, e.g. text direction characters are invisible.

...and if you do hexdump it, make sure you hexdump the actual string from the cloud config, not just the string you copy/paste from the WebUI form.


(Also, if you have access to the Jenkins controller's filesystem, take a look at the config xml file and see what's in there. If that's just plain ASCII and there's no weird characters then my hunch is likely to be wrong)

**Comment by Flow86** [comment]
I don't think there are any weird chars in there:

```
println(new String(Jenkins.getInstance().clouds[0].dockerApi.dockerHost.getUri()).getBytes().encodeHex())
```

```
74 63 70 3a 2f 2f 64 69 6e 64 3a 32 33 37 35
t  c  p  :  /  /  d  i  n  d  :  2  3  7  5
```

**Comment by pjdarton** [comment]
Ah, OK, well there goes that theory then ☹️ 
I think that's indisputable proof that the 1st character _isn't_ a weird one.
It looks like [the code](https://github.com/jenkinsci/docker-plugin/blob/docker-plugin-1.3.0/src/main/java/io/jenkins/docker/client/DockerAPI.java#L171) calls `dockerHost.getUri()` itself, so if that's returning those bytes and those bytes are OK, that suggests that the error might not be being quite as informative as one would hope.

So, the next step I guess would be to determine exactly what JVM you're using, find the source code for that, and then trace the deepest levels (i.e. the first few methods/lines-of-code) of that stacktrace to try to figure out what _else_ might cause that exception message.

**Comment by Flow86** [comment]
Its the default JVM from the docker container (jenkins/jenkins:lts)

**Comment by basil** [comment]
This is user error. You set the `DOCKER_HOST` environment variable to the literal string `"tcp://127.0.0.1:2375"` (with quotes). It is expected that the software would fail in this scenario. The recommendation is not to set `DOCKER_HOST` to an invalid value.

**Comment by Flow86** [comment]
@basil 
note: the environment variable did not had quotes. I would assume that the value I enter into the cloud configuration takes precedence over any value coming magically from an environment variable. At least it should be documented that an environment variable is taken into account instead to avoid these errors in future.

**Comment by basil** [comment]
I think you are mistaken about the environment variable not having had quotes. I am not going to take any further action about this issue. If you think the documentation can be improved, then submit a documentation PR.
