### ISSUE TITLE
Can't build: java.lang.NoClassDefFoundError: org/jenkinsci/plugins/tokenmacro/TokenMacro

### ISSUE THREAD

**Issue by marcellodesales** [jenkinsci/docker-plugin#94]
Hi there,

I got the following error while trying to build:
```
Docker Build
FATAL: org/jenkinsci/plugins/tokenmacro/TokenMacro
java.lang.NoClassDefFoundError: org/jenkinsci/plugins/tokenmacro/TokenMacro
    at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher.getTag(DockerBuilderPublisher.java:172)
    at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher.perform(DockerBuilderPublisher.java:56)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
    at hudson.model.Build$BuildExecution.build(Build.java:199)
    at hudson.model.Build$BuildExecution.doRun(Build.java:160)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:533)
    at hudson.model.Run.execute(Run.java:1745)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:89)
    at hudson.model.Executor.run(Executor.java:240)
Caused by: java.lang.ClassNotFoundException: org.jenkinsci.plugins.tokenmacro.TokenMacro
    at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1375)
    at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1325)
    at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1078)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    ... 11 more
```

**Comment by KostyaSha** [comment]
@towe75 please try new hpi from https://jenkins.ci.cloudbees.com/job/plugins/job/docker-plugin/246/com.nirima$docker-plugin/ and open new issue with providing https://wiki.jenkins-ci.org/display/JENKINS/How+to+report+an+issue#Howtoreportanissue-WhatinformationtoprovideforEnvironmentandDescription
